/**
 * The General Roman Calendar in Czech.
 *
 * Transcribed from GCatholic's Czech edition of the Czech Republic's
 * calendar. `../names.svelte.ts` has what these are, where they came from,
 * and the two things they are not.
 *
 * 212 of the Calendar's 218. The 6 absent are the ones the Czech Republic
 * keeps someone else on the day of — `cyril-methodius` among them — so this
 * edition never prints them and they go on falling back to English, which is
 * what `celebrationName` is for.
 */
export const cs: Record<string, string> = {
	'basil-gregory': 'Sv. Basila Velikého a Řehoře Naziánského, biskupů a učitelů církve',
	'holy-name-of-jesus': 'Nejsvětějšího Jména Ježíš',
	'raymond-of-penyafort': 'Sv. Rajmunda z Peñafortu, kněze',
	hilary: 'Sv. Hilaria, biskupa a učitele církve',
	'anthony-abbot': 'Sv. Antonína, opata',
	fabian: 'Sv. Fabiána, papeže a mučedníka',
	sebastian: 'Sv. Šebestiána, mučedníka',
	agnes: 'Sv. Anežky Římské, panny a mučednice',
	'vincent-deacon': 'Sv. Vincence, jáhna a mučedníka',
	'francis-de-sales': 'Sv. Františka Saleského, biskupa a učitele církve',
	'conversion-of-paul': 'Obrácení svatého Pavla, apoštola',
	'timothy-titus': 'Sv. Timoteje a Tita, biskupů',
	'angela-merici': 'Sv. Anděly Mericiové, panny',
	'thomas-aquinas': 'Sv. Tomáše Akvinského, kněze a učitele církve',
	'john-bosco': 'Sv. Jana Boska, kněze',
	'presentation-of-the-lord': 'Uvedení Páně do chrámu',
	blaise: 'Sv. Blažeje, biskupa a mučedníka',
	ansgar: 'Sv. Ansgara, biskupa',
	agatha: 'Sv. Agáty, panny a mučednice',
	'paul-miki': 'Sv. Pavla Mikiho a druhů, mučedníků',
	'jerome-emiliani': 'Sv. Jeronýma Emilianiho',
	'josephine-bakhita': 'Sv. Josefíny Bakhity, panny',
	scholastica: 'Sv. Scholastiky, panny',
	'our-lady-of-lourdes': 'Panny Marie Lurdské',
	'peter-damian': 'Sv. Petra Damianiho, biskupa a učitele církve',
	'chair-of-peter': 'Stolce svatého Petra, apoštola',
	polycarp: 'Sv. Polykarpa, biskupa a mučedníka',
	'gregory-of-narek': 'Sv. Řehoř z Nareku, opata a učitele církve',
	casimir: 'Sv. Kazimíra',
	'perpetua-felicity': 'Sv. Perpetuy a Felicity, mučednic',
	'john-of-god': 'Sv. Jana z Boha, řeholníka',
	'frances-of-rome': 'Sv. Františky Římské, řeholnice',
	patrick: 'Sv. Patrika, biskupa',
	'cyril-of-jerusalem': 'Sv. Cyrila Jeruzalémského, biskupa a učitele církve',
	joseph: 'Sv. Josefa, Snoubence Panny Marie',
	turibius: 'Sv. Turibia z Mongroveja, biskupa',
	annunciation: 'Zvěstování Páně',
	'francis-of-paola': 'Sv. Františka z Pauly, poustevníka',
	isidore: 'Sv. Izidora, biskupa a učitele církve',
	'vincent-ferrer': 'Sv. Vincence Ferrerského, kněze',
	'john-baptist-de-la-salle': 'Sv. Jana Křtitele de la Salle, kněze',
	stanislaus: 'Sv. Stanislava, biskupa a mučedníka',
	'martin-i': 'Sv. Martina I., papeže a mučedníka',
	anselm: 'Sv. Anselma, biskupa a učitele církve',
	adalbert: 'Sv. Vojtěcha, biskupa a mučedníka',
	fidelis: 'Sv. Fidela ze Sigmaringy, kněze a mučedníka',
	mark: 'Sv. Marka, evangelisty',
	'peter-chanel': 'Sv. Petra Chanela, kněze a mučedníka',
	'louis-de-montfort': 'Sv. Ludvíka Marie Grigniona z Montfortu, kněze',
	'catherine-of-siena': 'Sv. Kateřiny Sienské, panny a učitelky církve',
	'pius-v': 'Sv. Pia V., papeže',
	'joseph-the-worker': 'Sv. Josefa, dělníka',
	athanasius: 'Sv. Atanáše, biskupa a učitele církve',
	'philip-james': 'Sv. Filipa a Jakuba, apoštolů',
	'john-of-avila': 'Sv. Jan z Ávily, kněze a učitele církve',
	'nereus-achilleus': 'Sv. Nerea a Achillea, mučedníků',
	pancras: 'Sv. Pankráce, mučedníka',
	'our-lady-of-fatima': 'Panny Marie Fatimské',
	matthias: 'Sv. Matěje, apoštola',
	'john-i': 'Sv. Jana I., papeže a mučedníka',
	'bernardine-of-siena': 'Sv. Bernardina Sienského, kněze',
	'christopher-magallanes': 'Sv. Kryštofa Magallanese, kněze a druhů, mučedníků',
	'rita-of-cascia': 'Sv. Rity z Cascie, řeholnice',
	bede: 'Sv. Bedy Ctihodného, kněze a učitele církve',
	'gregory-vii': 'Sv. Řehoře VII., papeže',
	'mary-magdalene-de-pazzi': 'Sv. Marie Magdalény de ’Pazzi, panny',
	'philip-neri': 'Sv. Filipa Neriho, kněze',
	'augustine-of-canterbury': 'Sv. Augustina z Canterbury, biskupa',
	'paul-vi': 'Sv. Pavla VI., papeže',
	visitation: 'Navštívení Panny Marie',
	justin: 'Sv. Justina, mučedníka',
	'marcellinus-peter': 'Sv. Marcelina a Petra, mučedníků',
	'charles-lwanga': 'Sv. Karla Lwangy a druhů, mučedníků',
	boniface: 'Sv. Bonifáce, biskupa a mučedníka',
	norbert: 'Sv. Norberta, biskupa',
	ephrem: 'Sv. Efréma Syrského, jáhna a učitele církve',
	barnabas: 'Sv. Barnabáše, apoštola',
	'anthony-of-padua': 'Sv. Antonína z Padovy, kněze a učitele církve',
	romuald: 'Sv. Romualda, opata',
	'aloysius-gonzaga': 'Sv. Aloise Gonzagy, řeholníka',
	'paulinus-of-nola': 'Sv. Paulína Nolánského, biskupa',
	'fisher-more': 'Sv. Jana Fishera, biskupa, a Tomáše Mora, mučedníků',
	'birth-of-john-the-baptist': 'Narození svatého Jana Křtitele',
	'cyril-of-alexandria': 'Sv. Cyrila Alexandrijského, biskupa a učitele církve',
	irenaeus: 'Sv. Ireneje, biskupa, mučedníka a učitele církve',
	'peter-and-paul': 'Sv. Petra a Pavla, apoštolů',
	'first-martyrs-of-rome': 'Svatých prvomučedníků římských',
	'thomas-apostle': 'Sv. Tomáše, apoštola',
	'elizabeth-of-portugal': 'Sv. Alžběty Portugalské',
	'maria-goretti': 'Sv. Marie Gorettiové, panny a mučednice',
	'augustine-zhao-rong': 'Sv. Augustina Čao Žung, kněze, a druhů, mučedníků',
	benedict: 'Sv. Benedikta, opata',
	henry: 'Sv. Jindřicha',
	camillus: 'Sv. Kamila de Lellis, kněze',
	bonaventure: 'Sv. Bonaventury, biskupa a učitele církve',
	'our-lady-of-mount-carmel': 'Panny Marie Karmelské',
	apollinaris: 'Sv. Apolináře, biskupa a mučedníka',
	'lawrence-of-brindisi': 'Sv. Vavřince z Brindisi, kněze a učitele církve',
	'mary-magdalene': 'Sv. Marie Magdalény',
	bridget: 'Sv. Brigity, řeholnice',
	sharbel: 'Sv. Šarbela Makhlūfa, kněze',
	james: 'Sv. Jakuba, apoštola',
	'joachim-anne': 'Sv. Jáchyma a Anny, rodičů Panny Marie',
	'martha-mary-lazarus': 'Sv. Marty, Marie a Lazara',
	'peter-chrysologus': 'Sv. Petra Chryzologa, biskupa a učitele církve',
	'ignatius-of-loyola': 'Sv. Ignáce z Loyoly, kněze',
	'alphonsus-liguori': 'Sv. Alfonsa Marie z Liguori, biskupa a učitele církve',
	'eusebius-of-vercelli': 'Sv. Eusebia z Vercelli, biskupa',
	'peter-julian-eymard': 'Sv. Petra Juliána Eymarda, kněze',
	'john-vianney': 'Sv. Jana Marie Vianneye, kněze',
	'dedication-st-mary-major': 'Posvěcení římské baziliky Panny Marie',
	transfiguration: 'Proměnění Páně',
	'sixtus-ii': 'Sv. Sixta II., papeže, a druhů, mučedníků',
	cajetan: 'Sv. Kajetána, kněze',
	dominic: 'Sv. Dominika, kněze',
	'teresa-benedicta': 'Sv. Terezie Benedikty od Kříže, panny a mučednice',
	lawrence: 'Sv. Vavřince, jáhna a mučedníka',
	clare: 'Sv. Kláry, panny',
	'jane-frances-de-chantal': 'Sv. Jany Františky de Chantal, řeholnice',
	'pontian-hippolytus': 'Sv. Ponciána, papeže, a Hippolyta, kněze, mučedníků',
	'maximilian-kolbe': 'Sv. Maxmiliána Marie Kolbeho, kněze a mučedníka',
	assumption: 'Nanebevzetí Panny Marie',
	'stephen-of-hungary': 'Sv. Štěpána Uherského',
	'john-eudes': 'Sv. Jana Eudese, kněze',
	bernard: 'Sv. Bernarda, opata a učitele církve',
	'pius-x': 'Sv. Pia X., papeže',
	'queenship-of-mary': 'Panny Marie Královny',
	'rose-of-lima': 'Sv. Růženy z Limy, panny',
	bartholomew: 'Sv. Bartoloměje, apoštola',
	louis: 'Sv. Ludvíka',
	'joseph-calasanz': 'Sv. Josefa Kalasanského, kněze',
	monica: 'Sv. Moniky',
	augustine: 'Sv. Augustina, biskupa a učitele církve',
	'passion-of-john-the-baptist': 'Umučení sv. Jana Křtitele',
	'gregory-the-great': 'Sv. Řehoře Velikého, papeže a učitele církve',
	'teresa-of-calcutta': 'Sv. Terezie z Kalkaty, panny',
	'nativity-of-mary': 'Narození Panny Marie',
	'peter-claver': 'Sv. Petra Klavera, kněze',
	'holy-name-of-mary': 'Jména Panny Marie',
	'john-chrysostom': 'Sv. Jana Zlatoústého, biskupa a učitele církve',
	'exaltation-of-the-cross': 'Povýšení svatého Kříže',
	'our-lady-of-sorrows': 'Panny Marie Bolestné',
	'robert-bellarmine': 'Sv. Roberta Bellarmina, biskupa a učitele církve',
	hildegard: 'Sv. Hildegarda z Bingenu, panny a učitelky církve',
	januarius: 'Sv. Januária, biskupa a mučedníka',
	'andrew-kim': 'Sv. Ondřeje Kim Tae-gỏna, kněze, Pavla Chõng Ha-sanga a druhů, mučedníků',
	matthew: 'Sv. Matouše, apoštola a evangelisty',
	'padre-pio': 'Sv. Pia z Pietrelciny, kněze',
	'cosmas-damian': 'Sv. Kosmy a Damiána, mučedníků',
	'vincent-de-paul': 'Sv. Vincence z Paula, kněze',
	wenceslaus: 'Sv. Václava, mučedníka',
	archangels: 'Sv. Michaela, Gabriela a Rafaela, archandělů',
	jerome: 'Sv. Jeronýma, kněze a učitele církve',
	'therese-of-lisieux': 'Sv. Terezie od Dítěte Ježíše, panny a učitelky církve',
	'guardian-angels': 'Svatých andělů strážných',
	'francis-of-assisi': 'Sv. Františka z Assisi',
	faustina: 'Sv. Faustyna Kowalska, panny',
	bruno: 'Sv. Bruna, kněze',
	'our-lady-of-the-rosary': 'Panny Marie Růžencové',
	denis: 'Sv. Dionýsia, biskupa, a druhů, mučedníků',
	'john-leonardi': 'Sv. Jana Leonardiho, kněze',
	'john-henry-newman': 'Sv. John Henry Newman, kněze a učitele církve',
	'john-xxiii': 'Sv. Jana XXIII., papeže',
	'callistus-i': 'Sv. Kalista I., papeže a mučedníka',
	'teresa-of-avila': 'Sv. Terezie od Ježíše, panny a učitelky církve',
	hedwig: 'Sv. Hedviky, řeholnice',
	'margaret-mary-alacoque': 'Sv. Markéty Marie Alacoque, panny',
	'ignatius-of-antioch': 'Sv. Ignáce Antiochijského, biskupa a mučedníka',
	luke: 'Sv. Lukáše, evangelisty',
	'north-american-martyrs': 'Sv. Jana de Brébeuf a Izáka Joguese, kněží, a druhů, mučedníků',
	'paul-of-the-cross': 'Sv. Pavla od Kříže, kněze',
	'john-paul-ii': 'Sv. Jana Pavla II., papeže',
	'john-of-capistrano': 'Sv. Jana Kapistránského, kněze',
	'anthony-mary-claret': 'Sv. Antonína Marie Klareta, biskupa',
	'simon-jude': 'Sv. Šimona a Judy, apoštolů',
	'all-saints': 'Všech svatých',
	'martin-de-porres': 'Sv. Martina de Porres, řeholníka',
	'charles-borromeo': 'Sv. Karla Boromejského, biskupa',
	'dedication-of-the-lateran': 'Posvěcení lateránské baziliky',
	'leo-the-great': 'Sv. Lva Velikého, papeže a učitele církve',
	'martin-of-tours': 'Sv. Martina, biskupa',
	josaphat: 'Sv. Josafata, biskupa a mučedníka',
	'albert-the-great': 'Sv. Alberta Velikého, biskupa a učitele církve',
	'margaret-of-scotland': 'Sv. Markéty Skotské',
	gertrude: 'Sv. Gertrudy Veliké, panny',
	'elizabeth-of-hungary': 'Sv. Alžběty Uherské, řeholnice',
	'dedication-of-peter-and-paul': 'Posvěcení římských bazilik svatých apoštolů Petra a Pavla',
	'presentation-of-mary': 'Zasvěcení Panny Marie v Jeruzalémě',
	cecilia: 'Sv. Cecílie, panny a mučednice',
	'clement-i': 'Sv. Klementa I., papeže a mučedníka',
	columban: 'Sv. Kolumbána, opata',
	'andrew-dung-lac': 'Sv. Ondřeje Dung-Laca, kněze, a druhů, mučedníků',
	'catherine-of-alexandria': 'Sv. Kateřiny Alexandrijské, panny a mučednice',
	andrew: 'Sv. Ondřeje, apoštola',
	'francis-xavier': 'Sv. Františka Xaverského, kněze',
	'john-damascene': 'Sv. Jana Damašského, kněze a učitele církve',
	nicholas: 'Sv. Mikuláše, biskupa',
	ambrose: 'Sv. Ambrože, biskupa a učitele církve',
	'immaculate-conception': 'Panny Marie, počaté bez poskvrny prvotního hříchu',
	'juan-diego': 'Sv. Jana Didaka Cuauhtlatoatzina',
	'our-lady-of-loreto': 'Panny Marie Loretánské',
	'damasus-i': 'Sv. Damasa I. papeže',
	'our-lady-of-guadalupe': 'Panny Marie Guadalupské',
	lucy: 'Sv. Lucie, panny a mučednice',
	'john-of-the-cross': 'Sv. Jana od Kříže, kněze a učitele církve',
	'peter-canisius': 'Sv. Petra Kanisia, kněze a učitele církve',
	'john-of-kanty': 'Sv. Jana Kentského, kněze',
	stephen: 'Sv. Štěpána, prvomučedníka',
	'john-evangelist': 'Sv. Jana, apoštola a evangelisty',
	'holy-innocents': 'Svatých Mláďátek, mučedníků',
	'thomas-becket': 'Sv. Tomáše Becketa, biskupa a mučedníka',
	'sylvester-i': 'Sv. Silvestra I. papeže'
};
