/**
 * The General Roman Calendar in Danish.
 *
 * Transcribed from GCatholic's Danish edition of Denmark's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 210 of the Calendar's 218. The 8 absent are the ones Denmark keeps someone
 * else on the day of — `raymond-of-penyafort` among them — so this edition
 * never prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 */
export const da: Record<string, string> = {
	'basil-gregory': 'Skt. Basilius den Store og Gregor af Nazianz, biskopper og kirkelærere',
	'holy-name-of-jesus': 'Jesu hellige Navn',
	hilary: 'Skt. Hilarius, biskop og kirkelærer',
	'anthony-abbot': 'Skt. Antonius, abbed',
	fabian: 'Skt. Fabian, pave og martyr',
	sebastian: 'Skt. Sebastian, martyr',
	agnes: 'Skt. Agnes, jomfru og martyr',
	'vincent-deacon': 'Skt. Vincent, diakon og martyr',
	'francis-de-sales': 'Skt. Frans af Sales, biskop og kirkelærer',
	'conversion-of-paul': 'Den Hellige Apostel Paulus’ Omvendelse',
	'timothy-titus': 'Skt. Timoteus og Titus, biskopper',
	'angela-merici': 'Skt. Angela Merici, jomfru',
	'thomas-aquinas': 'Skt. Thomas af Aquino, præst og kirkelærer',
	'john-bosco': 'Skt. Johannes Bosco, præst',
	'presentation-of-the-lord': 'Herrens Fremstilling i Templet',
	agatha: 'Skt. Agathe, jomfru og martyr',
	'paul-miki': 'Skt. Paul Miki og lidelsesfæller, martyrer',
	'jerome-emiliani': 'Skt. Hieronymus Æmiliani',
	'josephine-bakhita': 'Skt. Josephina Bakhita, jomfru',
	scholastica: 'Skt. Scholastica, jomfru',
	'our-lady-of-lourdes': 'Den salige Jomfru Maria af Lourdes',
	'cyril-methodius': 'Skt. Cyrillus, munk og Methodius, biskop',
	'seven-founders': 'Servitterordenen af den salige Jomfru Marias 7 hellige grundlæggere',
	'peter-damian': 'Skt. Peter Damian, biskop og kirkelærer',
	'chair-of-peter': 'Skt. Apostlen Peters Stol',
	polycarp: 'Skt. Polycarp, biskop og martyr',
	'gregory-of-narek': 'Skt. Gregor af Narek, abbed og kirkelærer',
	casimir: 'Skt. Casimir',
	'perpetua-felicity': 'Skt. Perpetua og Felicitas, martyrer',
	'john-of-god': 'Skt. Johannes af Gud, ordensmand',
	'frances-of-rome': 'Skt. Francisca af Rom, ordenssøster',
	patrick: 'Skt. Patrick, biskop',
	'cyril-of-jerusalem': 'Skt. Cyrillus af Jerusalem, biskop og kirkelærer',
	joseph: 'Skt. Josef, Jomfru Marias brudgom',
	turibius: 'Skt. Turibius Mongrovejo, biskop',
	annunciation: 'Herrens Bebudelse',
	'francis-of-paola': 'Skt. Frans af Paola, eneboer',
	isidore: 'Skt. Isidor, biskop og kirkelærer',
	'vincent-ferrer': 'Skt. Vincent Ferrer, præst',
	'john-baptist-de-la-salle': 'Skt. Johannes Baptista de la Salle, præst',
	stanislaus: 'Skt. Stanislaus, biskop og martyr',
	'martin-i': 'Skt. Martin I, pave og martyr',
	anselm: 'Skt. Anselm, biskop og kirkelærer',
	george: 'Skt. Georg, martyr',
	adalbert: 'Skt. Adalbert, biskop og martyr',
	fidelis: 'Skt. Fidelis af Sigmaringen, præst og martyr',
	mark: 'Skt. Markus, evangelist',
	'peter-chanel': 'Skt. Peter Chanel, præst og martyr',
	'louis-de-montfort': 'Skt. Ludvig Maria Grignion de Montfort, præst',
	'catherine-of-siena': 'Skt. Katarina af Siena, jomfru og kirkelærer',
	'pius-v': 'Skt. Pius V, pave',
	'joseph-the-worker': 'Skt. Josef, Arbejderen',
	athanasius: 'Skt. Athanasius, biskop og kirkelærer',
	'philip-james': 'Skt. Filip og Jakob, apostle',
	'john-of-avila': 'Skt. Johannes af Ávila, præst og kirkelærer',
	'nereus-achilleus': 'Skt. Nereus og Achilleus, martyrer',
	pancras: 'Skt. Pancratius, martyr',
	'our-lady-of-fatima': 'Vor Frue af Fatima',
	matthias: 'Skt. Mattias, apostel',
	'bernardine-of-siena': 'Skt. Bernardin af Siena, præst',
	'christopher-magallanes': 'Skt. Kristoffer Magallánes, præst, og lidelsesfæller, martyrer',
	'rita-of-cascia': 'Skt. Rita af Cascia, ordenssøster',
	bede: 'Skt. Beda den Ærværdige, præst og kirkelærer',
	'gregory-vii': 'Skt. Gregor VII, pave',
	'mary-magdalene-de-pazzi': 'Skt. Maria Magdalene af Pazzi, jomfru',
	'philip-neri': 'Skt. Filip Neri, præst',
	'augustine-of-canterbury': 'Skt. Augustin af Canterbury, biskop',
	'paul-vi': 'Skt. Paul VI, pave',
	visitation: 'Den salige jomfru Marias besøg hos Elisabeth',
	justin: 'Skt. Justinus, martyr',
	'marcellinus-peter': 'Skt. Marcellinus og Peter, martyrer',
	'charles-lwanga': 'Skt. Karl Lwanga og lidelsesfæller, martyrer',
	boniface: 'Skt. Bonifatius, biskop og martyr',
	norbert: 'Skt. Norbert, biskop',
	ephrem: 'Skt. Efræm Syrer, diakon og kirkelærer',
	barnabas: 'Skt. Barnabas, apostel',
	'anthony-of-padua': 'Skt. Antonius af Padova, præst og kirkelærer',
	romuald: 'Skt. Romuald, abbed',
	'aloysius-gonzaga': 'Skt. Aloysius Gonzaga, ordensmand',
	'paulinus-of-nola': 'Skt. Paulinus af Nola, biskop',
	'fisher-more': 'Skt. John Fisher, biskop, og Thomas More, martyrer',
	'birth-of-john-the-baptist': 'Skt. Johannes Døbers Fødsel',
	'cyril-of-alexandria': 'Skt. Cyrillus af Alexandria, biskop og kirkelærer',
	irenaeus: 'Skt. Irenæus, biskop, martyr og kirkelærer',
	'peter-and-paul': 'Skt. Peter og Paulus, apostle',
	'first-martyrs-of-rome': 'De første romerske martyrer',
	'thomas-apostle': 'Skt. Thomas, apostel',
	'elizabeth-of-portugal': 'Skt. Elisabeth af Portugal',
	'anthony-zaccaria': 'Skt. Antonius Maria Zacharia, præst',
	'maria-goretti': 'Skt. Maria Goretti, jomfru og martyr',
	benedict: 'Skt. Benedikt, abbed',
	henry: 'Skt. Henrik',
	camillus: 'Skt. Kamillus af Lellis, præst',
	bonaventure: 'Skt. Bonaventura, biskop og kirkelærer',
	'our-lady-of-mount-carmel': 'Den salige Jomfru Maria af Karmel',
	'lawrence-of-brindisi': 'Skt. Laurentius af Brindisi, biskop og kirkelærer',
	'mary-magdalene': 'Skt. Maria Magdalene',
	bridget: 'Skt. Birgitta, ordenssøster',
	sharbel: 'Skt. Charbel Makhluf, præst',
	james: 'Skt. Jakob, apostel',
	'joachim-anne': 'Den hellige Joakim og den hellige Anna, Jomfru Marias forældre',
	'peter-chrysologus': 'Skt. Peter Chrysologus, biskop og kirkelærer',
	'ignatius-of-loyola': 'Skt. Ignatius af Loyola, præst',
	'alphonsus-liguori': 'Skt. Alfons Maria de´ Liguori, biskop og kirkelærer',
	'eusebius-of-vercelli': 'Skt. Eusebius af Vercelli, biskop',
	'peter-julian-eymard': 'Skt. Peter Julian Eymard, præst',
	'john-vianney': 'Skt. Johannes Maria Vianney, præst',
	'dedication-st-mary-major': 'Kirkevielsesfest for kirken Santa Maria Maggiore',
	transfiguration: 'Herrens Forklarelse',
	'sixtus-ii': 'Skt. Xystus II, pave, og lidelsesfæller, martyrer',
	cajetan: 'Skt. Cajetan, præst',
	dominic: 'Skt. Dominikus, præst',
	'teresa-benedicta': 'Skt. Theresa Benedicta af korset, jomfru og martyr',
	lawrence: 'Skt. Laurentius, diakon og martyr',
	clare: 'Skt. Klara, jomfru',
	'jane-frances-de-chantal': 'Skt. Johanne Franciska Chantal, ordenssøster',
	'pontian-hippolytus': 'Skt. Pontianus, pave, og Hippolyt, præst, martyrer',
	'maximilian-kolbe': 'Skt. Maximilian Maria Kolbe, præst og martyr',
	assumption: 'Jomfru Marias Optagelse i Himlen',
	'stephen-of-hungary': 'Skt. Stefan af Ungarn',
	'john-eudes': 'Skt. Johannes Eudes, præst',
	bernard: 'Skt. Bernhard, abbed og kirkelærer',
	'pius-x': 'Skt. Pius X, pave',
	'queenship-of-mary': 'Jomfru Maria, vor Dronning',
	'rose-of-lima': 'Skt. Rosa af Lima, jomfru',
	bartholomew: 'Skt. Bartholomæus, apostel',
	louis: 'Skt. Ludvig',
	'joseph-calasanz': 'Skt. Josef af Calasanz, præst',
	monica: 'Skt. Monika',
	augustine: 'Skt. Augustin, biskop og kirkelærer',
	'passion-of-john-the-baptist': 'Skt. Johannes Døberens Martyrium',
	'gregory-the-great': 'Skt. Gregor den Store, pave og kirkelærer',
	'teresa-of-calcutta': 'Skt. Teresa af Calcutta, jomfru',
	'nativity-of-mary': 'Jomfru Marias Fødsel',
	'peter-claver': 'Skt. Peter Claver, præst',
	'holy-name-of-mary': 'Jomfru Marias hellige navn',
	'john-chrysostom': 'Skt. Johannes Chrysostomos, biskop og kirkelærer',
	'exaltation-of-the-cross': 'Det hellige Kors’ Ophøjelse',
	'our-lady-of-sorrows': 'Den salige Jomfru Marias Smerter',
	'cornelius-cyprian': 'Skt. Cornelius, pave, og Cyprian, biskop, martyrer',
	'robert-bellarmine': 'Skt. Robert Bellarmin, biskop og kirkelærer',
	hildegard: 'Skt. Hildegard af Bingen, jomfru og kirkelærer',
	januarius: 'Skt. Januarius, biskop og martyr',
	'andrew-kim':
		'Skt. Andreas Kim Taegon, præst, og Paulus Chong Hasang og lidelsesfæller, martyrer',
	matthew: 'Skt. Mattæus, apostel og evangelist',
	'padre-pio': 'Skt. Pius de Pietrelcina, præst',
	'cosmas-damian': 'Skt. Cosmas og Damian, martyrer',
	'vincent-de-paul': 'Skt. Vincent af Paul, præst',
	wenceslaus: 'Skt. Wenceslaus, martyr',
	'lawrence-ruiz': 'Skt. Laurentius Ruiz og lidelsesfæller, martyrer',
	archangels: 'De Hellige Ærkeengle, Michael, Gabriel og Rafael',
	jerome: 'Skt. Hieronymus, præst og kirkelærer',
	'therese-of-lisieux': 'Skt. Therese af Jesusbarnet, jomfru og kirkelærer',
	'guardian-angels': 'De hellige værneengle',
	'francis-of-assisi': 'Skt. Frans af Assisi',
	faustina: 'Skt. Faustina Kowalska, jomfru',
	bruno: 'Skt. Bruno, præst',
	'our-lady-of-the-rosary': 'Den salige Jomfru Maria af Rosenkransen',
	denis: 'Skt. Dionysius, biskop, og lidelsesfæller, martyrer',
	'john-leonardi': 'Skt. Johannes Leonardi, præst',
	'john-henry-newman': 'Skt. John Henry Newman, præst og kirkelærer',
	'john-xxiii': 'Skt. Johannes XXIII, pave',
	'callistus-i': 'Skt. Callistus I, pave og martyr',
	'teresa-of-avila': 'Skt. Teresa af Jesus, jomfru og kirkelærer',
	hedwig: 'Skt. Hedvig, ordenssøster',
	'margaret-mary-alacoque': 'Skt. Margrethe Maria Alacoque, jomfru',
	'ignatius-of-antioch': 'Skt. Ignatius af Antiochia, biskop og martyr',
	luke: 'Skt. Lukas, evangelist',
	'north-american-martyrs':
		'Skt. Jean de Brébeuf og Isaac Jogues, præster, og lidelsesfæller, martyrer',
	'paul-of-the-cross': 'Skt. Paul af Korset, præst',
	'john-paul-ii': 'Skt. Johannes Paul II, pave',
	'john-of-capistrano': 'Skt. Johannes af Capestrano, præst',
	'anthony-mary-claret': 'Skt. Antonius Maria Claret, biskop',
	'simon-jude': 'Skt. Simon og Judas, apostle',
	'all-saints': 'Alle Helgen',
	'martin-de-porres': 'Skt. Martin af Porres, ordensmand',
	'charles-borromeo': 'Skt. Karl Borromæus, biskop',
	'dedication-of-the-lateran': 'Laterankirkens Indvielse',
	'leo-the-great': 'Skt. Leo den Store, pave og kirkelærer',
	'martin-of-tours': 'Skt. Martin af Tours, biskop',
	josaphat: 'Skt. Josaphat, biskop og martyr',
	'albert-the-great': 'Skt. Albert den Store, biskop og kirkelærer',
	'margaret-of-scotland': 'Skt. Margrethe af Skotland',
	gertrude: 'Skt. Gertrud, jomfru',
	'elizabeth-of-hungary': 'Skt. Elisabeth af Ungarn, ordenssøster',
	'dedication-of-peter-and-paul': 'Peters- og Pauls basilikaernes indvielse',
	'presentation-of-mary': 'Jomfru Marias fremstilling i templet',
	cecilia: 'Skt. Cæcilie, jomfru og martyr',
	'clement-i': 'Skt. Clemens I, pave og martyr',
	columban: 'Skt. Columban, abbed',
	'andrew-dung-lac': 'Skt. Andreas Dung-Lac, præst, og lidelsesfæller, martyrer',
	andrew: 'Skt. Andreas, apostel',
	'francis-xavier': 'Skt. Frans Xaver, præst',
	'john-damascene': 'Skt. Johannes af Damaskus, præst og kirkelærer',
	nicholas: 'Skt. Nicolaus, biskop',
	ambrose: 'Skt. Ambrosius, biskop og kirkelærer',
	'immaculate-conception': 'Jomfru Marias Uplettede Undfangelse',
	'juan-diego': 'Skt. Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Vor Frue af Loreto',
	'damasus-i': 'Skt. Damasus I, pave',
	'our-lady-of-guadalupe': 'Vor Frue af Guadalupe',
	lucy: 'Skt. Lucia, jomfru og marty',
	'john-of-the-cross': 'Skt. Johannes af Korset, præst og kirkelærer',
	'peter-canisius': 'Skt. Petrus Canisius, præst og kirkelærer',
	'john-of-kanty': 'Skt. Johannes af Kenty, præst',
	stephen: 'Skt. Stefan, den første martyr',
	'john-evangelist': 'Skt. Johannes, apostel og evangelist',
	'holy-innocents': 'De Uskyldige Børn, martyrer',
	'thomas-becket': 'Skt. Thomas Becket, biskop og martyr',
	'sylvester-i': 'Skt. Silvester I, pave'
};
