/**
 * The General Roman Calendar in German.
 *
 * Transcribed from the 4 calendars GCatholic publishes in German.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * All 218 of them, in the Calendar's own order.
 */
export const de: Record<string, string> = {
	'basil-gregory': 'Hl. Basilius der Große und hl. Gregor von Nazianz, Bischöfe, Kirchenlehrer',
	'holy-name-of-jesus': 'Heiligster Name Jesu',
	'raymond-of-penyafort': 'Hl. Raimund von Peñafort, Priester',
	hilary: 'Hl. Hilarius, Bischof, Kirchenlehrer',
	'anthony-abbot': 'Hl. Antonius, Mönchsvater in Ägypten',
	fabian: 'Hl. Fabian, Papst, Märtyrer',
	sebastian: 'Hl. Sebastian, Märtyrer',
	agnes: 'Hl. Agnes, Jungfrau, Märtyrin',
	'vincent-deacon': 'Hl. Vinzenz, Diakon, Märtyrer',
	'francis-de-sales': 'Hl. Franz von Sales, Bischof, Kirchenlehrer',
	'conversion-of-paul': 'Bekehrung des hl. Apostels Paulus',
	'timothy-titus': 'Hl. Timotheus und hl. Titus, Bischöfe',
	'angela-merici': 'Hl. Angela Merici, Jungfrau',
	'thomas-aquinas': 'Hl. Thomas von Aquin, Ordenspriester, Kirchenlehrer',
	'john-bosco': 'Hl. Johannes Bosco, Ordenspriester',
	'presentation-of-the-lord': 'Darstellung des Herrn',
	blaise: 'Hl. Blasius von Sebaste, Bischof, Märtyrer',
	ansgar: 'Hl. Ansgar, Bischof',
	agatha: 'Hl. Agatha, Jungfrau, Märtyrin',
	'paul-miki': 'Hl. Paul Miki und Gefährten, Märtyrer',
	'jerome-emiliani': 'Hl. Hieronymus Ämiliani',
	'josephine-bakhita': 'Hl. Josefine Bakhita, Ordensfrau',
	scholastica: 'Hl. Scholastika, Jungfrau',
	'our-lady-of-lourdes': 'Unsere Liebe Frau in Lourdes',
	'cyril-methodius': 'Hl. Cyrill, Mönch, und hl. Methodius, Bischof',
	'seven-founders': 'Die Sieben heiligen Gründer des Servitenordens',
	'peter-damian': 'Hl. Petrus Damiani, Bischof, Kirchenlehrer',
	'chair-of-peter': 'Kathedra Petri',
	polycarp: 'Hl. Polykarp, Bischof, Märtyrer',
	'gregory-of-narek': 'Hl. Gregor von Narek, Abt, Kirchenlehrer',
	casimir: 'Hl. Kasimir',
	'perpetua-felicity': 'Hl. Perpetua und hl. Felicitas, Märtyrinnen',
	'john-of-god': 'Hl. Johannes von Gott, Ordenspriester',
	'frances-of-rome': 'Hl. Franziska von Rom, Ordensfrau',
	patrick: 'Hl. Patrick, Bischof',
	'cyril-of-jerusalem': 'Hl. Cyrill von Jerusalem, Bischof, Kirchenlehrer',
	joseph: 'Hl. Josef, Bräutigam der Gottesmutter Maria',
	turibius: 'Hl. Turibio von Mongrovejo, Bischof',
	annunciation: 'Verkündigung des Herrn',
	'francis-of-paola': 'Hl. Franz von Paola, Einsiedler',
	isidore: 'Hl. Isidor, Bischof, Kirchenlehrer',
	'vincent-ferrer': 'Hl. Vinzenz Ferrer, Ordenspriester',
	'john-baptist-de-la-salle': 'Hl. Jean Baptiste de La Salle, Priester',
	stanislaus: 'Hl. Stanislaus, Bischof, Märtyrer',
	'martin-i': 'Hl. Martin I., Papst, Märtyrer',
	anselm: 'Hl. Anselm, Bischof, Kirchenlehrer',
	george: 'Hl. Georg, Märtyrer',
	adalbert: 'Hl. Adalbert, Bischof, Märtyrer',
	fidelis: 'Hl. Fidelis von Sigmaringen, Ordenspriester, Märtyrer',
	mark: 'Hl. Markus, Evangelist',
	'peter-chanel': 'Hl. Peter Chanel, Priester, Märtyrer',
	'louis-de-montfort': 'Hl. Ludwig Maria Grignion de Montfort, Priester',
	'catherine-of-siena': 'Hl. Katharina von Siena, Ordensfrau, Kirchenlehrerin',
	'pius-v': 'Hl. Pius V., Papst',
	'joseph-the-worker': 'Hl. Josef der Arbeiter',
	athanasius: 'Hl. Athanasius, Bischof, Kirchenlehrer',
	'philip-james': 'Hl. Philippus und hl. Jakobus, Apostel',
	'john-of-avila': 'Hl. Johannes von Ávila, Priester, Kirchenlehrer',
	'nereus-achilleus': 'Hl. Nereus und hl. Achilleus, Märtyrer',
	pancras: 'Hl. Pankratius, Märtyrer',
	'our-lady-of-fatima': 'Unsere Liebe Frau von Fátima',
	matthias: 'Hl. Matthias, Apostel',
	'john-i': 'Hl. Johannes I., Papst, Märtyrer',
	'bernardine-of-siena': 'Hl. Bernhardin von Siena, Ordenspriester',
	'christopher-magallanes': 'Hl. Christophorus Magallanes, Priester, und Gefährten, Märtyrer',
	'rita-of-cascia': 'Hl. Rita von Cascia, Ordensfrau',
	bede: 'Hl. Beda der Ehrwürdige, Ordenspriester, Kirchenlehrer',
	'gregory-vii': 'Hl. Gregor VII., Papst',
	'mary-magdalene-de-pazzi': 'Hl. Maria Magdalena von Pazzi, Ordensfrau',
	'philip-neri': 'Hl. Philipp Neri, Priester',
	'augustine-of-canterbury': 'Hl. Augustinus von Canterbury, Bischof',
	'paul-vi': 'Hl. Paul VI., Papst',
	visitation: 'Mariä Heimsuchung',
	justin: 'Hl. Justin, Märtyrer',
	'marcellinus-peter': 'Hl. Marcellinus und hl. Petrus, Märtyrer',
	'charles-lwanga': 'Hl. Karl Lwanga und Gefährten, Märtyrer',
	boniface: 'Hl. Bonifatius, Bischof, Märtyrer',
	norbert: 'Hl. Norbert von Xanten, Bischof',
	ephrem: 'Hl. Ephräm der Syrer, Diakon, Kirchenlehrer',
	barnabas: 'Hl. Barnabas, Apostel',
	'anthony-of-padua': 'Hl. Antonius von Padua, Ordenspriester, Kirchenlehrer',
	romuald: 'Hl. Romuald, Abt',
	'aloysius-gonzaga': 'Hl. Aloisius Gonzaga, Ordensmann',
	'paulinus-of-nola': 'Hl. Paulinus von Nola, Bischof',
	'fisher-more': 'Hl. John Fisher, Bischof, und hl. Thomas Morus, Märtyrer',
	'birth-of-john-the-baptist': 'Geburt des hl. Johannes des Täufers',
	'cyril-of-alexandria': 'Hl. Cyrill von Alexandrien, Bischof, Kirchenlehrer',
	irenaeus: 'Hl. Irenäus, Bischof, Märtyrer, Kirchenlehrer',
	'peter-and-paul': 'Hl. Petrus und hl. Paulus, Apostel',
	'first-martyrs-of-rome': 'Die ersten Heiligen Märtyrer der Stadt Rom',
	'thomas-apostle': 'Hl. Thomas, Apostel',
	'elizabeth-of-portugal': 'Hl. Elisabeth von Portugal',
	'anthony-zaccaria': 'Hl. Antonius Maria Zaccaria, Ordenspriester',
	'maria-goretti': 'Hl. Maria Goretti, Jungfrau, Märtyrin',
	'augustine-zhao-rong': 'Hl. Augustinus Zhao Rong, Priester, und Gefährten, Märtyrer',
	benedict: 'Hl. Benedikt, Mönchsvater',
	henry: 'Hl. Heinrich',
	camillus: 'Hl. Kamillus von Lellis, Priester',
	bonaventure: 'Hl. Bonaventura, Bischof, Kirchenlehrer',
	'our-lady-of-mount-carmel': 'Unsere Liebe Frau auf dem Berge Karmel',
	apollinaris: 'Hl. Apollinaris, Bischof, Märtyrer',
	'lawrence-of-brindisi': 'Hl. Laurentius von Brindisi, Ordenspriester, Kirchenlehrer',
	'mary-magdalene': 'Hl. Maria Magdalena',
	bridget: 'Hl. Birgitta von Schweden, Ordensfrau',
	sharbel: 'Hl. Scharbel Mahluf, Ordenspriester',
	james: 'Hl. Jakobus, Apostel',
	'joachim-anne': 'Hl. Joachim und hl. Anna, Eltern der Gottesmutter Maria',
	'martha-mary-lazarus': 'Hl. Marta, hl. Maria und hl. Lazarus',
	'peter-chrysologus': 'Hl. Petrus Chrysologus, Bischof, Kirchenlehrer',
	'ignatius-of-loyola': 'Hl. Ignatius von Loyola, Priester',
	'alphonsus-liguori': 'Hl. Alfons Maria von Liguori, Bischof, Kirchenlehrer',
	'eusebius-of-vercelli': 'Hl. Eusebius von Vercelli, Bischof',
	'peter-julian-eymard': 'Hl. Petrus Julianus Eymard, Priester',
	'john-vianney': 'Hl. Johannes Maria Vianney, Priester',
	'dedication-st-mary-major': 'Weihe der Basilika Santa Maria Maggiore in Rom',
	transfiguration: 'Verklärung des Herrn',
	'sixtus-ii': 'Hl. Xystus II., Papst, und Gefährten, Märtyrer',
	cajetan: 'Hl. Kajetan, Priester',
	dominic: 'Hl. Dominikus, Priester',
	'teresa-benedicta': 'Hl. Theresia Benedicta vom Kreuz, Ordensfrau, Märtyrin',
	lawrence: 'Hl. Laurentius, Diakon, Märtyrer',
	clare: 'Hl. Klara von Assisi, Jungfrau',
	'jane-frances-de-chantal': 'Hl. Johanna Franziska von Chantal, Ordensfrau',
	'pontian-hippolytus': 'Hl. Pontianus, Papst, und hl. Hippolyt, Priester, Märtyrer',
	'maximilian-kolbe': 'Hl. Maximilian Maria Kolbe, Ordenspriester, Märtyrer',
	assumption: 'Mariä Aufnahme in den Himmel',
	'stephen-of-hungary': 'Hl. Stephan von Ungarn',
	'john-eudes': 'Hl. Johannes Eudes, Priester',
	bernard: 'Hl. Bernhard, Abt, Kirchenlehrer',
	'pius-x': 'Hl. Pius X., Papst',
	'queenship-of-mary': 'Maria Königin',
	'rose-of-lima': 'Hl. Rosa von Lima, Jungfrau',
	bartholomew: 'Hl. Bartholomäus, Apostel',
	louis: 'Hl. Ludwig, König von Frankreich',
	'joseph-calasanz': 'Hl. Josef von Calasanz, Priester',
	monica: 'Hl. Monika',
	augustine: 'Hl. Augustinus, Bischof, Kirchenlehrer',
	'passion-of-john-the-baptist': 'Enthauptung des hl. Johannes des Täufers',
	'gregory-the-great': 'Hl. Gregor der Große, Papst, Kirchenlehrer',
	'teresa-of-calcutta': 'Hl. Teresa von Kolkata, Jungfrau',
	'nativity-of-mary': 'Mariä Geburt',
	'peter-claver': 'Hl. Petrus Claver, Priester',
	'holy-name-of-mary': 'Heiligster Name Mariens',
	'john-chrysostom': 'Hl. Johannes Chrysostomus, Bischof, Kirchenlehrer',
	'exaltation-of-the-cross': 'Kreuzerhöhung',
	'our-lady-of-sorrows': 'Gedächtnis der Schmerzen Mariens',
	'cornelius-cyprian': 'Hl. Kornelius, Papst, und hl. Cyprian, Bischof, Märtyrer',
	'robert-bellarmine': 'Hl. Robert Bellarmin, Bischof, Kirchenlehrer',
	hildegard: 'Hl. Hildegard von Bingen, Jungfrau, Kirchenlehrerin',
	januarius: 'Hl. Januarius, Bischof, Märtyrer',
	'andrew-kim':
		'Hl. Andreas Kim Tae-gŏn, Priester, und hl. Paul Chŏng Ha-sang und Gefährten, Märtyrer',
	matthew: 'Hl. Matthäus, Apostel und Evangelist',
	'padre-pio': 'Hl. Pius von Pietrelcina, Ordenspriester',
	'cosmas-damian': 'Hl. Kosmas und hl. Damian, Märtyrer',
	'vincent-de-paul': 'Hl. Vinzenz von Paul, Ordenspriester',
	wenceslaus: 'Hl. Wenzel, Märtyrer',
	'lawrence-ruiz': 'Hl. Lorenzo Ruiz und Gefährten, Märtyrer',
	archangels: 'Hl. Michael, Hl. Gabriel und Hl. Rafael, Erzengel',
	jerome: 'Hl. Hieronymus, Priester, Kirchenlehrer',
	'therese-of-lisieux': 'Hl. Theresia vom Kinde Jesus, Ordensfrau, Kirchenlehrerin',
	'guardian-angels': 'Heilige Schutzengel',
	'francis-of-assisi': 'Hl. Franz von Assisi, Ordensmann',
	faustina: 'Hl. Faustyna Kowalska, Jungfrau',
	bruno: 'Hl. Bruno, Ordenspriester',
	'our-lady-of-the-rosary': 'Unsere Liebe Frau vom Rosenkranz',
	denis: 'Hl. Dionysius, Bischof, und Gefährten, Märtyrer',
	'john-leonardi': 'Hl. Johannes Leonardi, Priester',
	'john-henry-newman': 'Hl. John Henry Newman, Ordenspriester, Kirchenlehrer',
	'john-xxiii': 'Hl. Johannes XXIII., Papst',
	'callistus-i': 'Hl. Kallistus I., Papst, Märtyrer',
	'teresa-of-avila': 'Hl. Theresa von Jesus, Ordensfrau, Kirchenlehrerin',
	hedwig: 'Hl. Hedwig von Andechs, Ordensfrau',
	'margaret-mary-alacoque': 'Hl. Margareta Maria Alacoque, Ordensfrau',
	'ignatius-of-antioch': 'Hl. Ignatius von Antiochien, Bischof, Märtyrer',
	luke: 'Hl. Lukas, Evangelist',
	'north-american-martyrs':
		'Hl. Johannes de Brébeuf, hl. Isaak Jogues, Priester, und Gefährten, Märtyrer',
	'paul-of-the-cross': 'Hl. Paul vom Kreuz, Priester',
	'john-paul-ii': 'Hl. Johannes Paul II., Papst',
	'john-of-capistrano': 'Hl. Johannes von Capestrano, Ordenspriester',
	'anthony-mary-claret': 'Hl. Antonius Maria Claret, Bischof',
	'simon-jude': 'Hl. Simon und hl. Judas, Apostel',
	'all-saints': 'Allerheiligen',
	'martin-de-porres': 'Hl. Martin von Porres, Ordensmann',
	'charles-borromeo': 'Hl. Karl Borromäus, Bischof',
	'dedication-of-the-lateran': 'Weihe der Lateranbasilika',
	'leo-the-great': 'Hl. Leo der Große, Papst, Kirchenlehrer',
	'martin-of-tours': 'Hl. Martin von Tours, Bischof',
	josaphat: 'Hl. Josaphat, Bischof, Märtyrer',
	'albert-the-great': 'Hl. Albert der Große, Kirchenlehrer, Bischof',
	'margaret-of-scotland': 'Hl. Margareta von Schottland',
	gertrude: 'Hl. Gertrud, Ordensfrau',
	'elizabeth-of-hungary': 'Hl. Elisabeth von Thüringen, Ordensfrau',
	'dedication-of-peter-and-paul': 'Weihe der Basiliken Sankt Peter und Sankt Paul zu Rom',
	'presentation-of-mary': 'Gedenktag Unserer Lieben Frau in Jerusalem',
	cecilia: 'Hl. Cäcilia, Jungfrau, Märtyrin',
	'clement-i': 'Hl. Klemens I., Papst, Märtyrer',
	columban: 'Hl. Kolumban, Abt',
	'andrew-dung-lac': 'Hl. Andreas Dung-Lac, Priester, und Gefährten, Märtyrer',
	'catherine-of-alexandria': 'Hl. Katharina von Alexandrien, Märtyrin',
	andrew: 'Hl. Andreas, Apostel',
	'francis-xavier': 'Hl. Franz Xaver, Ordenspriester',
	'john-damascene': 'Hl. Johannes von Damaskus, Priester, Kirchenlehrer',
	nicholas: 'Hl. Nikolaus, Bischof',
	ambrose: 'Hl. Ambrosius, Bischof, Kirchenlehrer',
	'immaculate-conception': 'Ohne Erbsünde empfangene Jungfrau und Gottesmutter Maria',
	'juan-diego': 'Hl. Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Unsere Liebe Frau von Loreto',
	'damasus-i': 'Hl. Damasus I., Papst',
	'our-lady-of-guadalupe': 'Unsere Liebe Frau in Guadalupe',
	lucy: 'Hl. Luzia, Jungfrau, Märtyrin',
	'john-of-the-cross': 'Hl. Johannes vom Kreuz, Ordenspriester, Kirchenlehrer',
	'peter-canisius': 'Hl. Petrus Kanisius, Ordenspriester, Kirchenlehrer',
	'john-of-kanty': 'Hl. Johannes von Krakau, Priester',
	stephen: 'Hl. Stephanus, erster Märtyrer',
	'john-evangelist': 'Hl. Johannes, Apostel und Evangelist',
	'holy-innocents': 'Unschuldige Kinder',
	'thomas-becket': 'Hl. Thomas Becket, Bischof, Märtyrer',
	'sylvester-i': 'Hl. Silvester I., Papst'
};
