/**
 * The General Roman Calendar in Spanish.
 *
 * Transcribed from the 15 calendars GCatholic publishes in Spanish.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * All 218 of them, in the Calendar's own order.
 *
 * The fifteen Spanish calendars agree on 199 of the 218 and split on
 * nineteen, Spain and Urgell against the thirteen American ones — `Santos
 * Arcángeles Miguel, Gabriel y Rafael` against `Santos Miguel, Gabriel y
 * Rafael, arcángeles`, `El Dulce Nombre de María` against `El Santísimo
 * Nombre de María`. What is here is the American form, on the count alone:
 * there is no sense in which one of the two is the Spanish one.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `esTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const es: Record<string, string> = {
	'basil-gregory': 'Santos Basilio Magno y Gregorio de Nacianzo, obispos y doctores de la Iglesia',
	'holy-name-of-jesus': 'El Santísimo Nombre de Jesús',
	'raymond-of-penyafort': 'San Raimundo de Peñafort, presbítero',
	hilary: 'San Hilario, obispo y doctor de la Iglesia',
	'anthony-abbot': 'San Antonio, abad',
	fabian: 'San Fabián, papa y mártir',
	sebastian: 'San Sebastián, mártir',
	agnes: 'Santa Inés, virgen y mártir',
	'vincent-deacon': 'San Vicente, diácono y mártir',
	'francis-de-sales': 'San Francisco de Sales, obispo y doctor de la Iglesia',
	'conversion-of-paul': 'La Conversión de San Pablo, apóstol',
	'timothy-titus': 'Santos Timoteo y Tito, obispos',
	'angela-merici': 'Santa Ángela Merici, virgen',
	'thomas-aquinas': 'Santo Tomás de Aquino, presbítero y doctor de la Iglesia',
	'john-bosco': 'San Juan Bosco, presbítero',
	'presentation-of-the-lord': 'La Presentación del Señor',
	blaise: 'San Blas, obispo y mártir',
	ansgar: 'San Óscar, obispo',
	agatha: 'Santa Águeda, virgen y mártir',
	'paul-miki': 'Santos Pablo Miki y compañeros, mártires',
	'jerome-emiliani': 'San Jerónimo Emiliano',
	'josephine-bakhita': 'Santa Josefina Bakhita, virgen',
	scholastica: 'Santa Escolástica, virgen',
	'our-lady-of-lourdes': 'Nuestra Señora de Lourdes',
	'cyril-methodius': 'Santos Cirilo, monje, y Metodio, obispo',
	'seven-founders': 'Los Santos Siete Fundadores de la Orden de los Servitas',
	'peter-damian': 'San Pedro Damián, obispo y doctor de la Iglesia',
	'chair-of-peter': 'La Cátedra de San Pedro, apóstol',
	polycarp: 'San Policarpo, obispo y mártir',
	'gregory-of-narek': 'San Gregorio de Narek, abad y doctor de la Iglesia',
	casimir: 'San Casimiro',
	'perpetua-felicity': 'Santas Perpetua y Felicidad, mártires',
	'john-of-god': 'San Juan de Dios, religioso',
	'frances-of-rome': 'Santa Francisca Romana, religiosa',
	patrick: 'San Patricio, obispo',
	'cyril-of-jerusalem': 'San Cirilo de Jerusalén, obispo y doctor de la Iglesia',
	joseph: 'San José, esposo de la Bienaventurada Virgen María',
	turibius: 'Santo Toribio de Mogrovejo, obispo',
	annunciation: 'La Anunciación del Señor',
	'francis-of-paola': 'San Francisco de Paula, ermitaño',
	isidore: 'San Isidoro, obispo y doctor de la Iglesia',
	'vincent-ferrer': 'San Vicente Ferrer, presbítero',
	'john-baptist-de-la-salle': 'San Juan Bautista de La Salle, presbítero',
	stanislaus: 'San Estanislao, obispo y mártir',
	'martin-i': 'San Martín I, papa y mártir',
	anselm: 'San Anselmo, obispo y doctor de la Iglesia',
	george: 'San Jorge, mártir',
	adalbert: 'San Adalberto, obispo y mártir',
	fidelis: 'San Fidel de Sigmaringa, presbítero y mártir',
	mark: 'San Marcos, evangelista',
	'peter-chanel': 'San Pedro Chanel, presbítero y mártir',
	'louis-de-montfort': 'San Luis María Grignion de Montfort, presbítero',
	'catherine-of-siena': 'Santa Catalina de Siena, virgen y doctora de la Iglesia',
	'pius-v': 'San Pío V, papa',
	'joseph-the-worker': 'San José Obrero',
	athanasius: 'San Atanasio, obispo y doctor de la Iglesia',
	'philip-james': 'Santos Felipe y Santiago, apóstoles',
	'john-of-avila': 'San Juan de Ávila, presbítero y doctor de la Iglesia',
	'nereus-achilleus': 'Santos Nereo y Aquileo, mártires',
	pancras: 'San Pancracio, mártir',
	'our-lady-of-fatima': 'Nuestra Señora de Fátima',
	matthias: 'San Matías, apóstol',
	'john-i': 'San Juan I, papa y mártir',
	'bernardine-of-siena': 'San Bernardino de Siena, presbítero',
	'christopher-magallanes': 'Santos Cristóbal Magallanes, presbítero, y compañeros, mártires',
	'rita-of-cascia': 'Santa Rita de Casia, religiosa',
	bede: 'San Beda el Venerable, presbítero y doctor de la Iglesia',
	'gregory-vii': 'San Gregorio VII, papa',
	'mary-magdalene-de-pazzi': 'Santa María Magdalena de Pazzi, virgen',
	'philip-neri': 'San Felipe Neri, presbítero',
	'augustine-of-canterbury': 'San Agustín de Canterbury, obispo',
	'paul-vi': 'San Paolo VI, papa',
	visitation: 'La Visitación de la Bienaventurada Virgen María',
	justin: 'San Justino, mártir',
	'marcellinus-peter': 'Santos Marcelino y Pedro, mártires',
	'charles-lwanga': 'Santos Carlos Luanga y compañeros, mártires',
	boniface: 'San Bonifacio, obispo y mártir',
	norbert: 'San Norberto, obispo',
	ephrem: 'San Efrén, diácono y doctor de la Iglesia',
	barnabas: 'San Bernabé, apóstol',
	'anthony-of-padua': 'San Antonio de Padua, presbítero y doctor de la Iglesia',
	romuald: 'San Romualdo, abad',
	'aloysius-gonzaga': 'San Luis Gonzaga, religioso',
	'paulinus-of-nola': 'San Paulino de Nola, obispo',
	'fisher-more': 'Santos Juan Fisher, obispo, y Tomás Moro, mártires',
	'birth-of-john-the-baptist': 'El Nacimiento de San Juan Bautista',
	'cyril-of-alexandria': 'San Cirilo de Alejandría, obispo y doctor de la Iglesia',
	irenaeus: 'San Ireneo, obispo, mártir y doctor de la Iglesia',
	'peter-and-paul': 'Santos Pedro y Pablo, apóstoles',
	'first-martyrs-of-rome': 'Los Santos Primeros mártires de la Iglesia de Roma',
	'thomas-apostle': 'Santo Tomás, apóstol',
	'elizabeth-of-portugal': 'Santa Isabel de Portugal',
	'anthony-zaccaria': 'San Antonio María Zaccaria, presbítero',
	'maria-goretti': 'Santa María Goretti, virgen y mártir',
	'augustine-zhao-rong': 'Santos Agustín Zhao Rong, presbítero, y compañeros, mártires',
	benedict: 'San Benito, abad',
	henry: 'San Enrique',
	camillus: 'San Camilo de Lellis, presbítero',
	bonaventure: 'San Buenaventura, obispo y doctor de la Iglesia',
	'our-lady-of-mount-carmel': 'Nuestra Señora del Carmen',
	apollinaris: 'San Apolinar, obispo y mártir',
	'lawrence-of-brindisi': 'San Lorenzo de Brindis, presbítero y doctor de la Iglesia',
	'mary-magdalene': 'Santa María Magdalena',
	bridget: 'Santa Brígida de Suecia, religiosa',
	sharbel: 'San Chárbel Makhlouf, presbítero',
	james: 'Santiago, apóstol',
	'joachim-anne': 'Santos Joaquín y Ana, padres de la bienaventurada Virgen María',
	'martha-mary-lazarus': 'Santos Marta, María y Lázaro',
	'peter-chrysologus': 'San Pedro Crisólogo, obispo y doctor de la Iglesia',
	'ignatius-of-loyola': 'San Ignacio de Loyola, presbítero',
	'alphonsus-liguori': 'San Alfonso María de Ligorio, obispo y doctor de la Iglesia',
	'eusebius-of-vercelli': 'San Eusebio de Vercelli, obispo',
	'peter-julian-eymard': 'San Pedro Julián Eymard, presbítero',
	'john-vianney': 'San Juan María Vianney, presbítero',
	'dedication-st-mary-major': 'La Dedicación de la Basílica de Santa María',
	transfiguration: 'La Transfiguración del Señor',
	'sixtus-ii': 'Santos Sixto II, papa, y compañeros, mártires',
	cajetan: 'San Cayetano, presbítero',
	dominic: 'Santo Domingo, presbítero',
	'teresa-benedicta': 'Santa Teresa Benedicta de la Cruz, virgen y mártir',
	lawrence: 'San Lorenzo, diácono y mártir',
	clare: 'Santa Clara, virgen',
	'jane-frances-de-chantal': 'Santa Juana Francisca de Chantal, religiosa',
	'pontian-hippolytus': 'Santos Ponciano, papa, e Hipólito, presbítero, mártires',
	'maximilian-kolbe': 'San Maximiliano María Kolbe, presbítero y mártir',
	assumption: 'La Asunción de la Santísima Virgen María',
	'stephen-of-hungary': 'San Esteban de Hungría',
	'john-eudes': 'San Juan Eudes, presbítero',
	bernard: 'San Bernardo, abad y doctor de la Iglesia',
	'pius-x': 'San Pío X, papa',
	'queenship-of-mary': 'La Santísima Virgen María, Reina',
	'rose-of-lima': 'Santa Rosa de Lima, virgen',
	bartholomew: 'San Bartolomé, apóstol',
	louis: 'San Luis de Francia',
	'joseph-calasanz': 'San José de Calasanz, presbítero',
	monica: 'Santa Mónica',
	augustine: 'San Agustín, obispo y doctor de la Iglesia',
	'passion-of-john-the-baptist': 'El Martirio de San Juan Bautista',
	'gregory-the-great': 'San Gregorio Magno, papa y doctor de la Iglesia',
	'teresa-of-calcutta': 'Santa Teresa de Calcuta, virgen',
	'nativity-of-mary': 'La Natividad de la Bienaventurada Virgen María',
	'peter-claver': 'San Pedro Claver, presbítero',
	'holy-name-of-mary': 'El Santísimo Nombre de María',
	'john-chrysostom': 'San Juan Crisóstomo, obispo y doctor de la Iglesia',
	'exaltation-of-the-cross': 'La Exaltación de la Santa Cruz',
	'our-lady-of-sorrows': 'Nuestra Señora de los Dolores',
	'cornelius-cyprian': 'Santos Cornelio, papa, y Cipriano, obispo, mártires',
	'robert-bellarmine': 'San Roberto Belarmino, obispo y doctor de la Iglesia',
	hildegard: 'Santa Hildegarda de Bingen, virgen y doctora de la Iglesia',
	januarius: 'San Jenaro, obispo y mártir',
	'andrew-kim': 'Santos Andrés Kim Taegon, presbítero, Pablo Chong Hasang, y compañeros, mártires',
	matthew: 'San Mateo, apóstol y evangelista',
	'padre-pio': 'San Pío de Pietrelcina, presbítero',
	'cosmas-damian': 'Santos Cosme y Damián, mártires',
	'vincent-de-paul': 'San Vicente de Paúl, presbítero',
	wenceslaus: 'San Wenceslao, mártir',
	'lawrence-ruiz': 'Santos Lorenzo Ruiz y compañeros, mártires',
	archangels: 'Santos Miguel, Gabriel y Rafael, arcángeles',
	jerome: 'San Jerónimo, presbítero y doctor de la Iglesia',
	'therese-of-lisieux': 'Santa Teresa del Niño Jesús, virgen y doctora de la Iglesia',
	'guardian-angels': 'Los Santos Ángeles Custodios',
	'francis-of-assisi': 'San Francisco de Asís, religioso',
	faustina: 'Santa Faustina Kowalska, virgen',
	bruno: 'San Bruno, presbítero',
	'our-lady-of-the-rosary': 'Nuestra Señora del Rosario',
	denis: 'Santos Dionisio, obispo, y compañeros, mártires',
	'john-leonardi': 'San Juan Leonardi, presbítero',
	'john-henry-newman': 'San Juan Enrique Newman, presbítero y doctor de la Iglesia',
	'john-xxiii': 'San Juan XXIII, papa',
	'callistus-i': 'San Calixto I, papa y mártir',
	'teresa-of-avila': 'Santa Teresa de Jesús, virgen y doctora de la Iglesia',
	hedwig: 'Santa Eduviges, religiosa',
	'margaret-mary-alacoque': 'Santa Margarita María de Alacoque, virgen',
	'ignatius-of-antioch': 'San Ignacio de Antioquía, obispo y mártir',
	luke: 'San Lucas, evangelista',
	'north-american-martyrs':
		'Santos Juan de Brébeuf e Isaac Jogues, presbíteros, y compañeros, mártires',
	'paul-of-the-cross': 'San Pablo de la Cruz, presbítero',
	'john-paul-ii': 'San Juan Pablo II, papa',
	'john-of-capistrano': 'San Juan de Capistrano, presbítero',
	'anthony-mary-claret': 'San Antonio María Claret, obispo',
	'simon-jude': 'Santos Simón y Judas, apóstoles',
	'all-saints': 'Todos los Santos',
	'martin-de-porres': 'San Martín de Porres, religioso',
	'charles-borromeo': 'San Carlos Borromeo, obispo',
	'dedication-of-the-lateran': 'La Dedicación de la Basílica de Letrán',
	'leo-the-great': 'San León el Magno, papa y doctor de la Iglesia',
	'martin-of-tours': 'San Martín de Tours, obispo',
	josaphat: 'San Josafat, obispo y mártir',
	'albert-the-great': 'San Alberto Magno, obispo y doctor de la Iglesia',
	'margaret-of-scotland': 'Santa Margarita de Escocia',
	gertrude: 'Santa Gertrudis, virgen',
	'elizabeth-of-hungary': 'Santa Isabel de Hungría, religiosa',
	'dedication-of-peter-and-paul':
		'La Dedicación de las Basílicas de los Santos Pedro y Pablo, apóstoles',
	'presentation-of-mary': 'La Presentación de la Santísima Virgen María',
	cecilia: 'Santa Cecilia, virgen y mártir',
	'clement-i': 'San Clemente I, papa y mártir',
	columban: 'San Columbano, abad',
	'andrew-dung-lac': 'Santos Andrés Dung-Lac, presbítero, y compañeros, mártires',
	'catherine-of-alexandria': 'Santa Catalina de Alejandría, virgen y mártir',
	andrew: 'San Andrés, apóstol',
	'francis-xavier': 'San Francisco Javier, presbítero',
	'john-damascene': 'San Juan Damasceno, presbítero y doctor de la Iglesia',
	nicholas: 'San Nicolás, obispo',
	ambrose: 'San Ambrosio, obispo y doctor de la Iglesia',
	'immaculate-conception': 'La Inmaculada Concepción de la Bienaventurada Virgen María',
	'juan-diego': 'San Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Nuestra Señora de Loreto',
	'damasus-i': 'San Dámaso I, papa',
	'our-lady-of-guadalupe': 'Nuestra Señora de Guadalupe',
	lucy: 'Santa Lucía, virgen y mártir',
	'john-of-the-cross': 'San Juan de la Cruz, presbítero y doctor de la Iglesia',
	'peter-canisius': 'San Pedro Canisio, presbítero y doctor de la Iglesia',
	'john-of-kanty': 'San Juan Cancio, presbítero',
	stephen: 'San Esteban, protomártir',
	'john-evangelist': 'San Juan, apóstol y evangelista',
	'holy-innocents': 'Los Santos Inocentes, mártires',
	'thomas-becket': 'San Tomás Becket, obispo y mártir',
	'sylvester-i': 'San Silvestre I, papa',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'La Natividad del Señor',
	'holy-family': 'La Sagrada Familia de Jesús, María y José',
	'mary-mother-of-god': 'Santa María, Madre de Dios',
	'christmas-2-sunday': 'II Domingo de Natividad',
	epiphany: 'La Epifanía del Señor',
	'baptism-of-the-lord': 'El Bautismo del Señor',
	'ash-wednesday': 'Miércoles de Ceniza',
	'palm-sunday': 'Domingo de Ramos en la Pasión del Señor',
	'holy-thursday': 'Jueves Santo en la Cena del Señor',
	'good-friday': 'Viernes Santo en la Pasión del Señor',
	'holy-saturday': 'Sábado Santo de la Sepultura del Señor',
	'easter-sunday': 'Domingo de Pascua de la Resurrección del Señor',
	'easter-2-sunday': 'II Domingo de Pascua o de la Divina Misericordia',
	ascension: 'La Ascensión del Señor',
	pentecost: 'Domingo de Pentecostés',
	trinity: 'La Santísima Trinidad',
	'corpus-christi': 'El Cuerpo y la Sangre Santísimos de Cristo',
	'sacred-heart': 'El Sagrado Corazón de Jesús',
	'immaculate-heart': 'El Inmaculado Corazón de María',
	'mary-mother-of-the-church': 'Bienaventurada Virgen María, Madre de la Iglesia',
	'christ-the-king': 'Nuestro Señor Jesucristo, Rey del Universo'
};

/**
 * The Proper of Time in Spanish, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const esTemporal: TemporalNames = {
	days: { 1: 'Lunes', 2: 'Martes', 3: 'Miércoles', 4: 'Jueves', 5: 'Viernes', 6: 'Sábado' },
	weeks: {
		1: 'I',
		2: 'II',
		3: 'III',
		4: 'IV',
		5: 'V',
		6: 'VI',
		7: 'VII',
		8: 'VIII',
		9: 'IX',
		10: 'X',
		11: 'XI',
		12: 'XII',
		13: 'XIII',
		14: 'XIV',
		15: 'XV',
		16: 'XVI',
		17: 'XVII',
		18: 'XVIII',
		19: 'XIX',
		20: 'XX',
		21: 'XXI',
		22: 'XXII',
		23: 'XXIII',
		24: 'XXIV',
		25: 'XXV',
		26: 'XXVI',
		27: 'XXVII',
		28: 'XXVIII',
		29: 'XXIX',
		30: 'XXX',
		31: 'XXXI',
		32: 'XXXII',
		33: 'XXXIII',
		34: 'XXXIV'
	},
	octave: { 5: 'V', 6: 'VI', 7: 'VII' },
	sunday: {
		advent: '{week} Domingo de Adviento',
		lent: '{week} Domingo de Cuaresma',
		easter: '{week} Domingo de Pascua',
		ordinary: '{week} Domingo del Tiempo Ordinario'
	},
	weekday: {
		advent: '{day} de la {week} Semana de Adviento',
		lent: '{day} de la {week} Semana de Cuaresma',
		easter: '{day} de la {week} Semana de Pascua',
		ordinary: '{day} de la {week} Semana del Tiempo Ordinario'
	},
	holyWeek: '{day} Santo',
	afterAshes: '{day} después de Ceniza',
	afterEpiphany: '{day} después de la Epifanía',
	christmasWeekday: '{day} de la II Semana de Navidad',
	easterOctave: '{day} de la Octava de Pascua',
	christmasOctave: 'Día {nth} dentro de la Octava de la Natividad del Señor'
};
