/**
 * The General Roman Calendar in French.
 *
 * Transcribed from the 9 calendars GCatholic publishes in French.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * All 218 of them, in the Calendar's own order.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `frTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const fr: Record<string, string> = {
	'basil-gregory':
		'Saint Basile le Grand et Saint Grégoire de Nazianze, évêques et docteurs de L’Église',
	'holy-name-of-jesus': 'Le Saint Nom de Jésus',
	'raymond-of-penyafort': 'Saint Raymond de Penyafort, prêtre',
	hilary: 'Saint Hilaire, évêque et docteur de l’Église',
	'anthony-abbot': 'Saint Antoine, abbé',
	fabian: 'Saint Fabien, pape et martyr',
	sebastian: 'Saint Sébastien, martyr',
	agnes: 'Sainte Agnès, vierge et martyre',
	'vincent-deacon': 'Saint Vincent, diacre et martyr',
	'francis-de-sales': 'Saint François de Sales, évêque et docteur de l’Église',
	'conversion-of-paul': 'La Conversion de Saint Paul, apôtre',
	'timothy-titus': 'Saint Timothée et Saint Tite, évêques',
	'angela-merici': 'Sainte Angèle Merici, vierge',
	'thomas-aquinas': 'Saint Thomas d’Aquin, prêtre et docteur de l’Église',
	'john-bosco': 'Saint Jean Bosco, prêtre',
	'presentation-of-the-lord': 'La Présentation du Seigneur au Temple',
	blaise: 'Saint Blaise, évêque et martyr',
	ansgar: 'Saint Anschaire, évêque',
	agatha: 'Sainte Agathe, vierge et martyre',
	'paul-miki': 'Saint Paul Miki et ses compagnons, martyrs',
	'jerome-emiliani': 'Saint Jérôme Émilien',
	'josephine-bakhita': 'Sainte Joséphine Bakhita, vierge',
	scholastica: 'Sainte Scholastique, vierge',
	'our-lady-of-lourdes': 'Notre-Dame de Lourdes',
	'cyril-methodius': 'Saint Cyrille, moine, et Saint Méthode, évêque',
	'seven-founders': 'Les sept saints fondateurs des Servites de Marie',
	'peter-damian': 'Saint Pierre Damien, évêque et docteur de l’Église',
	'chair-of-peter': 'La Chaire de Saint Pierre, apôtre',
	polycarp: 'Saint Polycarpe, évêque et martyr',
	'gregory-of-narek': 'Saint Grégoire de Narek, abbé et docteur de l’Église',
	casimir: 'Saint Casimir',
	'perpetua-felicity': 'Sainte Perpétue et Sainte Félicité, martyres',
	'john-of-god': 'Saint Jean de Dieu, religieux',
	'frances-of-rome': 'Sainte Françoise Romaine, religieuse',
	patrick: 'Saint Patrice, évêque',
	'cyril-of-jerusalem': 'Saint Cyrille de Jérusalem, évêque et docteur de l’Église',
	joseph: 'Saint Joseph, époux de la Vierge Marie',
	turibius: 'Saint Turibio de Mogrovejo, évêque',
	annunciation: 'L’Annonciation du Seigneur',
	'francis-of-paola': 'Saint François de Paule, ermite',
	isidore: 'Saint Isidore, évêque et docteur de l’Église',
	'vincent-ferrer': 'Saint Vincent Ferrier, prêtre',
	'john-baptist-de-la-salle': 'Saint Jean-Baptiste de la Salle, prêtre',
	stanislaus: 'Saint Stanislas, évêque et martyr',
	'martin-i': 'Saint Martin Iᵉʳ, pape et martyr',
	anselm: 'Saint Anselme, évêque et docteur de l’Église',
	george: 'Saint Georges, martyr',
	adalbert: 'Saint Adalbert, évêque et martyr',
	fidelis: 'Saint Fidèle de Sigmaringen, prêtre et martyr',
	mark: 'Saint Marc, évangéliste',
	'peter-chanel': 'Saint Pierre Chanel, prêtre et martyr',
	'louis-de-montfort': 'Saint Louis-Marie Grignion de Montfort, prêtre',
	'catherine-of-siena': 'Sainte Catherine de Sienne, vierge et docteur de l’Église',
	'pius-v': 'Saint Pie V, pape',
	'joseph-the-worker': 'Saint Joseph travailleur',
	athanasius: 'Saint Athanase, évêque et docteur de l’Église',
	'philip-james': 'Saint Philippe et Saint Jacques, apôtres',
	'john-of-avila': 'Saint Jean d’Avila, prêtre et docteur de l’Église',
	'nereus-achilleus': 'Saint Nérée et Saint Achille, martyrs',
	pancras: 'Saint Pancrace, martyr',
	'our-lady-of-fatima': 'Notre-Dame de Fatima',
	matthias: 'Saint Matthias, apôtre',
	'john-i': 'Saint Jean Iᵉʳ, pape et martyr',
	'bernardine-of-siena': 'Saint Bernardin de Sienne, prêtre',
	'christopher-magallanes': 'Saint Christophe Magallanès, prêtre, et ses compagnons, martyrs',
	'rita-of-cascia': 'Sainte Rita de Cascia, religieuse',
	bede: 'Saint Bède le Vénérable, prêtre et docteur de l’Église',
	'gregory-vii': 'Saint Grégoire VII, pape',
	'mary-magdalene-de-pazzi': 'Sainte Marie-Madeleine de Pazzi, vierge',
	'philip-neri': 'Saint Philippe Neri, prêtre',
	'augustine-of-canterbury': 'Saint Augustin de Cantorbéry, évêque',
	'paul-vi': 'Saint Paul VI, pape',
	visitation: 'La Visitation de la Vierge Marie',
	justin: 'Saint Justin, martyr',
	'marcellinus-peter': 'Saint Marcellin et Saint Pierre, martyrs',
	'charles-lwanga': 'Saint Charles Lwanga et ses compagnons, martyrs',
	boniface: 'Saint Boniface, évêque et martyr',
	norbert: 'Saint Norbert, évêque',
	ephrem: 'Saint Éphrem, diacre et docteur de l’Église',
	barnabas: 'Saint Barnabé, apôtre',
	'anthony-of-padua': 'Saint Antoine de Padoue, prêtre et docteur de l’Église',
	romuald: 'Saint Romuald, abbé',
	'aloysius-gonzaga': 'Saint Louis de Gonzague, religieux',
	'paulinus-of-nola': 'Saint Paulin de Nole, évêque',
	'fisher-more': 'Saint Jean Fisher, évêque, et Saint Thomas More, martyrs',
	'birth-of-john-the-baptist': 'La Nativité de Saint Jean Baptiste',
	'cyril-of-alexandria': 'Saint Cyrille d’Alexandrie, évêque et docteur de l’Église',
	irenaeus: 'Saint Irénée, évêque, martyr et docteur de l’Église',
	'peter-and-paul': 'Saint Pierre et Saint Paul, apôtres',
	'first-martyrs-of-rome': 'Les premiers martyrs de l’Église de Rome',
	'thomas-apostle': 'Saint Thomas, apôtre',
	'elizabeth-of-portugal': 'Sainte Élisabeth de Portugal',
	'anthony-zaccaria': 'Saint Antoine-Marie Zaccaria, prêtre',
	'maria-goretti': 'Sainte Maria Goretti, vierge et martyre',
	'augustine-zhao-rong': 'Saint Augustin Zhao Rong, prêtre, et ses compagnons, martyrs',
	benedict: 'Saint Benoît, abbé',
	henry: 'Saint Henri',
	camillus: 'Saint Camille de Lellis, prêtre',
	bonaventure: 'Saint Bonaventure, évêque et docteur de l’Église',
	'our-lady-of-mount-carmel': 'Notre-Dame du Mont-Carmel',
	apollinaris: 'Saint Apollinaire, évêque et martyr',
	'lawrence-of-brindisi': 'Saint Laurent de Brindisi, prêtre et docteur de l’Église',
	'mary-magdalene': 'Sainte Marie Madeleine',
	bridget: 'Sainte Brigitte de Suède, religieuse',
	sharbel: 'Saint Charbel Maklouf, prêtre',
	james: 'Saint Jacques, apôtre',
	'joachim-anne': 'Saint Joachim et Sainte Anne, parents de la Vierge Marie',
	'martha-mary-lazarus': 'Sainte Marthe, Sainte Marie et Saint Lazare',
	'peter-chrysologus': 'Saint Pierre Chrysologue, évêque et docteur de l’Église',
	'ignatius-of-loyola': 'Saint Ignace de Loyola, prêtre',
	'alphonsus-liguori': 'Saint Alphonse-Marie de Liguori, évêque et docteur de l’Église',
	'eusebius-of-vercelli': 'Saint Eusèbe de Verceil, évêque',
	'peter-julian-eymard': 'Saint Pierre-Julien Eymard, prêtre',
	'john-vianney': 'Saint Jean-Marie Vianney, prêtre',
	'dedication-st-mary-major': 'La Dédicace de la Basilique Sainte-Marie Majeure',
	transfiguration: 'La Transfiguration du Seigneur',
	'sixtus-ii': 'Saint Sixte II, pape, et ses compagnons, martyrs',
	cajetan: 'Saint Gaétan, prêtre',
	dominic: 'Saint Dominique, prêtre',
	'teresa-benedicta': 'Sainte Thérèse-Bénédicte de la Croix, vierge et martyre',
	lawrence: 'Saint Laurent, diacre et martyr',
	clare: 'Sainte Claire, vierge',
	'jane-frances-de-chantal': 'Sainte Jeanne-Françoise de Chantal, religieuse',
	'pontian-hippolytus': 'Saint Pontien, pape, et Saint Hippolyte, prêtre, martyrs',
	'maximilian-kolbe': 'Saint Maximilien Kolbe, prêtre et martyr',
	assumption: 'L’Assomption de la Vierge Marie',
	'stephen-of-hungary': 'Saint Étienne de Hongrie',
	'john-eudes': 'Saint Jean Eudes, prêtre',
	bernard: 'Saint Bernard, abbé et docteur de l’Église',
	'pius-x': 'Saint Pie X, pape',
	'queenship-of-mary': 'La Vierge Marie Reine',
	'rose-of-lima': 'Sainte Rose de Lima, vierge',
	bartholomew: 'Saint Barthélemy, apôtre',
	louis: 'Saint Louis, roi de France',
	'joseph-calasanz': 'Saint Joseph de Calasanz, prêtre',
	monica: 'Sainte Monique',
	augustine: 'Saint Augustin, évêque et docteur de l’Église',
	'passion-of-john-the-baptist': 'Le Martyre de Saint Jean Baptiste',
	'gregory-the-great': 'Saint Grégoire le Grand, pape, docteur de l’Église',
	'teresa-of-calcutta': 'Sainte Teresa de Calcutta, vierge',
	'nativity-of-mary': 'La Nativité de la Vierge Marie',
	'peter-claver': 'Saint Pierre Claver, prêtre',
	'holy-name-of-mary': 'Le Saint Nom de Marie',
	'john-chrysostom': 'Saint Jean Chrysostome, évêque et docteur de l’Église',
	'exaltation-of-the-cross': 'La Croix Glorieuse',
	'our-lady-of-sorrows': 'Notre-Dame des Douleurs',
	'cornelius-cyprian': 'Saint Corneille, pape, et Saint Cyprien, évêque, martyrs',
	'robert-bellarmine': 'Saint Robert Bellarmin, évêque et docteur de l’Église',
	hildegard: 'Sainte Hildegarde de Bingen, vierge et docteur de l’Église',
	januarius: 'Saint Janvier, évêque et martyr',
	'andrew-kim':
		'Saint André Kim Tae-gon, prêtre, Saint Paul Chong Ha-sang, et leurs compagnons, martyrs',
	matthew: 'Saint Matthieu, apôtre et évangéliste',
	'padre-pio': 'Saint Pio de Pietrelcina, prêtre',
	'cosmas-damian': 'Saint Côme et Saint Damien, martyrs',
	'vincent-de-paul': 'Saint Vincent de Paul, prêtre',
	wenceslaus: 'Saint Venceslas, martyr',
	'lawrence-ruiz': 'Saint Laurent Ruiz et ses compagnons, martyrs',
	archangels: 'Saint Michel, Saint Gabriel et Saint Raphaël, archanges',
	jerome: 'Saint Jérôme, prêtre et docteur de l’Église',
	'therese-of-lisieux': 'Sainte Thérèse de l’Enfant-Jésus, vierge et docteur de l’Église',
	'guardian-angels': 'Les Saints Anges Gardiens',
	'francis-of-assisi': 'Saint François d’Assise, religieux',
	faustina: 'Sainte Faustine Kowalska, vierge',
	bruno: 'Saint Bruno, prêtre',
	'our-lady-of-the-rosary': 'Notre-Dame du Rosaire',
	denis: 'Saint Denis, évêque, et ses compagnons, martyrs',
	'john-leonardi': 'Saint Jean Leonardi, prêtre',
	'john-henry-newman': 'Saint John Henry Newman, prêtre et docteur de l’Église',
	'john-xxiii': 'Saint Jean XXIII, pape',
	'callistus-i': 'Saint Calliste Iᵉʳ, pape et martyr',
	'teresa-of-avila': 'Sainte Thérèse d’Avila, vierge et docteur de l’Église',
	hedwig: 'Sainte Edwige, religieuse',
	'margaret-mary-alacoque': 'Sainte Marguerite-Marie Alacoque, vierge',
	'ignatius-of-antioch': 'Saint Ignace d’Antioche, évêque et martyr',
	luke: 'Saint Luc, évangéliste',
	'north-american-martyrs':
		'Saint Jean de Brébeuf, Saint Isaac Jogues, prêtres, et leurs compagnons, martyrs',
	'paul-of-the-cross': 'Saint Paul de la Croix, prêtre',
	'john-paul-ii': 'Saint Jean-Paul II, pape',
	'john-of-capistrano': 'Saint Jean de Capistran, prêtre',
	'anthony-mary-claret': 'Saint Antoine-Marie Claret, évêque',
	'simon-jude': 'Saint Simon et Saint Jude, apôtres',
	'all-saints': 'Tous les Saints',
	'martin-de-porres': 'Saint Martin de Porrès',
	'charles-borromeo': 'Saint Charles Borromée, évêque',
	'dedication-of-the-lateran': 'La Dédicace de la Basilique du Latran',
	'leo-the-great': 'Saint Léon le Grand, pape et docteur de l’Église',
	'martin-of-tours': 'Saint Martin de Tours, évêque',
	josaphat: 'Saint Josaphat, évêque et martyr',
	'albert-the-great': 'Saint Albert le Grand, évêque et docteur de l’Église',
	'margaret-of-scotland': 'Sainte Marguerite d’Écosse',
	gertrude: 'Sainte Gertrude, vierge',
	'elizabeth-of-hungary': 'Sainte Élisabeth de Hongrie, religieuse',
	'dedication-of-peter-and-paul':
		'La Dédicace des Basiliques de Saint Pierre et de Saint Paul, apôtres',
	'presentation-of-mary': 'La Présentation de la Vierge Marie',
	cecilia: 'Sainte Cécile, vierge et martyre',
	'clement-i': 'Saint Clément Iᵉʳ, pape et martyr',
	columban: 'Saint Colomban, abbé',
	'andrew-dung-lac': 'Saint André Dung-Lac, prêtre, et ses compagnons, martyrs',
	'catherine-of-alexandria': 'Sainte Catherine d’Alexandrie, vierge et martyre',
	andrew: 'Saint André, apôtre',
	'francis-xavier': 'Saint François Xavier, prêtre',
	'john-damascene': 'Saint Jean de Damas, prêtre et docteur de l’Église',
	nicholas: 'Saint Nicolas, évêque',
	ambrose: 'Saint Ambroise, évêque et docteur de l’Église',
	'immaculate-conception': 'L’Immaculée Conception de la Vierge Marie',
	'juan-diego': 'Saint Juan Diego Cuautlatoatzi',
	'our-lady-of-loreto': 'Notre-Dame de Lorette',
	'damasus-i': 'Saint Damase Iᵉʳ, pape',
	'our-lady-of-guadalupe': 'Notre-Dame de Guadaloupé',
	lucy: 'Sainte Lucie, vierge et martyre',
	'john-of-the-cross': 'Saint Jean de la Croix, prêtre et docteur de l’Église',
	'peter-canisius': 'Saint Pierre Canisius, prêtre et docteur de l’Église',
	'john-of-kanty': 'Saint Jean de Kenty, prêtre',
	stephen: 'Saint Étienne, premier martyr',
	'john-evangelist': 'Saint Jean, apôtre et évangéliste',
	'holy-innocents': 'Les Saints Innocents, martyrs',
	'thomas-becket': 'Saint Thomas Becket, évêque et martyr',
	'sylvester-i': 'Saint Sylvestre Iᵉʳ, pape',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'La Nativité du Seigneur',
	'holy-family': 'Sainte Famille',
	'mary-mother-of-god': 'Sainte Marie, Mère de Dieu',
	'christmas-2-sunday': '2ᵉ Dimanche de la Nativité',
	epiphany: 'L’Épiphanie',
	'baptism-of-the-lord': 'Le Bapteme du Seigneur',
	'ash-wednesday': 'Mercredi des Cendres',
	'palm-sunday': 'Dimanche des Rameaux et de la Passion du Seigneur',
	'holy-thursday': 'Jeudi Saint: La Cène du Seigneur',
	'good-friday': 'Vendredi Saint: Célébration de la Passion et de la Mort du Seigneur',
	'holy-saturday': 'Samedi Saint',
	'easter-sunday': 'Dimanche de Pâques: La Résurrection du Seigneur',
	'easter-2-sunday': '2ᵉ Dimanche de Pâques ou de la Miséricorde',
	ascension: 'Ascension du Seigneur',
	pentecost: 'Dimanche de la Pentecôte',
	trinity: 'La Très Sainte Trinité',
	'corpus-christi': 'Le Saint-Sacrement du Corps et du Sang du Christ',
	'sacred-heart': 'Le Sacré-Cœur de Jésus',
	'immaculate-heart': 'Le Cœur Immaculé de Marie',
	'mary-mother-of-the-church': 'Bienheureuse Vierge Marie, Mère de l’Église',
	'christ-the-king': 'Notre Seigneur Jésus Christ Roi de l’Univers'
};

/**
 * The Proper of Time in French, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const frTemporal: TemporalNames = {
	days: { 1: 'Lundi', 2: 'Mardi', 3: 'Mercredi', 4: 'Jeudi', 5: 'Vendredi', 6: 'Samedi' },
	weeks: {
		1: '1ᵉʳ',
		2: '2ᵉ',
		3: '3ᵉ',
		4: '4ᵉ',
		5: '5ᵉ',
		6: '6ᵉ',
		7: '7ᵉ',
		8: '8ᵉ',
		9: '9ᵉ',
		10: '10ᵉ',
		11: '11ᵉ',
		12: '12ᵉ',
		13: '13ᵉ',
		14: '14ᵉ',
		15: '15ᵉ',
		16: '16ᵉ',
		17: '17ᵉ',
		18: '18ᵉ',
		19: '19ᵉ',
		20: '20ᵉ',
		21: '21ᵉ',
		22: '22ᵉ',
		23: '23ᵉ',
		24: '24ᵉ',
		25: '25ᵉ',
		26: '26ᵉ',
		27: '27ᵉ',
		28: '28ᵉ',
		29: '29ᵉ',
		30: '30ᵉ',
		31: '31ᵉ',
		32: '32ᵉ',
		33: '33ᵉ',
		34: '34ᵉ'
	},
	octave: { 5: '5ᵉ', 6: '6ᵉ', 7: '7ᵉ' },
	sunday: {
		advent: '{week} Dimanche de l’Avent',
		lent: '{week} Dimanche de Carême',
		easter: '{week} Dimanche de Pâques',
		ordinary: '{week} Dimanche du Temps Ordinaire'
	},
	weekday: {
		advent: '{day} de la {week} Semaine de l’Avent',
		lent: '{day} de la {week} Semaine de Carême',
		easter: '{day} de la {week} Semaine de Pâques',
		ordinary: '{day} de la {week} Semaine du Temps Ordinaire'
	},
	holyWeek: '{day} Saint',
	afterAshes: '{day} après les Cendres',
	afterEpiphany: '{day} après l’Épiphanie',
	christmasWeekday: '{day} du Temps de la Nativité',
	easterOctave: '{day} dans l’Octave de Pâques',
	christmasOctave: '{nth} jour dans l’octave de la Nativité'
};
