/**
 * The General Roman Calendar in Croatian.
 *
 * Transcribed from the 2 calendars GCatholic publishes in Croatian.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 213 of the Calendar's 218. The 5 absent are the ones every calendar in
 * this language keeps someone else on the day of — `scholastica` among them
 * — so this edition never prints them and they go on falling back to
 * English, which is what `celebrationName` is for.
 */
export const hr: Record<string, string> = {
	'basil-gregory': 'Sv. Bazilije Veliki i Grgur Nazijanski, biskupi i crkveni naučitelji',
	'holy-name-of-jesus': 'Presveto Ime Isusovo',
	'raymond-of-penyafort': 'Sv. Rajmund Penjafortski, prezbiter',
	hilary: 'Sv. Hilarije, biskup i crkveni naučitelj',
	'anthony-abbot': 'Sv. Antun, opat',
	fabian: 'Sv. Fabijan, papa i mučenik',
	sebastian: 'Sv. Sebastijan, mučenik',
	agnes: 'Sv. Agneza, djevica i mučenica',
	'vincent-deacon': 'Sv. Vinko, đakon i mučenik',
	'francis-de-sales': 'Sv. Franjo Saleški, biskup i crkveni naučitelj',
	'conversion-of-paul': 'Obraćenje sv. Pavla apostola',
	'timothy-titus': 'Sv. Timotej i Tit, biskupi',
	'angela-merici': 'Sv. Anđela Merici, djevica',
	'thomas-aquinas': 'Sv. Toma Akvinski, prezbiter i crkveni naučitelj',
	'john-bosco': 'Sv. Ivan Bosco, prezbiter',
	'presentation-of-the-lord': 'Prikazanje Gospodinovo',
	blaise: 'Sv. Blaž, biskup i mučenik',
	ansgar: 'Sv. Oskar, biskup',
	agatha: 'Sv. Agata, djevica i mučenica',
	'paul-miki': 'Sv. Pavao Miki i drugovi, mučenici',
	'jerome-emiliani': 'Sv. Jeronim Emilijani',
	'josephine-bakhita': 'Sv. Jozefina Bakhita, djevica',
	'our-lady-of-lourdes': 'Blažena Djevica Marija Lurdska',
	'seven-founders': 'Sedam sv. utemeljitelja Reda slugu BDM',
	'peter-damian': 'Sv. Petar Damiani, biskup i naučitelj',
	'chair-of-peter': 'Katedra sv. Petra apostola',
	polycarp: 'Sv. Polikarp, biskup i mučenik',
	'gregory-of-narek': 'Sv. Grgur iz Nareka, opat i crkveni naučitelj',
	casimir: 'Sv. Kazimir',
	'perpetua-felicity': 'Sv. Perpetua i Felicita, mučenice',
	'john-of-god': 'Sv. Ivan od Boga, redovnik',
	'frances-of-rome': 'Sv. Franciska Rimska, redovnica',
	patrick: 'Sv. Patrik, biskup',
	'cyril-of-jerusalem': 'Sv. Ćiril Jeruzalemski, biskup i crkveni naučitelj',
	joseph: 'Sv. Josip, zaručnik Blažene Djevice Marije',
	turibius: 'Sv. Turbije Mongrovejski, biskup',
	annunciation: 'Navještenje Gospodinovo',
	'francis-of-paola': 'Sv. Franjo Paolski, pustinjak',
	isidore: 'Sv. Izidor, biskup i crkveni naučitelj',
	'vincent-ferrer': 'Sv. Vinko Ferrer, prezbiter',
	'john-baptist-de-la-salle': 'Sv. Ivan Krstitelj de la Salle, prezbiter',
	stanislaus: 'Sv. Stanislav, biskup i mučenik',
	'martin-i': 'Sv. Martin I., papa i mučenik',
	anselm: 'Sv. Anzelmo, biskup i crkveni naučitelj',
	george: 'Sv. Juraj, mučenik',
	adalbert: 'Sv. Adalbert, biskup i mučenik',
	fidelis: 'Sv. Fidel Sigmarigenski, prezbiter i mučenik',
	mark: 'Sv. Marko, evanđelist',
	'peter-chanel': 'Sv. Petar Chanel, prezbiter i mučenik',
	'louis-de-montfort': 'Sv. Ljudevit M. Grignion de Monfort, prezbiter',
	'catherine-of-siena': 'Sv. Katarina Sijenska, djevica i crkvena naučiteljica',
	'pius-v': 'Sv. Pio V., papa',
	'joseph-the-worker': 'Sv. Josip Radnik',
	athanasius: 'Sv. Atanazije, biskup i crkveni naučitelj',
	'philip-james': 'Sv. Filip i Jakov, apostoli',
	'john-of-avila': 'Sv. Ivan Avilski, prezbiter i crkveni naučitelj',
	'our-lady-of-fatima': 'Blažena Djevica Marija Fatimska',
	matthias: 'Sv. Matija, apostol',
	'john-i': 'Sv. Ivan I., papa i mučenik',
	'bernardine-of-siena': 'Sv. Bernardin Sijenski, prezbiter',
	'christopher-magallanes': 'Sv. Kristofor Magallanes, prezbiter i drugovi, mučenici',
	'rita-of-cascia': 'Sv. Rita iz Cascie, redovnica',
	bede: 'Sv. Beda Časni, prezbiter i crkveni naučitelj',
	'gregory-vii': 'Sv. Grgur VII., papa',
	'mary-magdalene-de-pazzi': 'Sv. Marija Magdalena de’ Pazzi, djevica',
	'philip-neri': 'Sv. Filip Neri, prezbiter',
	'augustine-of-canterbury': 'Sv. Augustin Kenterberijski, biskup',
	'paul-vi': 'Sv. Pavao VI., papa',
	visitation: 'Pohod Blažene Djevice Marije',
	justin: 'Sv. Justin, mučenik',
	'marcellinus-peter': 'Sv. Marcelin i Petar, mučenici',
	'charles-lwanga': 'Sv. Karlo Lwanga i drugovi, mučenici',
	boniface: 'Sv. Bonifacije, biskup i mučenik',
	norbert: 'Sv. Norbert, biskup',
	ephrem: 'Sv. Efrem, đakon i crkveni naučitelj',
	barnabas: 'Sv. Barnaba, apostol',
	'anthony-of-padua': 'Sv. Antun Padovanski, prezbiter i crkveni naučitelj',
	romuald: 'Sv. Romuald, opat',
	'aloysius-gonzaga': 'Sv. Alojzije Gonzaga, redovnik',
	'paulinus-of-nola': 'Sv. Paulin iz Nole, biskup',
	'fisher-more': 'Sv. Ivan Fisher, biskup i sv. Toma More, mučenici',
	'birth-of-john-the-baptist': 'Rođenje Sv. Ivana Krstitelja',
	'cyril-of-alexandria': 'Sv. Ćiril Aleksandrijski, biskup i crkveni naučitelj',
	irenaeus: 'Sv. Irenej, biskup, mučenik i crkveni naučitelj',
	'peter-and-paul': 'Sv. Petar i Pavao, apostoli',
	'first-martyrs-of-rome': 'Sv. prvomučenici Svete Rimske Crkve',
	'thomas-apostle': 'Sv. Toma, apostol',
	'elizabeth-of-portugal': 'Sv. Elizabeta Portugalska',
	'maria-goretti': 'Sv. Marija Goretti, djevica i mučenica',
	'augustine-zhao-rong': 'Sv. Augustin Zhao Rong, prezbiter i drugovi, mučenici',
	benedict: 'Sv. Benedikt, opat',
	henry: 'Sv. Henrik, kralj',
	camillus: 'Sv. Kamilo de Lellis, prezbiter',
	bonaventure: 'Sv. Bonaventura, biskup i crkveni naučitelj',
	'our-lady-of-mount-carmel': 'Blažena Djevica Marija od brda Karmela',
	apollinaris: 'Sv. Apolinarije, biskup i mučenik',
	'lawrence-of-brindisi': 'Sv. Lovro Brindiški, prezbiter i crkveni naučitelj',
	'mary-magdalene': 'Sv. Marija Magdalena',
	bridget: 'Sv. Brigita, redovnica',
	sharbel: 'Sv. Sarbel Makhlūf, prezbiter',
	james: 'Sv. Jakov, apostol',
	'joachim-anne': 'Sv. Joakim i Ana, roditelji Blažene Djevice Marije',
	'martha-mary-lazarus': 'Sv. Marta, Marija i Lazar',
	'peter-chrysologus': 'Sv. Petar Krizolog, biskup i crkveni naučitelj',
	'ignatius-of-loyola': 'Sv. Ignacije Lojolski, prezbiter',
	'alphonsus-liguori': 'Sv. Alfonz Marija de’ Liguori, biskup i crkveni naučitelj',
	'eusebius-of-vercelli': 'Sv. Euzebije Verčelski, biskup',
	'peter-julian-eymard': 'Sv. Petar Juliani Eymard, prezbiter',
	'john-vianney': 'Sv. Ivan Marija Vianney, prezbiter',
	'dedication-st-mary-major': 'Posveta bazilike svete Marije Velike',
	transfiguration: 'Preobraženje Gospodinovo',
	'sixtus-ii': 'Sv. Siksto II., papa i drugovi, mučenici',
	cajetan: 'Sv. Kajetan, prezbiter',
	dominic: 'Sv. Dominik, prezbiter',
	'teresa-benedicta': 'Sv. Terezija Benedikta od Križa, djevica i mučenica',
	lawrence: 'Sv. Lovro, đakon i mučenik',
	clare: 'Sv. Klara, djevica',
	'jane-frances-de-chantal': 'Sv. Ivana Franciska de Chantal, redovnica',
	'pontian-hippolytus': 'Sv. Poncijan, papa i Hipolit, prezbiter, mučenici',
	'maximilian-kolbe': 'Sv. Maksimilijan Marija Kolbe, prezbiter i mučenik',
	assumption: 'Uznesenje Blažene Djevice Marije',
	'stephen-of-hungary': 'Sv. Stjepan Ugarski, kralj',
	'john-eudes': 'Sv. Ivan Eudes, prezbiter',
	bernard: 'Sv. Bernard, opat i crkveni naučitelj',
	'pius-x': 'Sv. Pio X., papa',
	'queenship-of-mary': 'Blažena Djevica Marija Kraljica',
	'rose-of-lima': 'Sv. Ruža Limska, djevica',
	bartholomew: 'Sv. Bartolomej apoštol',
	louis: 'Sv. Ljudevit, kralj',
	'joseph-calasanz': 'Sv. Josip Kalasancijski, prezbiter',
	monica: 'Sv. Monika',
	augustine: 'Sv. Augustin, biskup i crkveni naučitelj',
	'passion-of-john-the-baptist': 'Mučeništvo sv. Ivana Krstitelja',
	'gregory-the-great': 'Sv. Grgur Veliki, papa i crkveni naučitelj',
	'teresa-of-calcutta': 'Sv. Terezija iz Kalkute, djevica',
	'nativity-of-mary': 'Rodjenje Blazene Djevice Marije',
	'peter-claver': 'Sv. Petar Claver, prezbiter',
	'holy-name-of-mary': 'Ime Marijino',
	'john-chrysostom': 'Sv. Ivan Zlatousti, biskup i crkveni naučitelj',
	'exaltation-of-the-cross': 'Uzvišenje Svetog Križa',
	'our-lady-of-sorrows': 'Blažena Djevica Marija Žalosna',
	'cornelius-cyprian': 'Sv. Kornelije, papa i Ciprijan, biskup, mučenici',
	'robert-bellarmine': 'Sv. Robert Bellarmino, biskup i crkveni naučitelj',
	hildegard: 'Sv. Hildegarda Bingenška, djevica i crkvena naučiteljica',
	januarius: 'Sv. Januarije, biskup i mučenik',
	'andrew-kim': 'Sv. Andrija Kim Taegon, prezbiter, Pavao Chong Ha-sang i drugovi, mučenici',
	matthew: 'Sv. Matej, apostol i evanđelist',
	'padre-pio': 'Sv. Pio iz Pietrelcine, prezbiter',
	'cosmas-damian': 'Sv. Kuzma i Damjan, mučenici',
	'vincent-de-paul': 'Sv. Vinko Paulski, prezbiter',
	wenceslaus: 'Sv. Većeslav, mučenik',
	'lawrence-ruiz': 'Sv. Lovro Ruiz i drugovi, mučenici',
	archangels: 'Sv. Mihael, Gabriel i Rafael, arkanđeli',
	jerome: 'Sv. Jeronim, prezbiter i crkveni naučitelj',
	'therese-of-lisieux': 'Sv. Terezija od Djeteta Isusa, djevica i crkvena naučiteljica',
	'guardian-angels': 'Sv. Anđeli Čuvari',
	'francis-of-assisi': 'Sv. Franjo Asiški, redovnik',
	faustina: 'Sv. Faustina Kowalska, djevica',
	bruno: 'Sv. Bruno, prezbiter',
	'our-lady-of-the-rosary': 'Blažena Djevica Marija od krunice',
	denis: 'Sv. Dionizije, biskup i drugovi, mučenici',
	'john-leonardi': 'Sv. Ivan Leonardi, prezbiter',
	'john-henry-newman': 'Sv. John Henry Newman, prezbiter I crkveni naučitelj',
	'john-xxiii': 'Sv. Ivan XXIII., papa',
	'callistus-i': 'Sv. Kalist I., papa i mučenik',
	'teresa-of-avila': 'Sv. Terezija Avilska, djevica i crkvena naučiteljica',
	hedwig: 'Sv. Hedviga, redovnica',
	'margaret-mary-alacoque': 'Sv. Margareta Marija Alacoque, djevica',
	'ignatius-of-antioch': 'Sv. Ignacije Antiohijski, biskup i mučenik',
	luke: 'Sv. Luka, evanđelist',
	'north-american-martyrs': 'Sv. Ivan Brebefski i sv. Izak Jogues, prezbiteri, i drugovi, mučenici',
	'paul-of-the-cross': 'Sv. Pavao od Križa, prezbiter',
	'john-paul-ii': 'Sv. Ivan Pavao II., papa',
	'john-of-capistrano': 'Sv. Ivan Kapistranski, prezbiter',
	'anthony-mary-claret': 'Sv. Antun Marija Claret, biskup',
	'simon-jude': 'Sv. Šimun i Juda Tadej, apostoli',
	'all-saints': 'Svi Sveti',
	'martin-de-porres': 'Sv. Martin iz Porresa, redovnik',
	'charles-borromeo': 'Sv. Karlo Boromejski, biskup',
	'dedication-of-the-lateran': 'Posveta Lateranske bazilike',
	'leo-the-great': 'Sv. Leon Veliki, papa i crkveni naučitelj',
	'martin-of-tours': 'Sv. Martin Tourski, biskup',
	josaphat: 'Sv. Jozafat, biskup i mučenik',
	'albert-the-great': 'Sv. Albert Veliki, biskup i naučitelj',
	'margaret-of-scotland': 'Sv. Margareta Škotska',
	gertrude: 'Sv. Gertruda, djevica',
	'elizabeth-of-hungary': 'Sv. Elizabeta Ugarska, redovnica',
	'dedication-of-peter-and-paul': 'Posveta bazilika sv. Petra i Pavla, apostola',
	'presentation-of-mary': 'Prikazanje Blažene Djevice Marije',
	cecilia: 'Sv. Cecilija, djevica i mučenica',
	'clement-i': 'Sv. Klement I., papa i mučenik',
	columban: 'Sv. Kolumban, opat',
	'andrew-dung-lac': 'Sv. Andrija Dung-Lac, prezbiter i drugovi, mučenici',
	'catherine-of-alexandria': 'Sv. Katarina Aleksandrijska, djevica i mučenica',
	andrew: 'Sv. Andrija, apostol',
	'francis-xavier': 'Sv. Franjo Ksaverski, prezbiter',
	'john-damascene': 'Sv. Ivan Damaščnski, prezbiter i crkveni naučitelj',
	nicholas: 'Sv. Nikola, biskup',
	ambrose: 'Sv. Ambrozije, biskup i crkveni naučitelj',
	'immaculate-conception': 'Bezgrješno začeće Blažene Djevice Marije',
	'juan-diego': 'Sv. Ivan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Blažena Djevica Marija Loretska',
	'damasus-i': 'Sv. Damaz I., papa',
	'our-lady-of-guadalupe': 'Blažena Djevica Marija Guadalupska',
	lucy: 'Sv. Lucija, djevica i mučenica',
	'john-of-the-cross': 'Sv. Ivan od Križa, prezbiter i crkveni naučitelj',
	'peter-canisius': 'Sv. Petar Kanizije, prezbiter i naučitelj',
	'john-of-kanty': 'Sv. Ivan Kentijski, prezbiter',
	stephen: 'Sv. Stjepan, prvomučenik',
	'john-evangelist': 'Sv. Ivan, apostol i evanđelista',
	'holy-innocents': 'Sv. Nevina Dječica, mučenici',
	'thomas-becket': 'Sv. Toma Becket, biskup i mučenik',
	'sylvester-i': 'Sv. Silvestar I., papa'
};
