/**
 * The General Roman Calendar in Hungarian.
 *
 * Transcribed from GCatholic's Hungarian edition of Hungary's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 207 of the Calendar's 218. The 11 absent are the ones Hungary keeps
 * someone else on the day of — `george` among them — so this edition never
 * prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `huTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const hu: Record<string, string> = {
	'basil-gregory': 'Nagy Szent Vazul és Nazianzi Szent Gergely püspökök és egyháztanitók',
	'holy-name-of-jesus': 'Jézus Szent Neve',
	'raymond-of-penyafort': 'Pennaforti Szent Rajmund áldozópap',
	hilary: 'Szent Hiláriusz püspök és egyháztanító',
	'anthony-abbot': 'Szent Antal apát',
	fabian: 'Szent Fábián pápa és vértanú',
	sebastian: 'Szent Sebestyén vértanú',
	agnes: 'Szent Ágnes szűz és vértanú',
	'vincent-deacon': 'Szent Vince diakónus és vértanú',
	'francis-de-sales': 'Szalézi Szent Ferenc püspök és egyháztanító',
	'conversion-of-paul': 'Szent Pál apostol megtérése',
	'timothy-titus': 'Szent Timóteus és Szent Titusz püspökök',
	'angela-merici': 'Merici Szent Angéla szűz',
	'thomas-aquinas': 'Aquinói Szent Tamás áldozópap és egyháztanító',
	'john-bosco': 'Bosco Szent János áldozópap',
	'presentation-of-the-lord': 'Urunk bemutatása – Gyertyaszentelő Boldogasszony',
	blaise: 'Szent Balázs püspök és vértanú',
	ansgar: 'Szent Anszgár (Oszkár) püspök',
	agatha: 'Szent Ágota szűz és vértanú',
	'paul-miki': 'Miki Szent Pál és társai, vértanúk',
	'jerome-emiliani': 'Emiliáni Szent Jeromos áldozópap',
	'josephine-bakhita': 'Bakhita Szent Jozefina szűz',
	scholastica: 'Szent Skolasztika szűz',
	'our-lady-of-lourdes': 'A Lourdes-i Boldogságos Szűz Mária',
	'cyril-methodius': 'Szent Cirill szerzetes és Szent Metód püspök',
	'seven-founders': 'A Szervita rend hét szent alapítója',
	'peter-damian': 'Damiáni Szent Péter püspök és egyháztanító',
	'chair-of-peter': 'Szent Péter apostol székfoglalása',
	polycarp: 'Szent Polikárp püspök és vértanú',
	'gregory-of-narek': 'Nareki Szent Gergely apát és egyháztanító',
	casimir: 'Szent Kázmér',
	'perpetua-felicity': 'Szent Perpétua és Szent Felicitasz vértanúk',
	'john-of-god': 'Istenes Szent János szerzetes',
	'frances-of-rome': 'Római Szent Franciska szerzetesnő',
	patrick: 'Szent Patrik püspök',
	'cyril-of-jerusalem': 'Jeruzsálemi Szent Cirill püspök és egyháztanító',
	joseph: 'Szent József, a Boldogságos Szűz Mária jegyese',
	turibius: 'Mongrovejói Szent Turibiusz püspök',
	annunciation: 'Urunk születésének hírüladása – Gyümölcsoltó Boldogasszony',
	'francis-of-paola': 'Paolai Szent Ferenc remete',
	isidore: 'Szent Izidor püspök és egyháztanító',
	'vincent-ferrer': 'Ferrer Szent Vince áldozópap',
	'john-baptist-de-la-salle': 'De la Salle Szent János áldozópap',
	stanislaus: 'Szent Szaniszló püspök és vértanú',
	'martin-i': 'Szent I. Márton pápa és vértanú',
	anselm: 'Szent Anzelm püspök és egyháztanító',
	adalbert: 'Szent Adalbert püspök és vértanú',
	fidelis: 'Sigmaringeni Szent Fidél áldozópap és vértanú',
	mark: 'Szent Márk evangélista',
	'peter-chanel': 'Chanel Szent Péter áldozópap és vértanú',
	'louis-de-montfort': 'Montforti Grinion Szent Lajos Mária áldozópap',
	'catherine-of-siena': 'Sziénai Szent Katalin szűz és egyháztanító',
	'pius-v': 'Szent V. Piusz pápa',
	'joseph-the-worker': 'Szent József, a munkás',
	athanasius: 'Szent Atanáz püspök és egyháztanító',
	'philip-james': 'Szent Fülöp és Szent Jakab apostolok',
	'john-of-avila': 'Avilai Szent János áldozópap és egyháztanító',
	'nereus-achilleus': 'Szent Néreusz és Szent Achilleusz vértanúk',
	pancras: 'Szent Pongrác vértanú',
	'our-lady-of-fatima': 'A Fatimai Boldogságos Szűz Mária',
	'john-i': 'Szent I. János pápa és vértanú',
	'bernardine-of-siena': 'Sienai Szent Bernardin áldozópap',
	'christopher-magallanes': 'Magallan Szent Kristóf áldozópap és társai, vértanúk',
	'rita-of-cascia': 'Casciai Szent Rita szerzetesnő',
	bede: 'Tiszteletreméltó Szent Béda áldozópap és egyháztanító',
	'gregory-vii': 'Szent VII. Gergely pápa',
	'mary-magdalene-de-pazzi': 'Pazzi Szent Mária Magdolna szűz',
	'philip-neri': 'Néri Szent Fülöp áldozópap',
	'augustine-of-canterbury': 'Canterbury Szent Ágoston püspök',
	'paul-vi': 'Szent VI. Pál pápa',
	justin: 'Szent Jusztinusz vértanú',
	'marcellinus-peter': 'Szent Marcellinusz és Szent Péter vértanúk',
	'charles-lwanga': 'Lwanga Szent Károly és társai, vértanúk',
	boniface: 'Szent Bonifác püspök és vértanú',
	norbert: 'Szent Norbert püspök',
	ephrem: 'Szír Szent Efrém diakónus és egyháztanító',
	barnabas: 'Szent Barnabás apostol',
	'anthony-of-padua': 'Páduai Szent Antal áldozópap és egyháztanító',
	romuald: 'Szent Romuald apát',
	'aloysius-gonzaga': 'Gonzága Szent Alajos szerzetes',
	'paulinus-of-nola': 'Nolai Szent Paulinusz püspök',
	'fisher-more': 'Fisher Szent János püspök és vértanúk és Morus Szent Tamás vértanúk',
	'birth-of-john-the-baptist': 'Keresztelő Szent János születése',
	irenaeus: 'Szent Ireneusz püspök, vértanú és egyháztanító',
	'peter-and-paul': 'Szent Péter és Szent Pál apostolok',
	'first-martyrs-of-rome': 'A római Egyház első szent vértanúi',
	'thomas-apostle': 'Szent Tamás apostol',
	'elizabeth-of-portugal': 'Portugáliai Szent Erzsébet',
	'anthony-zaccaria': 'Zaccaria Szent Antal Mária áldozópap',
	'maria-goretti': 'Goretti Szent Mária szűz és vértanú',
	'augustine-zhao-rong': 'Zhao Rong Szent Ágoston áldozópap és társai, vértanúk',
	benedict: 'Szent Benedek apát',
	henry: 'Szent Henrik',
	camillus: 'Lellisi Szent Kamill áldozópap',
	bonaventure: 'Szent Bonaventura püspök és egyháztanító',
	'our-lady-of-mount-carmel': 'Kármelhegyi Boldogasszony',
	apollinaris: 'Szent Apollinaris püspök és vértanú',
	'lawrence-of-brindisi': 'Brindisi Szent Lőrinc áldozópap és egyháztanító',
	'mary-magdalene': 'Szent Mária Magdolna',
	bridget: 'Szent Brigitta szerzetesnő',
	james: 'Szent Jakab apostol',
	'joachim-anne': 'Szent Joakim és Szent Anna, a Boldogságos Szűz Mária szülei',
	'martha-mary-lazarus': 'Szent Márta, Szent Mária és Szent Lázár',
	'peter-chrysologus': 'Aranyszavú (Krizológ) Szent Péter püspök és egyháztanító',
	'ignatius-of-loyola': 'Loyolai Szent Ignác áldozópap',
	'alphonsus-liguori': 'Ligouri Szent Alfonz Mária püspök és egyháztanító',
	'eusebius-of-vercelli': 'Vercelli Szent Özséb püspök',
	'peter-julian-eymard': 'Eymard Szent Péter Julián áldozópap',
	'john-vianney': 'Vianney Szent János Mária áldozópap',
	'dedication-st-mary-major': 'Szűz Mária Római Főtemplomának felszentelése',
	transfiguration: 'Urunk színeváltozása',
	'sixtus-ii': 'Szent II. Szixtusz pápa és társai, vértanúk',
	cajetan: 'Szent Kajetán áldozópap',
	dominic: 'Szent Domonkos áldozópap',
	'teresa-benedicta': 'A keresztről nevezett Szent Terézia Benedikta (Edit Stein) szűz és vértanú',
	lawrence: 'Szent Lőrinc diakónus és vértanú',
	clare: 'Szent Klára szűz',
	'jane-frances-de-chantal': 'Chantal Szent Johanna Franciska szerzetesnő',
	'maximilian-kolbe': 'Szent Maximilián Mária Kolbe áldozópap és vértanú',
	assumption: 'Szűz Mária mennybevétele (Nagyboldogasszony)',
	'pius-x': 'Szent X. Piusz pápa',
	'queenship-of-mary': 'Boldogságos Szűz Mária királynő',
	'rose-of-lima': 'Limai Szent Róza szűz',
	bartholomew: 'Szent Bertalan apostol',
	louis: 'Szent Lajos',
	'joseph-calasanz': 'Kalazanci Szent József áldozópap',
	monica: 'Szent Mónika',
	augustine: 'Szent Ágoston püspök és egyháztanító',
	'passion-of-john-the-baptist': 'Keresztelő Szent János vértanúsága',
	'gregory-the-great': 'Nagy Szent Gergely pápa és egyháztanító',
	'teresa-of-calcutta': 'Kalkuttai Szent Teréz szűz',
	'nativity-of-mary': 'Szűz Mária születése (Kisboldogasszony)',
	'peter-claver': 'Claver Szent Péter áldozópap',
	'holy-name-of-mary': 'Szűz Mária szent neve',
	'john-chrysostom': 'Aranyszájú (Krizosztomosz) Szent János püspök és egyháztanító',
	'exaltation-of-the-cross': 'Szent Kereszt felmagasztalása',
	'our-lady-of-sorrows': 'A Fájdalmas Szűzanya',
	'cornelius-cyprian': 'Szent Kornél pápa és Szent Ciprián püspök, vértanúk',
	'robert-bellarmine': 'Bellarmin Szent Róbert püspök és egyháztanító',
	hildegard: 'Bingeni Szent Hildegárd szűz és egyháztanító',
	januarius: 'Szent Januáriusz püspök és vértanú',
	'andrew-kim': 'Kim Taegon Szent András áldozópap és Csong Haszang Szent Pál és társai, vértanúk',
	matthew: 'Szent Máté apostol és evangélista',
	'padre-pio': 'Pietrelcinai Szent Pió áldozópap',
	'cosmas-damian': 'Szent Kozma és Szent Damján vértanúk',
	'vincent-de-paul': 'Páli Szent Vince áldozópap',
	wenceslaus: 'Szent Vencel vértanú',
	'lawrence-ruiz': 'Ruiz Szent Lőrinc és társai, vértanúk',
	archangels: 'Szent Mihály, Szent Gábor és Szent Rafael főangyalok',
	jerome: 'Szent Jeromos áldozópap és egyháztanító',
	'therese-of-lisieux': 'A Gyermek Jézusról nevezett (Lisieux-i) Szent Teréz szűz és egyháztanító',
	'guardian-angels': 'Szent Őrzőangyalok',
	'francis-of-assisi': 'Assisi Szent Ferenc',
	faustina: 'Kowalska Szent Faustyna szűz',
	bruno: 'Szent Brúnó áldozópap',
	'our-lady-of-the-rosary': 'Rózsafüzér Királynője',
	denis: 'Szent Dénes püspök és társai, vértanúk',
	'john-leonardi': 'Leonardi Szent János áldozópap',
	'john-henry-newman': 'Newman Szent János Henrik áldozópap és egyháztanító',
	'john-xxiii': 'Szent XXIII. János pápa',
	'callistus-i': 'Szent I. Kallixtusz pápa és vértanú',
	'teresa-of-avila': 'A Jézusról nevezett (Avilai) Szent Teréz szűz és egyháztanító',
	hedwig: 'Szent Hedvig szerzetesnő',
	'margaret-mary-alacoque': 'Alacoque Szent Margit Mária szűz',
	'ignatius-of-antioch': 'Antiochiai Szent Ignác püspök és vértanú',
	luke: 'Szent Lukács evangélista',
	'north-american-martyrs':
		'De Brébeuf Szent János és Jogues Szent Izsák áldozópapok és társai, vértanúk',
	'paul-of-the-cross': 'Keresztes Szent Pál áldozópap',
	'john-paul-ii': 'Szent II. János Pál pápa',
	'john-of-capistrano': 'Kapisztrán Szent János áldozópap',
	'anthony-mary-claret': 'Claret Szent Antal Mária püspök',
	'simon-jude': 'Szent Simon és Szent Júdás Tádé apostolok',
	'all-saints': 'Mindenszentek ünnepe',
	'martin-de-porres': 'Porres Szent Márton szerzetes',
	'charles-borromeo': 'Borromeo Szent Károly püspök',
	'dedication-of-the-lateran': 'A lateráni bazilika felszentelése',
	'leo-the-great': 'Nagy Szent Leó pápa és egyháztanító',
	'martin-of-tours': 'Tours-i Szent Márton püspök',
	josaphat: 'Szent Jozafát püspök és vértanú',
	'albert-the-great': 'Nagy Szent Albert püspök és egyháztanító',
	'margaret-of-scotland': 'Skóciai Szent Margit',
	'dedication-of-peter-and-paul': 'A Szent Péter- és Szent Pál-bazilikák felszentelése',
	'presentation-of-mary': 'A Boldogságos Szűz Mária bemutatása a templomban',
	cecilia: 'Szent Cecília szűz és vértanú',
	'clement-i': 'Szent Kelemen pápa és vértanú',
	columban: 'Szent Kolumbán apát',
	'andrew-dung-lac': 'Dung-Lac Szent András áldozópap és társai, vértanúk',
	'catherine-of-alexandria': 'Alexandriai Szent Katalin szűz és vértanú',
	andrew: 'Szent András apostol',
	'francis-xavier': 'Xavéri Szent Ferenc áldozópap',
	'john-damascene': 'Damaszkuszi Szent János áldozópap és egyháztanító',
	nicholas: 'Szent Miklós püspök',
	ambrose: 'Szent Ambrus püspök és egyháztanító',
	'immaculate-conception': 'A Boldogságos Szűz Mária szeplőtelen fogantatása',
	'juan-diego': 'Szent Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'A Loretói Boldogságos Szűz Mária',
	'damasus-i': 'Szent I. Damazusz pápa',
	'our-lady-of-guadalupe': 'A Guadalupei Boldogságos Szűz Mária',
	lucy: 'Szent Lúcia szűz és vértanú',
	'john-of-the-cross': 'Keresztes Szent János áldozópap és egyháztanító',
	'peter-canisius': 'Kaníziusz Szent Péter áldozópap és egyháztanító',
	'john-of-kanty': 'Kety Szent Jáno áldozópap',
	stephen: 'Szent István első vértanú',
	'john-evangelist': 'Szent János apostol és evangélista',
	'holy-innocents': 'Aprószentek, vértanúk',
	'thomas-becket': 'Becket Szent Tamás püspök és vértanú',
	'sylvester-i': 'Szent I. Szilveszter pápa',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Urunk születése – Karácsony',
	'holy-family': 'A Szent Család: Jézus, Mária és József',
	'mary-mother-of-god': 'Szűz Mária, Isten anyja',
	'christmas-2-sunday': 'Karácsony utáni 2. vasárnap',
	epiphany: 'Urunk megjelenése – Vízkereszt',
	'baptism-of-the-lord': 'Urunk megkeresztelkedése',
	'ash-wednesday': 'Hamvazószerda',
	'palm-sunday': 'Virágvasárnap',
	'holy-thursday': 'Nagycsütörtök',
	'good-friday': 'Nagypéntek',
	'holy-saturday': 'Nagyszombat',
	'easter-sunday': 'Húsvétvasárnap',
	'easter-2-sunday': 'Húsvét 2. vasárnapja, az isteni irgalmasság vasárnapja',
	ascension: 'Urunk mennybemenetele',
	pentecost: 'Pünkösdvasárnap',
	trinity: 'Szentháromság vasárnapja',
	'corpus-christi': 'Krisztus szent teste és vére – Úrnapja',
	'sacred-heart': 'Jézus Szent Szíve',
	'immaculate-heart': 'A Boldogságos Szűz Mária Szeplőtelen Szíve',
	'mary-mother-of-the-church': 'A Boldogságos Szűz Mária, az Egyház Anyja',
	'christ-the-king': 'Krisztus a Mindenség Királya'
};

/**
 * The Proper of Time in Hungarian, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const huTemporal: TemporalNames = {
	days: { 1: 'Hétfő', 2: 'Kedd', 3: 'Szerda', 4: 'Csütörtök', 5: 'Péntek', 6: 'Szombat' },
	weeks: {
		1: '1',
		2: '2',
		3: '3',
		4: '4',
		5: '5',
		6: '6',
		7: '7',
		8: '8',
		9: '9',
		10: '10',
		11: '11',
		12: '12',
		13: '13',
		14: '14',
		15: '15',
		16: '16',
		17: '17',
		18: '18',
		19: '19',
		20: '20',
		21: '21',
		22: '22',
		23: '23',
		24: '24',
		25: '25',
		26: '26',
		27: '27',
		28: '28',
		29: '29',
		30: '30',
		31: '31',
		32: '32',
		33: '33',
		34: '34'
	},
	octave: { 5: '5', 6: '6', 7: '7' },
	sunday: {
		advent: 'Advent {week}. vasárnapja',
		lent: 'Nagyböjt {week}. vasárnap',
		easter: 'Húsvét {week}. vasárnapja',
		ordinary: 'Évközi {week}. vasárnap'
	},
	weekday: {
		advent: '{week}. adventi hét {day}',
		lent: '{week}. nagyböjti hét {day}',
		easter: 'Húsvét {week}. hét {day}',
		ordinary: '{week}. évközi hét {day}'
	},
	holyWeek: { form: '{day}', days: { 1: 'Nagyhétfő', 2: 'Nagykedd', 3: 'Nagyszerda' } },
	afterAshes: '{day} hamvazószerda után',
	afterEpiphany: '{day}, Vízkereszt után',
	christmasWeekday: '{day}, Vizkereszt előtti',
	easterOctave: '{day} húsvét nyolcadában',
	christmasOctave: 'Karácsony nyolcada alatti {nth}. nap'
};
