/**
 * The General Roman Calendar in Indonesian.
 *
 * Transcribed from GCatholic's Indonesian edition of Indonesia's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 217 of the Calendar's 218. The one absent is `augustine-zhao-rong`, which
 * Indonesia keeps someone else on the day of, so this edition never prints
 * it and it goes on falling back to English — which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `idTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const id: Record<string, string> = {
	'basil-gregory': 'S. Basilius Agung dan Gregorius dari Nazianze, uskup dan pujangga Gereja',
	'holy-name-of-jesus': 'Nama Tersuci Yesus',
	'raymond-of-penyafort': 'S. Raimundus dari Penyafort, imam',
	hilary: 'S. Hilarius, uskup dan pujangga Gereja',
	'anthony-abbot': 'S. Antonius, abas',
	fabian: 'S. Fabianus, Paus dan martir',
	sebastian: 'S. Sebastianus, martir',
	agnes: 'S. Agnes, perawan dan martir',
	'vincent-deacon': 'S. Vinsensius, diakon dan martir',
	'francis-de-sales': 'S. Fransiskus dari Sales, uskup dan pujangga Gereja',
	'conversion-of-paul': 'Pertobatan S. Paulus, rasul',
	'timothy-titus': 'S. Timotius dan Titus, uskup',
	'angela-merici': 'S. Angela Merici, perawan',
	'thomas-aquinas': 'S. Tomas Aquino, imam dan pujangga Gereja',
	'john-bosco': 'S. Yohanes Bosko, imam',
	'presentation-of-the-lord': 'Yesus Dipersembahkan di Kanisah',
	blaise: 'S. Blasius, uskup dan martir',
	ansgar: 'S. Ansgarius, uskup',
	agatha: 'S. Agata, perawan dan martir',
	'paul-miki': 'S. Paulus Miki, imam, dan kawan-kawan, martir',
	'jerome-emiliani': 'S. Hieronimus Emilianus',
	'josephine-bakhita': 'S. Yosefina Bakhita, perawan',
	scholastica: 'S. Skolastika, perawan',
	'our-lady-of-lourdes': 'Santa Perawan Maria dari Lourdes',
	'cyril-methodius': 'S. Sirilus, rahib, dan Metodius, uskup',
	'seven-founders': 'Tujuh Santo Pendiri Ordo Hamba-hamba Santa Perwan Maria',
	'peter-damian': 'S. Petrus Damianus, uskup dan pujangga Gereja',
	'chair-of-peter': 'Takhta S. Petrus, rasul',
	polycarp: 'S. Polikarpus, uskup dan martir',
	'gregory-of-narek': 'S. Gregorius dari Narek, abas dan pujangga Gereja',
	casimir: 'S. Kasimirus',
	'perpetua-felicity': 'S. Perpetua dan Felisitas, martir',
	'john-of-god': 'S. Yohanes a Deo, biarawan',
	'frances-of-rome': 'S. Fransiska Romana, biarawati',
	patrick: 'S. Patrik, uskup',
	'cyril-of-jerusalem': 'S. Sirilus dari Yerusalem, uskup dan pujangga Gereja',
	joseph: 'S. Yusuf, Suami Santa Maria',
	turibius: 'S. Turibius dari Mogrovejo, uskup',
	annunciation: 'Kabar Sukacita',
	'francis-of-paola': 'S. Fransiskus dari Paola, pertapa',
	isidore: 'S. Isidorus, uskup dan pujangga Gereja',
	'vincent-ferrer': 'S. Vincensius Ferrer, imam',
	'john-baptist-de-la-salle': 'S. Yohanes Baptista de La Salle, imam',
	stanislaus: 'S. Stanislaus, uskup dan martir',
	'martin-i': 'S. Martinus I, Paus dan martir',
	anselm: 'S. Anselmus, uskup dan pujangga Gereja',
	george: 'S. Georgius, martir',
	adalbert: 'S. Adalbertus, uskup dan martir',
	fidelis: 'S. Fidelis dari Sigmaringen, imam dan martir',
	mark: 'S. Markus, PenInj',
	'peter-chanel': 'S. Petrus Chanel, imam dan martir',
	'louis-de-montfort': 'S. Louis-Mariæ Grignion de Montfort, imam',
	'catherine-of-siena': 'S. Katarina dari Siena, perawan dan pujangga Gereja',
	'pius-v': 'S. Pius V, Paus',
	'joseph-the-worker': 'S. Yusuf, Pekerja',
	athanasius: 'S. Atanasius, uskup dan pujangga Gereja',
	'philip-james': 'S. Filipus dan Yakobus, rasul',
	'john-of-avila': 'S. Yohanes dari Avila, imam dan pujangga Gereja',
	'nereus-achilleus': 'S. Nereus dan Akhilleus, martir',
	pancras: 'S. Pankrasius, martir',
	'our-lady-of-fatima': 'Santa Perawan Maria dari Fatima',
	matthias: 'S. Matias, rasul',
	'john-i': 'S. Yohanes I, Paus dan martir',
	'bernardine-of-siena': 'S. Bernardinus dari Siena, imam',
	'christopher-magallanes': 'S. Kristoforus Magallanes, imam, dan kawan-kawan, martir',
	'rita-of-cascia': 'S. Rita dari Cascia, biarawati',
	bede: 'S. Beda Venerabilis, imam dan pujangga Gereja',
	'gregory-vii': 'S. Gregorius VII, Paus',
	'mary-magdalene-de-pazzi': 'S. Maria Magdalena dё ’Pazzi, perawan',
	'philip-neri': 'S. Filipus Neri, imam',
	'augustine-of-canterbury': 'S. Agustinus dari Canterbury, uskup',
	'paul-vi': 'S. Paulus VI, Paus',
	visitation: 'Santa Perawan Maria Mengunjungi Elisabet Saudaranya',
	justin: 'S. Yustinus, martir',
	'marcellinus-peter': 'S. Marselinus dan Petrus, martir',
	'charles-lwanga': 'S. Karolus Lwanga dan kawan-kawan, martir',
	boniface: 'S. Bonifasius, uskup dan martir',
	norbert: 'S. Norbertus, uskup',
	ephrem: 'S. Efrem, diakon dan pujangga Gereja',
	barnabas: 'S. Barnabas, rasul',
	'anthony-of-padua': 'S. Antonius dari Padua, imam dan pujangga Gereja',
	romuald: 'S. Romualdus, abas',
	'aloysius-gonzaga': 'S. Aloisius Gonzaga, biarawan',
	'paulinus-of-nola': 'S. Paulinus dari Nola, uskup',
	'fisher-more': 'S. Yohanes Fisher, uskup, dan S. Thomas More, martir',
	'birth-of-john-the-baptist': 'Kelahiran S. Yohanes Pembaptis',
	'cyril-of-alexandria': 'S. Sirillus dari Aleksandria, uskup dan pujangga Gereja',
	irenaeus: 'S. Ireneus, uskup, martir dan pujangga Gereja',
	'peter-and-paul': 'S. Petrus dan Paulus, rasul',
	'first-martyrs-of-rome': 'Para Martir Pertama Gereja Roma yang Kudus',
	'thomas-apostle': 'S. Tomas, rasul',
	'elizabeth-of-portugal': 'S. Elisabet dari Portugal',
	'anthony-zaccaria': 'S. Antonius Maria Zakkaria, imam',
	'maria-goretti': 'S. Maria Goretti, perawan dan martir',
	benedict: 'S. Benediktus, abas',
	henry: 'S. Henrikus',
	camillus: 'S. Kamillus de Lellis, imam',
	bonaventure: 'S. Bonaventura, uskup dan pujangga Gereja',
	'our-lady-of-mount-carmel': 'Bunda Maria dari Gunung Karmel',
	apollinaris: 'S. Apollinaris, uskup dan martir',
	'lawrence-of-brindisi': 'S. Laurensius dari Brindisi, imam dan pujangga Gereja',
	'mary-magdalene': 'S. Maria Magdalena',
	bridget: 'S. Birgitta, biarawati',
	sharbel: 'S. Sharbel Makhlūf, imam',
	james: 'S. Yakobus, rasul',
	'joachim-anne': 'S. Yoakim dan Anna, orang tua Santa Perawan Maria',
	'martha-mary-lazarus': 'S. Marta, Maria, dan Lazarus',
	'peter-chrysologus': 'S. Petrus Krisologus, uskup dan pujangga Gereja',
	'ignatius-of-loyola': 'S. Ignasius dari Loyola, imam',
	'alphonsus-liguori': 'S. Alfonsus Maria de Liguori, uskup dan pujangga Gereja',
	'eusebius-of-vercelli': 'S. Eusebius Vercelli, uskup',
	'peter-julian-eymard': 'S. Petrus Yulianus Eymard, imam',
	'john-vianney': 'S. Yohanes Maria Vianney, imam',
	'dedication-st-mary-major': 'Pemberkatan Gereja Basilika Santa Maria Maggiore',
	transfiguration: 'Yesus Menampakkan Kemuliaan-Nya',
	'sixtus-ii': 'S. Sikstus II, Paus, dan kawan-kawan, martir',
	cajetan: 'S. Kayetanus, imam',
	dominic: 'S. Dominikus, imam',
	'teresa-benedicta': 'S. Teresia Benedikta dari Salib, perawan dan martir',
	lawrence: 'S. Laurensius, diakon dan martir',
	clare: 'S. Klara, perawan',
	'jane-frances-de-chantal': 'S. Yohana Fransiska de Chantal, biarawati',
	'pontian-hippolytus': 'S. Pontianus, Paus, dan S. Hipolitus, imam, martir',
	'maximilian-kolbe': 'S. Maksimilianus Maria Kolbe, imam dan martir',
	assumption: 'Santa Perawan Maria Diangkat ke Surga',
	'stephen-of-hungary': 'S. Stefanus dari Hungaria',
	'john-eudes': 'S. Yohanes Eudes, imam',
	bernard: 'S. Bernardus, abas dan pujangga Gereja',
	'pius-x': 'S. Pius X, Paus',
	'queenship-of-mary': 'Santa Perawan Maria, Ratu',
	'rose-of-lima': 'S. Rosa dari Lima, perawan',
	bartholomew: 'S. Bartolomeus, rasul',
	louis: 'S. Louis IX, raja',
	'joseph-calasanz': 'S. Yosef dari Calasanz, imam',
	monica: 'S. Monika',
	augustine: 'S. Agustinus, uskup dan pujangga Gereja',
	'passion-of-john-the-baptist': 'Kemartiran S. Yohanes Pembaptis',
	'gregory-the-great': 'S. Gregorius Agung, Paus dan pujangga Gereja',
	'teresa-of-calcutta': 'S. Teresa dari Kalkuta, perawan',
	'nativity-of-mary': 'Kelahiran Santa Perawan Maria',
	'peter-claver': 'S. Petrus Klaver, imam',
	'holy-name-of-mary': 'Nama Tersuci Santa Perawan Maria',
	'john-chrysostom': 'S. Yohanes Krisostomus, uskup dan pujangga Gereja',
	'exaltation-of-the-cross': 'Salib Suci',
	'our-lady-of-sorrows': 'Santa Perawan Maria Berdukacita',
	'cornelius-cyprian': 'S. Kornelius, Paus, dan S. Siprianus, uskup, martir',
	'robert-bellarmine': 'S. Robertus Bellarminus, uskup dan pujangga Gereja',
	hildegard: 'S. Hildegard dari Bingen, perawan dan pujangga Gereja',
	januarius: 'S. Yanuarius, uskup dan martir',
	'andrew-kim': 'S. Andreas Kim Tae-gŏn, imam, Paulus Chŏng Ha-sang, dan kawan-kawan, martir',
	matthew: 'S. Matius, rasul dan penulis Injil',
	'padre-pio': 'S. Pius dari Pietrelcina, imam',
	'cosmas-damian': 'S. Kosmas dan Damianus, uskup, martir',
	'vincent-de-paul': 'S. Vinsensius a Paulo, imam',
	wenceslaus: 'S. Wenseslaus, martir',
	'lawrence-ruiz': 'S. Laurensius Ruiz, dan kawan-kawan, martir',
	archangels: 'S. Mikael, Gabriel, dan Rafael, Malaikat Agung',
	jerome: 'S. Hieronimus, imam dan pujangga Gereja',
	'therese-of-lisieux': 'S. Teresia dari Kanak-Kanak Yesus, perawan dan pujangga Gereja',
	'guardian-angels': 'Para Malaikat Pelindung',
	'francis-of-assisi': 'S. Fransiskus dari Assisi',
	faustina: 'S. Faustina Kowalska, perawan',
	bruno: 'S. Bruno, imam',
	'our-lady-of-the-rosary': 'Santa Perawan Maria, Ratu Rosario',
	denis: 'S. Dionisius, uskup, dan kawan-kawan, martir',
	'john-leonardi': 'S. Yohanes Leonardus, imam',
	'john-henry-newman': 'S. John Henry Newman, imam dan pujangga Gereja',
	'john-xxiii': 'S. Yohanes XXIII, Paus',
	'callistus-i': 'S. Kalistus I, Paus dan martir',
	'teresa-of-avila': 'S. Teresia dari Avila, perawan dan pujangga Gereja',
	hedwig: 'S. Hedwig, biarawati',
	'margaret-mary-alacoque': 'S. Margarita Maria Alacoque, perawan',
	'ignatius-of-antioch': 'S. Ignasius dari Antiokhia, uskup dan martir',
	luke: 'S. Lukas, penulis Injil',
	'north-american-martyrs': 'S. Yohanes de Brébeuf dan Ishak Jogues, imam, dan kawan-kawan, martir',
	'paul-of-the-cross': 'S. Paulus dari Salib, imam',
	'john-paul-ii': 'S. Yohanes Paulus II, Paus',
	'john-of-capistrano': 'S. Yohanes dari Capestrano, imam',
	'anthony-mary-claret': 'S. Antonius Maria Claret, uskup',
	'simon-jude': 'S. Simon dan Yudas, rasul',
	'all-saints': 'Semua Orang Kudus',
	'martin-de-porres': 'S. Martinus de Porres, biarawan',
	'charles-borromeo': 'S. Carolus Borromeus, uskup',
	'dedication-of-the-lateran': 'Pemberkatan Gereja Basilik Lateran',
	'leo-the-great': 'S. Leo Agung, Paus dan pujangga Gereja',
	'martin-of-tours': 'S. Martinus dari Tours, uskup',
	josaphat: 'S. Yosafat, uskup dan martir',
	'albert-the-great': 'S. Albertus Agung, uskup dan pujangga Gereja',
	'margaret-of-scotland': 'S. Margarita dari Skotlandia',
	gertrude: 'S. Gertrudis, perawan',
	'elizabeth-of-hungary': 'S. Elisabet dari Hungaria, biarawati',
	'dedication-of-peter-and-paul':
		'Pemberkatan Basilika Santo Petrus Rasul dan Basilika Santo Paulus Rasul',
	'presentation-of-mary': 'Santa Perawan Maria Dipersembahkan dalam Kanisah',
	cecilia: 'S. Sesilia, perawan dan martir',
	'clement-i': 'S. Klemens I, Paus dan martir',
	columban: 'S. Kolumbanus, abas',
	'andrew-dung-lac': 'S. Andreas Dũng Lac, imam, dan kawan-kawan, martir',
	'catherine-of-alexandria': 'S. Katarina dari Aleksandria, perawan dan martir',
	andrew: 'S. Andreas, rasul',
	'francis-xavier': 'S. Fransiskus Xaverius, imam',
	'john-damascene': 'S. Yohanes dari Damsyik, imam dan pujangga Gereja',
	nicholas: 'S. Nikolaus, uskup',
	ambrose: 'S. Ambrosius, uskup dan pujangga Gereja',
	'immaculate-conception': 'Santa Perawan Maria Dikandung Tanpa Noda',
	'juan-diego': 'S. Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Santa Perawan Maria dari Loreto',
	'damasus-i': 'S. Damasus I, Paus',
	'our-lady-of-guadalupe': 'Santa Perawan Maria Guadalupe',
	lucy: 'S. Lusia, perawan dan martir',
	'john-of-the-cross': 'S. Yohanes dari Salib, imam dan pujangga Gereja',
	'peter-canisius': 'S. Petrus Kanisius, imam dan pujangga Gereja',
	'john-of-kanty': 'S. Yohanes Kansius, imam',
	stephen: 'S. Stefanus, martir pertama',
	'john-evangelist': 'S. Yohanes, rasul dan penulis Injil',
	'holy-innocents': 'Kanak-kanak Suci, martir',
	'thomas-becket': 'S. Thomas Becket, uskup dan martir',
	'sylvester-i': 'S. Silvester I, Paus',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Natal',
	'holy-family': 'Keluarga Kudus, Yesus, Maria dan Yusuf',
	'mary-mother-of-god': 'Santa Maria Bunda Allah',
	epiphany: 'Penampakan Tuhan',
	'baptism-of-the-lord': 'Pembaptisan Tuhan',
	'ash-wednesday': 'Rabu Abu',
	'palm-sunday': 'Hari Minggu Palma Mengenangkan Sengsara Tuhan',
	'holy-thursday': 'Kamas Putih',
	'good-friday': 'Hari Jumat Agung',
	'holy-saturday': 'Hari Sabtu Suci',
	'easter-sunday': 'Paskah Kebangkitan Tuhan',
	'easter-2-sunday': 'Hari Minggu Paskah II',
	ascension: 'Kenaikan Tuhan',
	pentecost: 'Pentakosta',
	trinity: 'Tritunggal Maha Kudus',
	'corpus-christi': 'Tubuh dan Darah Kristus',
	'sacred-heart': 'Hati Yesus Yang Mahakudus',
	'immaculate-heart': 'Hati Tak Bernoda Santa Perawan Maria',
	'mary-mother-of-the-church': 'Santa Perawan Maria, Bunda Gereja',
	'christ-the-king': 'Tuhan Kita Yesus Kristus Raja Semesta Alam'
};

/**
 * The Proper of Time in Indonesian, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const idTemporal: TemporalNames = {
	days: { 1: 'Senin', 2: 'Selasa', 3: 'Rabu', 4: 'Kamis', 5: 'Jumat', 6: 'Sabtu' },
	weeks: {
		1: 'I',
		2: 'II',
		3: 'III',
		4: 'IV',
		5: 'V',
		6: 'VI',
		7: 'VII',
		8: 'VIII',
		9: 'IX',
		10: 'X',
		11: 'XI',
		12: 'XII',
		13: 'XIII',
		14: 'XIV',
		15: 'XV',
		16: 'XVI',
		17: 'XVII',
		18: 'XVIII',
		19: 'XIX',
		20: 'XX',
		21: 'XXI',
		22: 'XXII',
		23: 'XXIII',
		24: 'XXIV',
		25: 'XXV',
		26: 'XXVI',
		27: 'XXVII',
		28: 'XXVIII',
		29: 'XXIX',
		30: 'XXX',
		31: 'XXXI',
		32: 'XXXII',
		33: 'XXXIII',
		34: 'XXXIV'
	},
	octave: { 5: 'Kelima', 6: 'Keenam', 7: 'Ketujuh' },
	sunday: {
		advent: 'Hari Minggu Adven {week}',
		lent: 'Hari Minggu Prapaskah {week}',
		easter: 'Hari Minggu Paskah {week}',
		ordinary: 'Hari Minggu Biasa {week}'
	},
	weekday: {
		advent: '{day} Pekan Adven {week}',
		lent: '{day} Pekan Prapaskah {week}',
		easter: '{day} Pekan Paskah {week}',
		ordinary: '{day} Pekan Biasa {week}'
	},
	holyWeek: 'Hari {day} dalam Pekan Suci',
	afterAshes: 'Hari {day} ses Rabu Abu',
	afterEpiphany: '{day} ses Penampakan Tuhan',
	christmasWeekday: '{day} Pekan Natal II',
	easterOctave: 'Hari {day} dalam Oktaf Paskah',
	christmasOctave: 'Hari {nth} Dalam Oktaf Natal'
};
