/**
 * The General Roman Calendar in Italian.
 *
 * Transcribed from the 3 calendars GCatholic publishes in Italian.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * All 218 of them, in the Calendar's own order.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `itTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const it: Record<string, string> = {
	'basil-gregory': 'Santi Basilio Magno e Gregorio Nazianzeno, vescovi e dottori della Chiesa',
	'holy-name-of-jesus': 'Santissimo Nome di Gesù',
	'raymond-of-penyafort': 'San Raimondo di Peñafort, sacerdote',
	hilary: 'Sant’Ilario di Poitiers, vescovo e dottore della Chiesa',
	'anthony-abbot': 'Sant’Antonio, abate',
	fabian: 'San Fabiano, papa e martire',
	sebastian: 'San Sebastiano, martire',
	agnes: 'Sant’Agnese, vergine e martire',
	'vincent-deacon': 'San Vincenzo, diacono e martire',
	'francis-de-sales': 'San Francesco di Sales, vescovo e dottore della Chiesa',
	'conversion-of-paul': 'Conversione di San Paolo, apostolo',
	'timothy-titus': 'Santi Timoteo e Tito, vescovi',
	'angela-merici': 'Sant’Angela Merici, vergine',
	'thomas-aquinas': 'San Tommaso d’Aquino, sacerdote e dottore della Chiesa',
	'john-bosco': 'San Giovanni Bosco, sacerdote',
	'presentation-of-the-lord': 'Presentazione del Signore',
	blaise: 'San Biagio, vescovo e martire',
	ansgar: 'Sant’Oscar, vescovo',
	agatha: 'Sant’Agata, vergine e martire',
	'paul-miki': 'Santi Paolo Miki e compagni, martiri',
	'jerome-emiliani': 'San Girolamo Emiliani',
	'josephine-bakhita': 'Santa Giuseppina Bakhita, vergine',
	scholastica: 'Santa Scolastica, vergine',
	'our-lady-of-lourdes': 'Nostra Signora di Lourdes',
	'cyril-methodius': 'Santi Cirillo, monaco, e Metodio, vescovo',
	'seven-founders': 'Santi sette fondatori dell’Ordine dei Servi di Maria',
	'peter-damian': 'San Pier Damiani, vescovo e dottore della Chiesa',
	'chair-of-peter': 'Cattedra di San Pietro, apostolo',
	polycarp: 'San Policarpo, vescovo e martire',
	'gregory-of-narek': 'San Gregorio di Narek, abate e dottore della Chiesa',
	casimir: 'San Casimiro',
	'perpetua-felicity': 'Sante Perpetua e Felicita, martiri',
	'john-of-god': 'San Giovanni di Dio, religioso',
	'frances-of-rome': 'Santa Francesca Romana, religiosa',
	patrick: 'San Patrizio, vescovo',
	'cyril-of-jerusalem': 'San Cirillo di Gerusalemme, vescovo e dottore della Chiesa',
	joseph: 'San Giuseppe, sposo della Beata Vergine Maria',
	turibius: 'San Turibio de Mogrovejo, vescovo',
	annunciation: 'Annunciazione del Signore',
	'francis-of-paola': 'San Francesco di Paola, eremita',
	isidore: 'Sant’Isidoro, vescovo e dottore della Chiesa',
	'vincent-ferrer': 'San Vincenzo Ferrer, sacerdote',
	'john-baptist-de-la-salle': 'San Giovanni Battista de La Salle, sacerdote',
	stanislaus: 'Santo Stanislao, vescovo e martire',
	'martin-i': 'San Martino I, papa e martire',
	anselm: 'Sant’Anselmo, vescovo e dottore della Chiesa',
	george: 'San Giorgio, martire',
	adalbert: 'Sant’Adalberto di Praga, vescovo e martire',
	fidelis: 'San Fedele di Sigmaringa, sacerdote e martire',
	mark: 'San Marco, evangelista',
	'peter-chanel': 'San Pietro Chanel, sacerdote e martire',
	'louis-de-montfort': 'San Luigi Maria Grignion de Montfort, sacerdote',
	'catherine-of-siena': 'Santa Caterina da Siena, vergine, dottore della Chiesa',
	'pius-v': 'San Pio V, papa',
	'joseph-the-worker': 'San Giuseppe, artigiano',
	athanasius: 'Sant’Atanasio, vescovo e dottore della Chiesa',
	'philip-james': 'Santi Filippo e Giacomo, apostoli',
	'john-of-avila': 'San Giovanni d’Avila, presbitero e dottore della Chiesa',
	'nereus-achilleus': 'Santi Nereo e Achilleo, martiri',
	pancras: 'San Pancrazio, martire',
	'our-lady-of-fatima': 'Nostra Signora di Fatima',
	matthias: 'San Mattia, apostolo',
	'john-i': 'San Giovanni I, papa e martire',
	'bernardine-of-siena': 'San Bernardino da Siena, sacerdote',
	'christopher-magallanes': 'Santi Cristoforo Magallanes, sacerdote, e compagni, martiri',
	'rita-of-cascia': 'Santa Rita da Cascia, religiosa',
	bede: 'San Beda il Venerabile, sacerdote e dottore della Chiesa',
	'gregory-vii': 'San Gregorio VII, papa',
	'mary-magdalene-de-pazzi': 'Santa Maria Maddalena de’ Pazzi, vergine',
	'philip-neri': 'San Filippo Neri, sacerdote',
	'augustine-of-canterbury': 'Sant’Agostino di Canterbury, vescovo',
	'paul-vi': 'San Paolo VI, papa',
	visitation: 'Visitazione della Beata Vergine Maria',
	justin: 'San Giustino, martire',
	'marcellinus-peter': 'Santi Marcellino e Pietro, martiri',
	'charles-lwanga': 'Santi Carlo Lwanga e compagni, martiri',
	boniface: 'San Bonifacio, vescovo e martire',
	norbert: 'San Norberto, vescovo',
	ephrem: 'Sant’Efrem il Siro, diacono e dottore della Chiesa',
	barnabas: 'San Barnaba, apostolo',
	'anthony-of-padua': 'Sant’Antonio da Padova, sacerdote e dottore della Chiesa',
	romuald: 'San Romualdo, abate',
	'aloysius-gonzaga': 'San Luigi Gonzaga, religioso',
	'paulinus-of-nola': 'San Paolino di Nola, vescovo',
	'fisher-more': 'Santi Giovanni Fisher, vescovo, e Tommaso Moro, martiri',
	'birth-of-john-the-baptist': 'Natività di San Giovanni Battista',
	'cyril-of-alexandria': 'San Cirillo di Alessandria, vescovo e dottore della Chiesa',
	irenaeus: 'Sant’Ireneo di Lione, vescovo, martire e dottore della Chiesa',
	'peter-and-paul': 'Santi Pietro e Paolo, apostoli',
	'first-martyrs-of-rome': 'Santi Primi martiri della Chiesa romana',
	'thomas-apostle': 'San Tommaso, apostolo',
	'elizabeth-of-portugal': 'Sant’Elisabetta di Portogallo',
	'anthony-zaccaria': 'Sant’Antonio Maria Zaccaria, sacerdote',
	'maria-goretti': 'Santa Maria Goretti, vergine e martire',
	'augustine-zhao-rong': 'Santi Agostino Zhao Rong, sacerdote, e compagni, martiri',
	benedict: 'San Benedetto, abate',
	henry: 'Sant’Enrico',
	camillus: 'San Camillo de Lellis, sacerdote',
	bonaventure: 'San Bonaventura, vescovo e dottore della Chiesa',
	'our-lady-of-mount-carmel': 'Beata Vergine Maria del Monte Carmelo',
	apollinaris: 'Sant’Apollinare, vescovo e martire',
	'lawrence-of-brindisi': 'San Lorenzo da Brindisi, sacerdote e dottore della Chiesa',
	'mary-magdalene': 'Santa Maria Maddalena',
	bridget: 'Santa Brigida di Svezia, religiosa',
	sharbel: 'San Charbel Makhlouf, sacerdote',
	james: 'San Giacomo, apostolo',
	'joachim-anne': 'Santi Gioacchino ed Anna, genitori della Beata Vergine Maria',
	'martha-mary-lazarus': 'Santi Marta, Maria e Lazzaro',
	'peter-chrysologus': 'San Pietro Crisologo, vescovo e dottore della Chiesa',
	'ignatius-of-loyola': 'Sant’Ignazio di Loyola, sacerdote',
	'alphonsus-liguori': 'Sant’Alfonso Maria de’ Liguori, vescovo e dottore della Chiesa',
	'eusebius-of-vercelli': 'Sant’Eusebio di Vercelli, vescovo',
	'peter-julian-eymard': 'San Pietro Giuliano Eymard, sacerdote',
	'john-vianney': 'San Giovanni Maria Vianney, sacerdote',
	'dedication-st-mary-major': 'Dedicazione della basilica di Santa Maria Maggiore',
	transfiguration: 'Trasfigurazione del Signore',
	'sixtus-ii': 'Santi Sisto II, papa, e compagni, martiri',
	cajetan: 'San Gaetano, sacerdote',
	dominic: 'San Domenico, sacerdote',
	'teresa-benedicta': 'Santa Teresa Benedetta della Croce, vergine e martire',
	lawrence: 'San Lorenzo, diacono e martire',
	clare: 'Santa Chiara, vergine',
	'jane-frances-de-chantal': 'Santa Giovanna Francesca de Chantal, religiosa',
	'pontian-hippolytus': 'Santi Ponziano, papa, e Ippolito, sacerdote, martiri',
	'maximilian-kolbe': 'San Massimiliano Maria Kolbe, sacerdote e martire',
	assumption: 'Assunzione della Beata Vergine Maria',
	'stephen-of-hungary': 'Santo Stefano d’Ungheria',
	'john-eudes': 'San Giovanni Eudes, sacerdote',
	bernard: 'San Bernardo, abate e dottore della Chiesa',
	'pius-x': 'San Pio X, papa',
	'queenship-of-mary': 'Beata Vergine Maria Regina',
	'rose-of-lima': 'Santa Rosa da Lima, vergine',
	bartholomew: 'San Bartolomeo, apostolo',
	louis: 'San Ludovico',
	'joseph-calasanz': 'San Giuseppe Calasanzio, sacerdote',
	monica: 'Santa Monica',
	augustine: 'Sant’Agostino, vescovo e dottore della Chiesa',
	'passion-of-john-the-baptist': 'Martirio di San Giovanni Battista',
	'gregory-the-great': 'San Gregorio Magno, papa e dottore della Chiesa',
	'teresa-of-calcutta': 'Santa Teresa di Calcutta, vergine',
	'nativity-of-mary': 'Natività della Beata Vergine Maria',
	'peter-claver': 'San Pietro Claver, sacerdote',
	'holy-name-of-mary': 'Santissimo Nome di Maria',
	'john-chrysostom': 'San Giovanni Crisostomo, vescovo e dottore della Chiesa',
	'exaltation-of-the-cross': 'Esaltazione della Santa Croce',
	'our-lady-of-sorrows': 'Beata Vergine Maria Addolorata',
	'cornelius-cyprian': 'Santi Cornelio, papa, e Cipriano, vescovo, martiri',
	'robert-bellarmine': 'San Roberto Bellarmino, vescovo e dottore della Chiesa',
	hildegard: 'Santa Ildegarda di Bingen, vergine e dottore della Chiesa',
	januarius: 'San Gennaro, vescovo e martire',
	'andrew-kim': 'Santi Andrea Kim Taegŏn, sacerdote, Paolo Chŏng Hasang e compagni, martiri',
	matthew: 'San Matteo, apostolo ed evangelista',
	'padre-pio': 'San Pio da Pietrelcina, sacerdote',
	'cosmas-damian': 'Santi Cosma e Damiano, martiri',
	'vincent-de-paul': 'San Vincenzo de’ Paoli, sacerdote',
	wenceslaus: 'San Venceslao, martire',
	'lawrence-ruiz': 'Santi Lorenzo Ruiz, sacerdote, e compagni, martiri',
	archangels: 'Santi Michele, Gabriele e Raffaele, Arcangeli',
	jerome: 'San Girolamo, sacerdote e dottore della Chiesa',
	'therese-of-lisieux': 'Santa Teresa del Bambino Gesù, vergine e dottore della Chiesa',
	'guardian-angels': 'Santi Angeli custodi',
	'francis-of-assisi': 'San Francesco d’Assisi, religioso',
	faustina: 'Santa Faustina Kowalska, vergine',
	bruno: 'San Bruno, sacerdote',
	'our-lady-of-the-rosary': 'Beata Vergine Maria del Rosario',
	denis: 'Santi Dionigi, vescovo, e compagni, martiri',
	'john-leonardi': 'San Giovanni Leonardi, sacerdote',
	'john-henry-newman': 'San John Henry Newman, sacerdote e dottore della Chiesa',
	'john-xxiii': 'San Giovanni XXIII, papa',
	'callistus-i': 'San Callisto I, papa e martire',
	'teresa-of-avila': 'Santa Teresa di Gesù, vergine e dottore della Chiesa',
	hedwig: 'Sant’Edvige, religiosa',
	'margaret-mary-alacoque': 'Santa Margherita Maria Alacoque, vergine',
	'ignatius-of-antioch': 'Sant’Ignazio di Antiochia, vescovo e martire',
	luke: 'San Luca, evangelista',
	'north-american-martyrs':
		'Santi Giovanni de Brébeuf, Isacco Jogues, sacerdoti, e compagni, martiri',
	'paul-of-the-cross': 'San Paolo della Croce, sacerdote',
	'john-paul-ii': 'San Giovanni Paolo II, papa',
	'john-of-capistrano': 'San Giovanni da Capestrano, sacerdote',
	'anthony-mary-claret': 'Sant’Antonio Maria Claret, vescovo',
	'simon-jude': 'Santi Simone e Giuda, apostoli',
	'all-saints': 'Tutti i Santi',
	'martin-de-porres': 'San Martino de Porres, religioso',
	'charles-borromeo': 'San Carlo Borromeo, vescovo',
	'dedication-of-the-lateran': 'Dedicazione della basilica Lateranense',
	'leo-the-great': 'San Leone Magno, papa e dottore della Chiesa',
	'martin-of-tours': 'San Martino di Tours, vescovo',
	josaphat: 'San Giosafat, vescovo e martire',
	'albert-the-great': 'Sant’Alberto Magno, vescovo e dottore della Chiesa',
	'margaret-of-scotland': 'Santa Margherita di Scozia',
	gertrude: 'Santa Gertrude, vergine',
	'elizabeth-of-hungary': 'Sant’Elisabetta d’Ungheria, religiosa',
	'dedication-of-peter-and-paul': 'Dedicazione delle basiliche dei Santi Pietro e Paolo, apostoli',
	'presentation-of-mary': 'Presentazione della Beata Vergine Maria',
	cecilia: 'Santa Cecilia, vergine e martire',
	'clement-i': 'San Clemente I, papa e martire',
	columban: 'San Colombano, abate',
	'andrew-dung-lac': 'Santi Andrea Dung-Lac, sacerdote, e compagni, martiri',
	'catherine-of-alexandria': 'Santa Caterina d’Alessandria, vergine e martire',
	andrew: 'Sant’Andrea, apostolo',
	'francis-xavier': 'San Francesco Saverio, sacerdote',
	'john-damascene': 'San Giovanni Damasceno, sacerdote e dottore della Chiesa',
	nicholas: 'San Nicola, vescovo',
	ambrose: 'Sant’Ambrogio, vescovo e dottore della Chiesa',
	'immaculate-conception': 'Immacolata Concezione della Beata Vergine Maria',
	'juan-diego': 'San Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Maria Santissima di Loreto',
	'damasus-i': 'San Damaso I, papa',
	'our-lady-of-guadalupe': 'Nostra Signora di Guadalupe',
	lucy: 'Santa Lucia, vergine e martire',
	'john-of-the-cross': 'San Giovanni della Croce, sacerdote e dottore della Chiesa',
	'peter-canisius': 'San Pietro Canisio, sacerdote e dottore della Chiesa',
	'john-of-kanty': 'San Giovanni da Kety, sacerdote',
	stephen: 'Santo Stefano, primo martire',
	'john-evangelist': 'San Giovanni, apostolo ed evangelista',
	'holy-innocents': 'Santi Innocenti, martiri',
	'thomas-becket': 'San Tommaso Becket, vescovo e martire',
	'sylvester-i': 'San Silvestro I, papa',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Natale del Signore',
	'holy-family': 'Santa Famiglia di Gesù, Maria e Giuseppe',
	'mary-mother-of-god': 'Maria Santissima Madre di Dio',
	'christmas-2-sunday': 'II Domenica di Natale',
	epiphany: 'Epifania del Signore',
	'baptism-of-the-lord': 'Battesimo del Signore',
	'ash-wednesday': 'Mercoledì delle Ceneri',
	'palm-sunday': 'Domenica delle Palme e della Passione del Signore',
	'holy-thursday': 'Giovedì Santo – Cena del Signore',
	'good-friday': 'Venerdì Santo – Passione del Signore',
	'holy-saturday': 'Sabato Santo',
	'easter-sunday': 'Domenica di Pasqua – Risurrezione del Signore',
	'easter-2-sunday': 'II Domenica di Pasqua (o della Divina Misericordia)',
	ascension: 'Ascensione del Signore',
	pentecost: 'Domenica di Pentecoste',
	trinity: 'Santissima Trinità',
	'corpus-christi': 'Santissimo Corpo e Sangue di Cristo',
	'sacred-heart': 'Sacratissimo Cuore di Gesù',
	'immaculate-heart': 'Cuore Immacolato della Beata Vergine Maria',
	'mary-mother-of-the-church': 'Beata Maria Vergine Madre della Chiesa',
	'christ-the-king': 'Nostro Signore Gesù Cristo Re dell’Universo'
};

/**
 * The Proper of Time in Italian, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const itTemporal: TemporalNames = {
	days: { 1: 'Lunedì', 2: 'Martedì', 3: 'Mercoledì', 4: 'Giovedì', 5: 'Venerdì', 6: 'Sabato' },
	weeks: {
		1: 'I',
		2: 'II',
		3: 'III',
		4: 'IV',
		5: 'V',
		6: 'VI',
		7: 'VII',
		8: 'VIII',
		9: 'IX',
		10: 'X',
		11: 'XI',
		12: 'XII',
		13: 'XIII',
		14: 'XIV',
		15: 'XV',
		16: 'XVI',
		17: 'XVII',
		18: 'XVIII',
		19: 'XIX',
		20: 'XX',
		21: 'XXI',
		22: 'XXII',
		23: 'XXIII',
		24: 'XXIV',
		25: 'XXV',
		26: 'XXVI',
		27: 'XXVII',
		28: 'XXVIII',
		29: 'XXIX',
		30: 'XXX',
		31: 'XXXI',
		32: 'XXXII',
		33: 'XXXIII',
		34: 'XXXIV'
	},
	octave: { 5: 'V', 6: 'VI', 7: 'VII' },
	sunday: {
		advent: '{week} Domenica di Avvento',
		lent: '{week} Domenica di Quaresima',
		easter: '{week} Domenica di Pasqua',
		ordinary: '{week} Domenica del Tempo Ordinario'
	},
	weekday: {
		advent: '{day} della {week} settimana di Avvento',
		lent: '{day} della {week} settimana di Quaresima',
		easter: '{day} della {week} settimana di Pasqua',
		ordinary: '{day} della {week} settimana del Tempo Ordinario'
	},
	holyWeek: '{day} Santo',
	afterAshes: '{day} dopo le Ceneri',
	afterEpiphany: '{day} dopo l’Epifania',
	christmasWeekday: '{day} del Tempo di Natale',
	easterOctave: '{day} fra l’Ottava di Pasqua',
	christmasOctave: '{nth} giorno fra l’Ottava di Natale'
};
