/**
 * The General Roman Calendar in Japanese.
 *
 * Transcribed from GCatholic's Japanese edition of Japan's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 211 of the Calendar's 218. The 7 absent are the ones Japan keeps someone
 * else on the day of — `blaise` among them — so this edition never prints
 * them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `jaTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const ja: Record<string, string> = {
	'basil-gregory': '聖バジリオ 聖グレゴリオ（ナジアンズ）司教教会博士',
	'holy-name-of-jesus': 'イエスのみ名',
	'raymond-of-penyafort': '聖ライムンド（ペニャフォル）司祭',
	hilary: '聖ヒラリオ司教教会博士',
	'anthony-abbot': '聖アントニオ修道院長',
	fabian: '聖ファビアノ教皇殉教者',
	sebastian: '聖セバスチアノ殉教者',
	agnes: '聖アグネスおとめ殉教者',
	'vincent-deacon': '聖ビンセンチオ助祭殉教者',
	'francis-de-sales': '聖フランシスコ・サレジオ司教教会博士',
	'conversion-of-paul': '聖パウロの回心',
	'timothy-titus': '聖テモテ 聖テトス司教',
	'angela-merici': '聖アンジェラ・メリチおとめ',
	'thomas-aquinas': '聖トマス・アクィナス司祭教会博士',
	'john-bosco': '聖ヨハネ・ボスコ司祭',
	'presentation-of-the-lord': '主の奉献',
	'jerome-emiliani': '聖ヒエロニモ・エミリアニ司祭',
	'josephine-bakhita': '聖ジュゼッピーナ・バキータおとめ',
	scholastica: '聖スコラスチカおとめ',
	'our-lady-of-lourdes': 'ルルドの聖母',
	'cyril-methodius': '聖チリロ隠世修道者 聖メトジオ司教',
	'seven-founders': '聖母のしもべ会7聖人',
	'peter-damian': '聖ペトロ・ダミアノ司教教会博士',
	'chair-of-peter': '聖ペトロの使徒座',
	polycarp: '聖ポリカルボ司教殉教者',
	'gregory-of-narek': '聖グレゴリオ（ナレク）修道院長教会博士',
	casimir: '聖カシミロ',
	'perpetua-felicity': '聖ペルペトゥア 聖フェリチタス殉教者',
	'john-of-god': '聖ヨハネ・ア・デオ修道者',
	'frances-of-rome': '聖フランシスカ（ローマ）修道女',
	'cyril-of-jerusalem': '聖チリロ（エルサレム）司教教会博士',
	joseph: '聖ヨセフ',
	turibius: '聖トゥリビオ（モングロベホ）司教',
	annunciation: '神のお告げ',
	'francis-of-paola': '聖フランシスコ（パオラ）隠世修道士',
	isidore: '聖イシドロ司教教会博士',
	'vincent-ferrer': '聖ビンセンチオ・フェレル司祭',
	'john-baptist-de-la-salle': '聖ヨハネ・バプティスタ（ラ・サール）司祭',
	stanislaus: '聖スタニスラオ司教殉教者',
	'martin-i': '聖マルチノ一世教皇殉教者',
	anselm: '聖アンセルモ司教教会博士',
	george: '聖ジェオルジオ殉教者',
	adalbert: '聖アダルベルト司教殉教者',
	fidelis: '聖フィデリス（ジグマリンゲン）司祭殉教者',
	mark: '聖マルコ福音記者',
	'peter-chanel': '聖ペトロ・シャネル司祭殉教者',
	'louis-de-montfort': '聖ルイ・マリー・グリニヨン・ド・モンフォール司祭',
	'catherine-of-siena': '聖カタリナ（シエナ）おとめ教会博士',
	'pius-v': '聖ピオ五世教皇',
	'joseph-the-worker': '労働者聖ヨセフ',
	athanasius: '聖アタナシオ司教教会博士',
	'philip-james': '聖フィリポ 聖ヤコブ使徒',
	'john-of-avila': '聖ヨハネ（アビラ）司祭教会博士',
	'nereus-achilleus': '聖ネレオ 聖アキレオ殉教者',
	pancras: '聖パンクラチオ殉教者',
	'our-lady-of-fatima': 'ファチマの聖母',
	matthias: '聖マチア使徒',
	'john-i': '聖ヨハネ一世教皇殉教者',
	'bernardine-of-siena': '聖ベルナルディノ（シエナ）司祭',
	'christopher-magallanes': '聖クリストバル・マガヤネス司祭と同志殉教者',
	'rita-of-cascia': '聖リタ（カシャ）修道女',
	bede: '聖ベダ司教教会博士',
	'gregory-vii': '聖グレゴリオ七世教皇',
	'mary-magdalene-de-pazzi': '聖マリア・マグダレナ（パッジ）おとめ',
	'philip-neri': '聖フィリポ・ネリ司祭',
	'augustine-of-canterbury': '聖アウグスチヌス（カンタベリー）司教',
	'paul-vi': '聖パウロ六世教皇',
	visitation: '聖母の訪問',
	justin: '聖ユスチノ殉教者',
	'marcellinus-peter': '聖マルチェリノ 聖ペトロ殉教者',
	'charles-lwanga': '聖カロロ・ルワンガと同志殉教者',
	boniface: '聖ボニファチオ司教殉教者',
	norbert: '聖ノルベルト司教',
	ephrem: '聖エフレム助祭教会博士',
	barnabas: '聖バルナバ使徒',
	'anthony-of-padua': '聖アントニオ（パドバ）司祭教会博士',
	romuald: '聖ロムアルド修道院長',
	'aloysius-gonzaga': '聖アロイジオ・ゴンザカ修道者',
	'paulinus-of-nola': '聖パウリノ（ノラ）司教',
	'fisher-more': '聖ヨハネ・フィッシャー司教 聖トマス・モア殉教者',
	'birth-of-john-the-baptist': '洗礼者聖ヨハネの誕生',
	'cyril-of-alexandria': '聖チリロ（アレキサンドリア）司教教会博士',
	irenaeus: '聖イレネオ司教殉教者教会博士',
	'peter-and-paul': '聖ペトロ 聖パウロ使徒',
	'first-martyrs-of-rome': 'ローマ教会最初の殉教者たち',
	'thomas-apostle': '聖トマ使徒',
	'elizabeth-of-portugal': '聖エリザベト（ポルトガル）',
	'anthony-zaccaria': '聖アントニオ・マリア・ザカリア司祭',
	'maria-goretti': '聖マリア・ゴレッティおとめ殉教者',
	'augustine-zhao-rong': '聖アウグスチノ・チャオ・ロン司祭と同志殉教者',
	benedict: '聖ベネディクト修道院長',
	henry: '聖ハインリッヒ',
	camillus: '聖カミロ（レリス）司祭',
	bonaventure: '聖ボナベントゥラ司教教会博士',
	'our-lady-of-mount-carmel': 'カルメル山の聖母',
	apollinaris: '聖アポリナーリス司教殉教者',
	'lawrence-of-brindisi': '聖ラウレンチオ（ブリンディジ）司祭教会博士',
	'mary-magdalene': '聖マリア（マグダラ）',
	bridget: '聖ビルジッタ修道女',
	sharbel: '聖シャーベル・マクルーフ司祭',
	james: '聖ヤコブ使徒',
	'joachim-anne': '聖マリアの両親 聖ヨアキムと聖アンナ',
	'martha-mary-lazarus': '聖マルタ 聖マリア 聖ラザロ',
	'peter-chrysologus': '聖ペトロ・クリソロゴ司教教会博士',
	'ignatius-of-loyola': '聖イグナチオ（ロヨラ）司祭',
	'alphonsus-liguori': '聖アルフォンソ（リゴリ)司教教会博士',
	'eusebius-of-vercelli': '聖エウセビオ（ベルチェリ）司教',
	'peter-julian-eymard': '聖ペトロ・ユリアノ・エイマール司祭',
	'john-vianney': '聖ヨハネ・マリア・ビアンネ司祭',
	'dedication-st-mary-major': '聖マリア教会の献堂',
	transfiguration: '主の変容',
	'sixtus-ii': '聖シスト二世教皇と同志殉教者',
	cajetan: '聖カエタノ司祭',
	dominic: '聖ドミニコ司祭',
	'teresa-benedicta': '聖テレサ・ベネディクタ（十字架の）おとめ殉教者',
	lawrence: '聖ラウレンチオ助祭殉教者',
	clare: '聖クララおとめ',
	'jane-frances-de-chantal': '聖ヨハンナ・フランシスカ・ド・シャンタル修道女',
	'pontian-hippolytus': '聖ポンチアノ教皇 聖ヒッポリト司祭殉教者',
	'maximilian-kolbe': '聖マキシミリアノ・マリア・コルベ司祭殉教者',
	assumption: '聖母の被昇天',
	'stephen-of-hungary': '聖ステファノ（ハンガリー）',
	'john-eudes': '聖ヨハネ・ユード司祭',
	bernard: '聖ベルナルド修道院長教会博士',
	'pius-x': '聖ピオ十世教皇',
	'queenship-of-mary': '天の元后聖マリア',
	'rose-of-lima': '聖ローザ（リマ）おとめ',
	bartholomew: '聖バルトロマイ使徒',
	louis: '聖ルイ',
	'joseph-calasanz': '聖ヨセフ・カラサンス司祭',
	monica: '聖モニカ',
	augustine: '聖アウグスチヌス司教教会博士',
	'passion-of-john-the-baptist': '洗礼者聖ヨハネの殉教',
	'gregory-the-great': '聖グレゴリオ一世教皇教会博士',
	'teresa-of-calcutta': 'コルカタの聖テレサおとめ',
	'nativity-of-mary': '聖マリアの誕生',
	'peter-claver': '聖ペトロ・クラベル司祭',
	'holy-name-of-mary': 'マリアのみ名',
	'john-chrysostom': '聖ヨハネ・クリゾストモ司教教会博士',
	'exaltation-of-the-cross': '十字架称賛',
	'our-lady-of-sorrows': '悲しみの聖母',
	'cornelius-cyprian': '聖コルネリオ教皇 聖チプリアノ司教殉教者',
	'robert-bellarmine': '聖ロベルト・ベラルミノ司教教会博士',
	hildegard: '聖ヒルデガルト（ビンゲン）おとめ教会博士',
	januarius: '聖ヤヌアリオ司教殉教者',
	'andrew-kim': '聖アンデレ金司祭と同志殉教者',
	matthew: '聖マタイ使徒福音記者',
	'padre-pio': '聖ピオ（ピエトレルチーナ）司祭',
	'cosmas-damian': '聖コスマ 聖ダミアノ殉教者',
	'vincent-de-paul': '聖ビンセンチオ・ア・パウロ司祭',
	archangels: '聖ミカエル 聖ガブリエル 聖ラファエル大天使',
	jerome: '聖ヒエロニモ司祭教会博士',
	'therese-of-lisieux': '聖テレジア（幼いイエスの）おとめ教会博士',
	'guardian-angels': '守護の天使',
	'francis-of-assisi': '聖フランシスコ（アシジ）修道者',
	faustina: '聖ファウスティナ・コヴァルスカおとめ',
	bruno: '聖ブルーノ司祭',
	'our-lady-of-the-rosary': 'ロザリオの聖母',
	denis: '聖ディオニジオ司教と同志殉教者',
	'john-leonardi': '聖ヨハネ・レオナルディ司祭',
	'john-henry-newman': '聖ジョン・ヘンリー・ニューマン司祭教会博士',
	'john-xxiii': '聖ヨハネ二十三世教皇',
	'callistus-i': '聖カリスト一世教皇殉教者',
	'teresa-of-avila': '聖テレジア（イエスの）おとめ教会博士',
	hedwig: '聖ヘドビッヒ修道女',
	'margaret-mary-alacoque': '聖マルガリタ・マリア・アラコクおとめ',
	'ignatius-of-antioch': '聖イグナチオ（アンチオケ）司教殉教者',
	luke: '聖ルカ福音記者',
	'north-american-martyrs': '聖ヨハネ・ブレブーフ 聖イザーク・ジョーグ司祭と同志殉教者',
	'paul-of-the-cross': '聖パウロ（十字架の）司祭',
	'john-paul-ii': '聖ヨハネ・パウロ二世教皇',
	'john-of-capistrano': '聖ヨハネ（カペストラノ）司祭',
	'anthony-mary-claret': '聖アントニオ・マリア・クラレ司教',
	'simon-jude': '聖シモン 聖ユダ使徒',
	'all-saints': '諸聖人',
	'martin-de-porres': '聖マルチノ・デ・ポレス修道者',
	'charles-borromeo': '聖カロロ・ボロメオ司教',
	'dedication-of-the-lateran': 'ラテラン教会の献堂',
	'leo-the-great': '聖レオ一世教皇教会博士',
	'martin-of-tours': '聖マルチノ（ツール）司教',
	josaphat: '聖ヨサファト司教殉教者',
	'albert-the-great': '聖アルベルト司教教会博士',
	'margaret-of-scotland': '聖マルガリタ（スコットランド）',
	gertrude: '聖ゲルトルードおとめ',
	'elizabeth-of-hungary': '聖エリザベト（ハンガリー）修道女',
	'dedication-of-peter-and-paul': '聖ペトロ教会と聖パウロ教会の献堂',
	'presentation-of-mary': '聖マリアの奉献',
	cecilia: '聖セシリアおとめ殉教者',
	'clement-i': '聖クレメンス一世教皇殉教者',
	columban: '聖コロンバン修道院長',
	'andrew-dung-lac': '聖アンデレ・ジュン・ラク司祭と同志殉教者',
	'catherine-of-alexandria': '聖カタリナ（アレキサンドリア）おとめ殉教者',
	andrew: '聖アンデレ使徒',
	'francis-xavier': '聖フランシスコ・ザビエル司祭',
	'john-damascene': '聖ヨハネ（ダマスコ）司祭教会博士',
	nicholas: '聖ニコラオ司教',
	ambrose: '聖アンブロジオ司教教会博士',
	'immaculate-conception': '無原罪の聖マリア',
	'juan-diego': '聖ホァン・ディエゴ・クアウトラトアツィン',
	'our-lady-of-loreto': 'ロレトの聖母マリア',
	'damasus-i': '聖ダマソ一世教皇',
	'our-lady-of-guadalupe': 'グアダルペの聖母',
	lucy: '聖ルチアおとめ殉教者',
	'john-of-the-cross': '聖ヨハネ（十字架の）司祭教会博士',
	'peter-canisius': '聖ペトロ・カニジオ司祭教会博士',
	'john-of-kanty': '聖ヨハネ（ケンティ）司祭',
	stephen: '聖ステファノ殉教者',
	'john-evangelist': '聖ヨハネ使徒福音記者',
	'holy-innocents': '幼児殉教者',
	'thomas-becket': '聖トマス・ベケット司教殉教者',
	'sylvester-i': '聖シルベストロ一世教皇',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: '主の降誕',
	'holy-family': '聖家族',
	'mary-mother-of-god': '神の母聖マリア',
	epiphany: '主の公現',
	'baptism-of-the-lord': '主の洗礼',
	'ash-wednesday': '灰の水曜日',
	'palm-sunday': '受難の主日（枝の主日）',
	'holy-thursday': '聖木曜日（主の晩さん）',
	'good-friday': '聖金曜日（主の受難）',
	'holy-saturday': '聖土曜日',
	'easter-sunday': '復活の主日',
	'easter-2-sunday': '復活節第2主日（神のいつくしみの主日）',
	ascension: '主の昇天',
	pentecost: '聖霊降臨の主日',
	trinity: '三位一体の主日',
	'corpus-christi': 'キリストの聖体',
	'sacred-heart': 'イエスのみ心',
	'immaculate-heart': '聖母のみ心',
	'mary-mother-of-the-church': '教会の母聖マリア',
	'christ-the-king': '王であるキリスト'
};

/**
 * The Proper of Time in Japanese, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const jaTemporal: TemporalNames = {
	days: { 1: '月', 2: '火', 3: '水', 4: '木', 5: '金', 6: '土' },
	weeks: {
		1: '1',
		2: '2',
		3: '3',
		4: '4',
		5: '5',
		6: '6',
		7: '7',
		8: '8',
		9: '9',
		10: '10',
		11: '11',
		12: '12',
		13: '13',
		14: '14',
		15: '15',
		16: '16',
		17: '17',
		18: '18',
		19: '19',
		20: '20',
		21: '21',
		22: '22',
		23: '23',
		24: '24',
		25: '25',
		26: '26',
		27: '27',
		28: '28',
		29: '29',
		30: '30',
		31: '31',
		32: '32',
		33: '33',
		34: '34'
	},
	octave: { 5: '5', 6: '6', 7: '7' },
	sunday: {
		advent: '待降節第{week}主日',
		lent: '四旬節第{week}主日',
		easter: '復活節第{week}主日',
		ordinary: '年間第{week}主日'
	},
	weekday: {
		advent: '待降節第{week}{day}曜日',
		lent: '四旬節第{week}{day}曜日',
		easter: '復活節第{week}{day}曜日',
		ordinary: '年間第{week}{day}曜日'
	},
	holyWeek: '受難の{day}曜日',
	afterAshes: '灰の水曜日後の{day}曜日',
	afterEpiphany: '公現後の{day}曜日',
	christmasWeekday: '公現前の{day}曜日',
	easterOctave: '復活の{day}曜日',
	christmasOctave: '主の降誕第{nth}日'
};
