/**
 * The General Roman Calendar in Korean.
 *
 * Transcribed from GCatholic's Korean edition of Korea's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 217 of the Calendar's 218. The one absent is `justin`, which Korea keeps
 * someone else on the day of, so this edition never prints it and it goes on
 * falling back to English — which is what `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `koTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const ko: Record<string, string> = {
	'basil-gregory': '성 대 바실리오와 나지안조의 성 그레고리오 주교 학자',
	'holy-name-of-jesus': '예수 성명',
	'raymond-of-penyafort': '페냐포르트 성 라이문도 사제',
	hilary: '성 힐라리오 주교 학자',
	'anthony-abbot': '성 안토니오 아빠스',
	fabian: '성 파비아노 교황 순교자',
	sebastian: '성 세바스티아노 순교자',
	agnes: '성녀 아녜스 동정 순교자',
	'vincent-deacon': '성 빈첸시오 부제 순교자',
	'francis-de-sales': '성 프란치스코 살레시오 주교 학자',
	'conversion-of-paul': '성 바오로 사도의 회심',
	'timothy-titus': '성 티모테오와 성 티토 주교',
	'angela-merici': '성녀 안젤라 메리치 동정',
	'thomas-aquinas': '성 토마스 아퀴나스 사제 학자',
	'john-bosco': '성 요한 보스코 사제',
	'presentation-of-the-lord': '주님 봉헌',
	blaise: '성 블라시오 주교 순교자',
	ansgar: '성 안스가리오 주교',
	agatha: '성녀 아가타 동정 순교자',
	'paul-miki': '성 바오로 미키와 동료 순교자들',
	'jerome-emiliani': '성 예로니모 에밀리아니 사제',
	'josephine-bakhita': '성녀 요세피나 바키타 동정',
	scholastica: '성녀 스콜라스티카 동정',
	'our-lady-of-lourdes': '루르드의 복되신 동정 마리아',
	'cyril-methodius': '성 치릴로 수도자와 성 메토디오 주교',
	'seven-founders': '성모의 종 수도회 창설자 7성인',
	'peter-damian': '성 베드로 다미아노 주교 학자',
	'chair-of-peter': '성 베드로 사도좌',
	polycarp: '성 폴리카르포 주교 순교자',
	'gregory-of-narek': '나렉의 성 그레고리오 아빠스 학자',
	casimir: '성 가시미로',
	'perpetua-felicity': '성녀 페르페투아와 성녀 펠리치타스 순교자',
	'john-of-god': '성 요한 수도자',
	'frances-of-rome': '성녀 프란치스카 수도자',
	patrick: '성 파트리치오 주교',
	'cyril-of-jerusalem': '성 치릴로 주교 학자',
	joseph: '복되신 동정 마리아의 배필 성 요셉',
	turibius: '성 투리비오 데 모그로베호 주교',
	annunciation: '주님 탄생 예고',
	'francis-of-paola': '성 프란치스코 은수자',
	isidore: '성 이시도로 주교 학자',
	'vincent-ferrer': '성 빈첸시오 페레르 사제',
	'john-baptist-de-la-salle': '성 요한 밥티스타 드 라 살 사제',
	stanislaus: '성 스타니슬라오 주교 순교자',
	'martin-i': '성 마르티노 1세 교황 순교자',
	anselm: '성 안셀모 주교 학자',
	george: '성 제오르지오 순교자',
	adalbert: '성 아달베르토 주교 순교자',
	fidelis: '성 피델리스 사제 순교자',
	mark: '성 마르코 복음사가',
	'peter-chanel': '성 베드로 샤넬 사제 순교자',
	'louis-de-montfort': '성 루도비코 마리아 그리뇽 드 몽포르 사제',
	'catherine-of-siena': '시에나의 성녀 가타리나 동정 학자',
	'pius-v': '성 비오 5세 교황',
	'joseph-the-worker': '노동자 성 요셉',
	athanasius: '성 아타나시오 주교 학자',
	'philip-james': '성 필립보와 성 야고보 사도',
	'john-of-avila': '아빌라의 성 요한 사제 학자',
	'nereus-achilleus': '성 네레오와 성 아킬레오 순교자',
	pancras: '성 판크라시오 순교자',
	'our-lady-of-fatima': '파티마의 복되신 동정 마리아',
	matthias: '성 마티아 사도',
	'john-i': '성 요한 1세 교황 순교자',
	'bernardine-of-siena': '시에나의 성 베르나르디노 사제',
	'christopher-magallanes': '성 크리스토포로 마가야네스 사제와 동료 순교자들',
	'rita-of-cascia': '카시아의 성녀 리타 수도자',
	bede: '성 베다 사제 학자',
	'gregory-vii': '성 그레고리오 7세 교황',
	'mary-magdalene-de-pazzi': '성녀 마리아 막달레나 데 파치 동정',
	'philip-neri': '성 필립보 네리 사제',
	'augustine-of-canterbury': '캔터베리의 성 아우구스티노 주교',
	'paul-vi': '성 바오로 6세 교황',
	visitation: '복되신 동정 마리아의 방문',
	'marcellinus-peter': '성 베드로와 성 마르첼리노 순교자',
	'charles-lwanga': '성 가롤로 르왕가와 동료 순교자들',
	boniface: '성 보니파시오 주교 순교자',
	norbert: '성 노르베르토 주교',
	ephrem: '성 에프렘 부제 학자',
	barnabas: '성 바르나바 사도',
	'anthony-of-padua': '파도바의 성 안토니오 사제 학자',
	romuald: '성 로무알도 아빠스',
	'aloysius-gonzaga': '성 알로이시오 곤자가 수도자',
	'paulinus-of-nola': '성 바울리노 주교',
	'fisher-more': '성 요한 피셔 주교와 성 토마스 모어 순교자',
	'birth-of-john-the-baptist': '성 요한 세례자 탄생',
	'cyril-of-alexandria': '알렉산드리아의 성 치릴로 주교 학자',
	irenaeus: '성 이레네오 주교 순교자 학자',
	'peter-and-paul': '성 베드로와 성 바오로 사도',
	'first-martyrs-of-rome': '로마 교회의 초기 순교자들',
	'thomas-apostle': '성 토마스 사도',
	'elizabeth-of-portugal': '포르투갈의 성녀 엘리사벳',
	'anthony-zaccaria': '성 안토니오 마리아 즈카르야 사제',
	'maria-goretti': '성녀 마리아 고레티 동정 순교자',
	'augustine-zhao-rong': '성 아우구스티노 자오룽 사제와 동료 순교자들',
	benedict: '성 베네딕토 아빠스',
	henry: '성 헨리코',
	camillus: '성 가밀로 데 렐리스 사제',
	bonaventure: '성 보나벤투라 주교 학자',
	'our-lady-of-mount-carmel': '카르멜 산의 복되신 동정 마리아',
	apollinaris: '성 아폴리나리오 주교 순교자',
	'lawrence-of-brindisi': '브린디시의 성 라우렌시오 사제 학자',
	'mary-magdalene': '성녀 마리아 막달레나',
	bridget: '성녀 비르지타 수도자',
	sharbel: '성 사르벨리오 마클루프 사제',
	james: '성 야고보 사도',
	'joachim-anne': '복되신 동정 마리아의 부모 성 요아킴과 성녀 안나',
	'martha-mary-lazarus': '성녀 마르타 성녀 마리아 성 라자루스',
	'peter-chrysologus': '성 베드로 크리솔로고 주교 학자',
	'ignatius-of-loyola': '성 이냐시오 데 로욜라 사제',
	'alphonsus-liguori': '성 알폰소 마리아 데 리구오리 주교 학자',
	'eusebius-of-vercelli': '성 에우세비오 주교',
	'peter-julian-eymard': '성 베드로 율리아노 사제',
	'john-vianney': '성 요한 마리아 비안네 사제',
	'dedication-st-mary-major': '성모 대성전 봉헌',
	transfiguration: '주님의 거룩한 변모',
	'sixtus-ii': '성 식스토 2세 교황과 동료 순교자들',
	cajetan: '성 가예타노 사제',
	dominic: '성 도미니코 사제',
	'teresa-benedicta': '십자가의 성녀 데레사 베네딕타 동정 순교자',
	lawrence: '성 라우렌시오 부제 순교자',
	clare: '성녀 클라라 동정',
	'jane-frances-de-chantal': '성녀 요안나 프란치스카 드 샹탈 수도자',
	'pontian-hippolytus': '성 폰시아노 교황과 성 히폴리토 사제 순교자',
	'maximilian-kolbe': '성 막시밀리아노 마리아 콜베 사제 순교자',
	assumption: '성모 승천',
	'stephen-of-hungary': '헝가리의 성 스테파노',
	'john-eudes': '성 요한 에우데스 사제',
	bernard: '성 베르나르도 아빠스 학자',
	'pius-x': '성 비오 10세 교황',
	'queenship-of-mary': '복되신 동정 마리아 모후',
	'rose-of-lima': '리마의 성녀 로사 동정',
	bartholomew: '성 바르톨로메오 사도',
	louis: '성 루도비코',
	'joseph-calasanz': '성 요셉 데 갈라산즈 사제',
	monica: '성녀 모니카',
	augustine: '성 아우구스티노 주교 학자',
	'passion-of-john-the-baptist': '성 요한 세례자의 수난',
	'gregory-the-great': '성 대 그레고리오 교황 학자',
	'teresa-of-calcutta': '콜카타의 성녀 테레사 동정',
	'nativity-of-mary': '복되신 동정 마리아 탄생',
	'peter-claver': '성 베드로 클라베르 사제',
	'holy-name-of-mary': '복되신 동정 마리아 성명',
	'john-chrysostom': '성 요한 크리소스토모 주교 학자',
	'exaltation-of-the-cross': '성 십자가 현양',
	'our-lady-of-sorrows': '고통의 성모 마리아',
	'cornelius-cyprian': '성 고르넬리오 교황과 성 치프리아노 주교 순교자',
	'robert-bellarmine': '성 로베르토 벨라르미노 주교 학자',
	hildegard: '빙엔의 성녀 힐데가르트 동정 학자',
	januarius: '성 야누아리오 주교 순교자',
	'andrew-kim': '성 김대건 안드레아 사제와 성 정하상 바오로와 동료 순교자들',
	matthew: '성 마태오 사도 복음사가',
	'padre-pio': '피에트렐치나의 성 비오 사제',
	'cosmas-damian': '성 고스마와 성 다미아노 순교자',
	'vincent-de-paul': '성 빈첸시오 드 폴 사제',
	wenceslaus: '성 벤체슬라오 순교자',
	'lawrence-ruiz': '성 라우렌시오 루이스와 동료 순교자들',
	archangels: '성 미카엘, 가브리엘, 라파엘 대천사',
	jerome: '성 예로니모 사제 학자',
	'therese-of-lisieux': '아기 예수의 성녀 데레사 동정 학자',
	'guardian-angels': '수호천사',
	'francis-of-assisi': '아시시의 성 프란치스코',
	faustina: '성녀 파우스티나 코발스카 동정',
	bruno: '성 브루노 사제',
	'our-lady-of-the-rosary': '묵주 기도의 복되신 동정 마리아',
	denis: '성 디오니시오 주교와 동료 순교자들',
	'john-leonardi': '성 요한 레오나르디 사제',
	'john-henry-newman': '성 존 헨리 뉴먼 사제 학자',
	'john-xxiii': '성 요한 23세 교황',
	'callistus-i': '성 갈리스토 1세 교황 순교자',
	'teresa-of-avila': '예수의 성녀 데레사 동정 학자',
	hedwig: '성녀 헤드비히 수도자',
	'margaret-mary-alacoque': '성녀 마르가리타 마리아 알라코크 동정',
	'ignatius-of-antioch': '안티오키아의 성 이냐시오 주교 순교자',
	luke: '성 루카 복음사가',
	'north-american-martyrs': '성 요한 드 브레뵈프 사제와 동료 순교자들',
	'paul-of-the-cross': '십자가의 성 바오로 사제',
	'john-paul-ii': '성 요한 바오로 2세 교황',
	'john-of-capistrano': '카페스트라노의 성 요한 사제',
	'anthony-mary-claret': '성 안토니오 마리아 클라렛 주교',
	'simon-jude': '성 시몬과 성 유다 사도',
	'all-saints': '모든 성인',
	'martin-de-porres': '성 마르티노 데 포레스 수도자',
	'charles-borromeo': '성 가롤로 보로메오 주교',
	'dedication-of-the-lateran': '라테라노 대성전 봉헌',
	'leo-the-great': '성 대 레오 교황 학자',
	'martin-of-tours': '투르의 성 마르티노 주교',
	josaphat: '성 요사팟 주교 순교자',
	'albert-the-great': '성 대 알베르토 주교 학자',
	'margaret-of-scotland': '스코틀랜드의 성녀 마르가리타',
	gertrude: '성녀 제르트루다 동정',
	'elizabeth-of-hungary': '헝가리의 성녀 엘리사벳 수도자',
	'dedication-of-peter-and-paul': '성 베드로 대성전과 성 바오로 대성전 봉헌',
	'presentation-of-mary': '복되신 동정 마리아의 자헌',
	cecilia: '성녀 체칠리아 동정 순교자',
	'clement-i': '성 클레멘스 1세 교황 순교자',
	columban: '성 골룸바노 아빠스',
	'andrew-dung-lac': '성 안드레아 둥락 사제와 동료 순교자들',
	'catherine-of-alexandria': '알렉산드리아의 성녀 가타리나 동정 순교자',
	andrew: '성 안드레아 사도',
	'francis-xavier': '성 프란치스코 하비에르 사제',
	'john-damascene': '다마스쿠스의 성 요한 사제 학자',
	nicholas: '성 니콜라오 주교',
	ambrose: '성 암브로시오 주교 학자',
	'immaculate-conception': '한국 교회의 수호자 원죄 없이 잉태되신 복되신 동정 마리아',
	'juan-diego': '쿠아우티틀란의 성 후안 디에고',
	'our-lady-of-loreto': '로레토 복되신 동정 마리아',
	'damasus-i': '성 다마소 1세 교황',
	'our-lady-of-guadalupe': '과달루페의 복되신 동정 마리아',
	lucy: '성녀 루치아 동정 순교자',
	'john-of-the-cross': '십자가의 성 요한 사제 학자',
	'peter-canisius': '성 베드로 가니시오 사제 학자',
	'john-of-kanty': '켕티의 성 요한 사제',
	stephen: '성 스테파노 첫 순교자',
	'john-evangelist': '성 요한 사도 복음사가',
	'holy-innocents': '죄 없는 아기 순교자들',
	'thomas-becket': '성 토마스 베케트 주교 순교자',
	'sylvester-i': '성 실베스테르 1세 교황',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: '주님 성탄',
	'holy-family': '예수, 마리아, 요셉의 성가정',
	'mary-mother-of-god': '천주의 성모 마리아',
	epiphany: '주님 공현 대축일',
	'baptism-of-the-lord': '주님 세례 축일',
	'ash-wednesday': '재의 수요일',
	'palm-sunday': '주님 수난 성지주일',
	'holy-thursday': '주님 만찬 성목요일',
	'good-friday': '주님 수난 성금요일',
	'holy-saturday': '성토요일',
	'easter-sunday': '주님 부활 대축일',
	'easter-2-sunday': '부활 제2주일 (하느님의 자비 주일)',
	ascension: '주님 승천',
	pentecost: '성령 강림',
	trinity: '지극히 거룩하신 삼위일체',
	'corpus-christi': '지극히 거룩하신 그리스도의 성체 성혈',
	'sacred-heart': '지극히 거룩하신 예수 성심',
	'immaculate-heart': '티 없이 깨끗하신 성모 성심',
	'mary-mother-of-the-church': '교회의 어머니 복되신 동정 마리아',
	'christ-the-king': '온 누리의 임금이신 우리 주 예수 그리스도 왕'
};

/**
 * The Proper of Time in Korean, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const koTemporal: TemporalNames = {
	days: { 1: '월', 2: '화', 3: '수', 4: '목', 5: '금', 6: '토' },
	weeks: {
		1: '1',
		2: '2',
		3: '3',
		4: '4',
		5: '5',
		6: '6',
		7: '7',
		8: '8',
		9: '9',
		10: '10',
		11: '11',
		12: '12',
		13: '13',
		14: '14',
		15: '15',
		16: '16',
		17: '17',
		18: '18',
		19: '19',
		20: '20',
		21: '21',
		22: '22',
		23: '23',
		24: '24',
		25: '25',
		26: '26',
		27: '27',
		28: '28',
		29: '29',
		30: '30',
		31: '31',
		32: '32',
		33: '33',
		34: '34'
	},
	octave: { 5: '5', 6: '6', 7: '7' },
	sunday: {
		advent: '대림 제{week}주일',
		lent: '사순 제{week}주일',
		easter: '부활 제{week}주일',
		ordinary: '연중 제{week}주일'
	},
	weekday: {
		advent: '대림 제{week}주간 {day}요일',
		lent: '사순 제{week}주간 {day}요일',
		easter: '부활 제{week}주간 {day}요일',
		ordinary: '연중 제{week}주간 {day}요일'
	},
	holyWeek: '성주간 {day}요일',
	afterAshes: '재의 예식 다음 {day}요일',
	afterEpiphany: '주님 공현 대축일 후 {day}요일',
	christmasWeekday: '주님 공현 대축일 전 {day}요일',
	easterOctave: '부활 팔일 축제 {day}요일',
	christmasOctave: '성탄 팔일 축제 제{nth}일'
};
