/**
 * The General Roman Calendar in Lithuanian.
 *
 * Transcribed from GCatholic's Lithuanian edition of Lithuania's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 212 of the Calendar's 218. The 6 absent are the ones Lithuania keeps
 * someone else on the day of — `angela-merici` among them — so this edition
 * never prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `ltTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const lt: Record<string, string> = {
	'basil-gregory': 'Šv. Bazilijus Didysis ir Grigalius Nazianzietis, vyskupai, Bažnyčios mokytojai',
	'holy-name-of-jesus': 'Švč. Jėzaus Vardas',
	'raymond-of-penyafort': 'Šv. Raimundas Penjafortietis, kunigas',
	hilary: 'Šv. Hiliaras, vyskupas, Bažnyčios mokytojas',
	'anthony-abbot': 'Šv. Antanas, abatas',
	fabian: 'Šv. Fabijonas, popiežius, kankinys',
	sebastian: 'Šv. Sebastijonas, kankinys',
	agnes: 'Šv. Agnietė, mergelė, kankinė',
	'vincent-deacon': 'Šv. Vincentas, diakonas, kankinys',
	'francis-de-sales': 'Šv. Pranciškus Salezas, vyskupas, Bažnyčios mokytojas',
	'conversion-of-paul': 'Šv. Pauliaus, apaštalo, Atsivertimas',
	'timothy-titus': 'Šv. Timotiejus ir Titas, vyskupai',
	'thomas-aquinas': 'Šv. Tomas Akvinietis, kunigas, Bažnyčios mokytojas',
	'john-bosco': 'Šv. Jonas Boskas, kunigas',
	'presentation-of-the-lord': 'Kristaus Paaukojimas',
	blaise: 'Šv. Blažiejus, vyskupas, kankinys',
	ansgar: 'Šv. Ansgaras, vyskupas',
	agatha: 'Šv. Agota, mergelė, kankinė',
	'paul-miki': 'Šv. Paulius Mikis ir jo draugai, kankiniai',
	'jerome-emiliani': 'Šv. Jeronimas Emiljanis',
	'josephine-bakhita': 'Šv. Juozapina Bachita, mergelė',
	scholastica: 'Šv. Skolastika, mergelė',
	'our-lady-of-lourdes': 'Lurdo Švč. Mergelė Marija',
	'cyril-methodius': 'Šv. Kirilas, vienuolis, ir Metodijus, vyskupas',
	'seven-founders': 'Septyni šventieji Servitų ordino steigėjai',
	'peter-damian': 'Šv. Petras Damijonas, vyskupas, Bažnyčios mokytojas',
	'chair-of-peter': 'Šv. Petro, apaštalo, Sostas',
	polycarp: 'Šv. Polikarpas, vyskupas, kankinys',
	'gregory-of-narek': 'Šv. Grigalius Narekietis, abatas, Bažnyčios mokytojas',
	casimir: 'Šv. Kazimieras',
	'perpetua-felicity': 'Šv. Perpetua ir Felicita, kankinės',
	'john-of-god': 'Šv. Dievo Jonas, vienuolis',
	patrick: 'Šv. Patrikas, vyskupas',
	'cyril-of-jerusalem': 'Šv. Kirilas Jeruzalietis, vyskupas, Bažnyčios mokytojas',
	joseph: 'Šv. Juozapas, Švč. Mergelės Marijos Sužadėtinis',
	turibius: 'Šv. Turibijus Mongrovietis, vyskupas',
	annunciation: 'Viešpaties Apreiškimas Švč. Mergelei Marijai',
	'francis-of-paola': 'Šv. Pranciškus Paulietis, atsiskyrėlis',
	isidore: 'Šv. Izidorius, vyskupas, Bažnyčios mokytojas',
	'vincent-ferrer': 'Šv. Vincentas Fereras, kunigas',
	'john-baptist-de-la-salle': 'Šv. Jonas Salietis, kunigas',
	stanislaus: 'Šv. Stanislovas, vyskupas, kankinys',
	'martin-i': 'Šv. Martynas I, popiežius, kankinys',
	anselm: 'Šv. Anzelmas, vyskupas, Bažnyčios mokytojas',
	george: 'Šv. Jurgis, kankinys',
	mark: 'Šv. Morkus, evangelistas',
	'peter-chanel': 'Šv. Petras Šanelis, kunigas, kankinys',
	'louis-de-montfort': 'Šv. Liudvikas Marija Grinjonas Monforietis, kunigas',
	'catherine-of-siena': 'Šv. Kotryna Sienietė, mergelė, Bažnyčios mokytoja',
	'pius-v': 'Šv. Pijus V, popiežius',
	'joseph-the-worker': 'Šv. Juozapas Darbininkas',
	athanasius: 'Šv. Atanazas, vyskupas, Bažnyčios mokytojas',
	'philip-james': 'Šv. Pilypas ir Jokūbas, apaštalai',
	'john-of-avila': 'Šv. Jonas Avilietis, kunigas, Bažnyčios mokytojas',
	'nereus-achilleus': 'Šv. Nerijus ir Achilas, kankiniai',
	pancras: 'Šv. Pankratas, kankinys',
	'our-lady-of-fatima': 'Fatimos Švč. Mergelė Marija',
	matthias: 'Šv. Motiejus, apaštalas',
	'john-i': 'Šv. Jonas I, popiežius, kankinys',
	'bernardine-of-siena': 'Šv. Bernardinas Sienietis, kunigas',
	'christopher-magallanes': 'Šv. Kristoforas Magaljanesas ir jo draugai, kankiniai',
	'rita-of-cascia': 'Šv. Rita Kašietė, vienuolė',
	bede: 'Šv. Beda Garbingasis, kunigas, Bažnyčios mokytojas',
	'gregory-vii': 'Šv. Grigalius VII, popiežius',
	'mary-magdalene-de-pazzi': 'Šv. Marija Magdalena de Paci, mergelė',
	'philip-neri': 'Šv. Pilypas Neris, kunigas',
	'augustine-of-canterbury': 'Šv. Augustinas Kenterberietis, vyskupas',
	'paul-vi': 'Šv. Paulius VI, popiežius',
	visitation: 'Švč. Mergelės Marijos Apsilankymas',
	justin: 'Šv. Justinas, kankinys',
	'marcellinus-peter': 'Šv. Marcelinas ir Petras, kankiniai',
	'charles-lwanga': 'Šv. Karolis Luanga ir jo draugai, kankiniai',
	boniface: 'Šv. Bonifacas, vyskupas, kankinys',
	norbert: 'Šv. Norbertas, vyskupas',
	ephrem: 'Šv. Efremas, diakonas, Bažnyčios mokytojas',
	barnabas: 'Šv. Barnabas, apaštalas',
	'anthony-of-padua': 'Šv. Antanas Paduvietis, kunigas, Bažnyčios mokytojas',
	romuald: 'Šv. Romualdas, abatas',
	'aloysius-gonzaga': 'Šv. Aloyzas Gonzaga, vienuolis',
	'paulinus-of-nola': 'Šv. Paulinas Nolietis, vyskupas',
	'fisher-more': 'Šv. Jonas Fišeris, vyskupas, ir Tomas Moras, kankiniai',
	'birth-of-john-the-baptist': 'Šv. Jono Krikštytojo Gimimas',
	'cyril-of-alexandria': 'Šv. Kirilas Aleksandrietis, vyskupas, Bažnyčios mokytojas',
	irenaeus: 'Šv. Ireniejus, vyskupas, kankinys, Bažnyčios mokytojas',
	'peter-and-paul': 'Šv. Petras ir Paulius, apaštalai',
	'first-martyrs-of-rome': 'Pirmieji šventieji Romos Bažnyčios kankiniai',
	'thomas-apostle': 'Šv. Tomas, apaštalas',
	'elizabeth-of-portugal': 'Šv. Elzbieta Portugalė',
	'anthony-zaccaria': 'Šv. Antanas Marija Zakarijas, kunigas',
	'maria-goretti': 'Šv. Marija Goreti, mergelė, kankinė',
	'augustine-zhao-rong': 'Šv. Augustinas Džao Žongas, kunigas, ir jo draugai, kankiniai',
	benedict: 'Šv. Benediktas, abatas',
	henry: 'Šv. Henrikas',
	camillus: 'Šv. Kamilis Lelietis, kunigas',
	bonaventure: 'Šv. Bonaventūras, vyskupas, Bažnyčios mokytojas',
	'our-lady-of-mount-carmel': 'Karmelio kalno Švč. Mergelė Marija',
	apollinaris: 'Šv. Apolinaras, vyskupas, kankinys',
	'lawrence-of-brindisi': 'Šv. Laurynas Brindizietis, kunigas, Bažnyčios mokytojas',
	'mary-magdalene': 'Šv. Marija Magdalietė',
	bridget: 'Šv. Brigita, vienuolė',
	sharbel: 'Šv. Sarbelijus Machlufas, kunigas',
	james: 'Šv. Jokūbas, apaštalas',
	'joachim-anne': 'Šv. Joakimas ir Ona, Švč. Mergelės Marijos tėvai',
	'martha-mary-lazarus': 'Šv. Morta, Marija ir Lozorius',
	'peter-chrysologus': 'Šv. Petras Auksažodis, vyskupas, Bažnyčios mokytojas',
	'ignatius-of-loyola': 'Šv. Ignacas Lojola, kunigas',
	'alphonsus-liguori': 'Šv. Alfonsas Marija Liguoris, vyskupas, Bažnyčios mokytojas',
	'eusebius-of-vercelli': 'Šv. Euzebijus Vercelietis, vyskupas',
	'peter-julian-eymard': 'Šv. Petras Julijonas Eimaras, kunigas',
	'john-vianney': 'Šv. Jonas Marija Vianėjus, kunigas',
	'dedication-st-mary-major': 'Švč. Marijos bazilikos pašventinimas',
	transfiguration: 'Kristaus Atsimainymas',
	'sixtus-ii': 'Šv. Sikstas II, popiežius, ir jo draugai, kankiniai',
	cajetan: 'Šv. Kajetonas, kunigas',
	dominic: 'Šv. Dominykas, kunigas',
	'teresa-benedicta': 'Šv. Kryžiaus Teresė Benedikta, mergelė, kankinė',
	lawrence: 'Šv. Laurynas, diakonas, kankinys',
	clare: 'Šv. Klara, mergelė',
	'jane-frances-de-chantal': 'Šv. Joana Pranciška Šantalietė, vienuolė',
	'pontian-hippolytus': 'Šv. Poncijonas, popiežius, ir Ipolitas, kunigas, kankiniai',
	'maximilian-kolbe': 'Šv. Maksimilijonas Marija Kolbė, kunigas, kankinys',
	assumption: 'Švč. Mergelės Marijos Ėmimas į dangų',
	'stephen-of-hungary': 'Šv. Steponas Vengras',
	'john-eudes': 'Šv. Jonas Eudas, kunigas',
	bernard: 'Šv. Bernardas, abatas, Bažnyčios mokytojas',
	'pius-x': 'Šv. Pijus X, popiežius',
	'queenship-of-mary': 'Švč. Mergelė Marija Karalienė',
	'rose-of-lima': 'Šv. Rožė Limietė, mergelė',
	bartholomew: 'Šv. Baltramiejus, apaštalas',
	louis: 'Šv. Liudvikas',
	'joseph-calasanz': 'Šv. Juozapas Kalasantas, kunigas',
	monica: 'Šv. Monika',
	augustine: 'Šv. Augustinas, vyskupas, Bažnyčios mokytojas',
	'passion-of-john-the-baptist': 'Šv. Jono Krikštytojo Nukankinimas',
	'gregory-the-great': 'Šv. Grigalius Didysis, popiežius, Bažnyčios mokytojas',
	'teresa-of-calcutta': 'Šv. Teresė iš Kalkutos, mergelė',
	'nativity-of-mary': 'Švč. Mergelės Marijos Gimimas',
	'peter-claver': 'Šv. Petras Klaveras, kunigas',
	'holy-name-of-mary': 'Švč. Mergelės Marijos Vardas',
	'john-chrysostom': 'Šv. Jonas Auksaburnis, vyskupas, Bažnyčios mokytojas',
	'exaltation-of-the-cross': 'Šv. Kryžiaus Išaukštinimas',
	'our-lady-of-sorrows': 'Švč. Mergelė Marija Sopulingoji',
	'cornelius-cyprian': 'Šv. Kornelijus, popiežius, ir Kiprijonas, vyskupas, kankiniai',
	'robert-bellarmine': 'Šv. Robertas Belarminas, vyskupas, Bažnyčios mokytojas',
	hildegard: 'Šv. Hildegarda Bingenietė, mergelė, Bažnyčios mokytoja',
	januarius: 'Šv. Januarijus, vyskupas, kankinys',
	'andrew-kim': 'Šv. Andriejus Kim Taegonas, kunigas, ir kiti Korėjos kankiniai',
	matthew: 'Šv. Matas, apaštalas, evangelistas',
	'padre-pio': 'Šv. Pijus Pietrelčinietis, kunigas',
	'cosmas-damian': 'Šv. Kozmas ir Damijonas, kankiniai',
	'vincent-de-paul': 'Šv. Vincentas Paulietis, kunigas',
	wenceslaus: 'Šv. Vaclovas, kankinys',
	'lawrence-ruiz': 'Šv. Laurynas Ruisas ir jo draugai, kankiniai',
	archangels: 'Šv. Mykolas, Gabrielius ir Rapolas, arkangelai',
	jerome: 'Šv. Jeronimas, kunigas, Bažnyčios mokytojas',
	'therese-of-lisieux': 'Šv. Kūdikėlio Jėzaus Teresė, mergelė, Bažnyčios mokytoja',
	'guardian-angels': 'Šv. Angelai Sargai',
	'francis-of-assisi': 'Šv. Pranciškus Asyžietis, vienuolis',
	faustina: 'Šv. Faustina Kovalska, mergelė',
	bruno: 'Šv. Brunonas, kunigas',
	'our-lady-of-the-rosary': 'Rožinio Švč. Mergelė Marija',
	denis: 'Šv. Dionizas, vyskupas, ir jo draugai, kankiniai',
	'john-leonardi': 'Šv. Jonas Leonardis, kunigas',
	'john-henry-newman': 'Šv. John Henry Newman, kunigas, Bažnyčios mokytojas',
	'john-xxiii': 'Šv. Jonas XXIII, popiežius',
	'callistus-i': 'Šv. Kalikstas I, popiežius, kankinys',
	'teresa-of-avila': 'Šv. Jėzaus Teresė, mergelė, Bažnyčios mokytoja',
	hedwig: 'Šv. Jadvyga, vienuolė',
	'margaret-mary-alacoque': 'Šv. Margarita Marija Alakok, mergelė',
	'ignatius-of-antioch': 'Šv. Ignotas Antiochietis, vyskupas, kankinys',
	luke: 'Šv. Lukas, evangelistas',
	'north-american-martyrs':
		'Šv. Jonas Brebefas ir Izaokas Žogas, kunigai, ir jų draugai, kankiniai',
	'paul-of-the-cross': 'Šv. Kryžiaus Paulius, kunigas',
	'john-paul-ii': 'Šv. Jonas Paulius II, popiežius',
	'john-of-capistrano': 'Šv. Jonas Kapestranas, kunigas',
	'anthony-mary-claret': 'Šv. Antanas Marija Klaretas, vyskupas',
	'simon-jude': 'Šv. Simonas ir Judas (Tadas), apaštalai',
	'all-saints': 'Visi šventieji',
	'martin-de-porres': 'Šv. Martynas Poresas, vienuolis',
	'charles-borromeo': 'Šv. Karolis Boromiejus, vyskupas',
	'dedication-of-the-lateran': 'Laterano bazilikos Pašventinimas',
	'leo-the-great': 'Šv. Leonas Didysis, popiežius, Bažnyčios mokytojas',
	'martin-of-tours': 'Šv. Martynas Turietis, vyskupas',
	josaphat: 'Šv. Juozapatas, vyskupas, kankinys',
	'albert-the-great': 'Šv. Albertas Didysis, vyskupas, Bažnyčios mokytojas',
	'elizabeth-of-hungary': 'Šv. Elzbieta Vengrė, vienuolė',
	'dedication-of-peter-and-paul': 'Šv. Petro ir Pauliaus, apaštalų, bazilikų Pašventinimas',
	'presentation-of-mary': 'Švč. Mergelės Marijos Paaukojimas',
	cecilia: 'Šv. Cecilija, mergelė, kankinė',
	'clement-i': 'Šv. Klemensas I, popiežius, kankinys',
	columban: 'Šv. Kolumbanas, abatas',
	'andrew-dung-lac': 'Šv. Andriejus Zung-Lakas, kunigas, ir draugai, kankiniai',
	'catherine-of-alexandria': 'Šv. Kotryna Aleksandrietė, mergelė, kankinė',
	andrew: 'Šv. Andriejus, apaštalas',
	'francis-xavier': 'Šv. Pranciškus Ksaveras, kunigas',
	'john-damascene': 'Šv. Jonas Damaskietis, kunigas, Bažnyčios mokytojas',
	nicholas: 'Šv. Mikalojus, vyskupas',
	ambrose: 'Šv. Ambraziejus, vyskupas, Bažnyčios mokytojas',
	'immaculate-conception': 'Švč. Mergelės Marijos Nekaltasis Prasidėjimas',
	'juan-diego': 'Šv. Jonas Didakas Kuautlatoatsinas',
	'our-lady-of-loreto': 'Loreto Švč. Mergelė Marija',
	'damasus-i': 'Šv. Damazas I, popiežius',
	'our-lady-of-guadalupe': 'Gvadelupės Švč. Mergelė Marija',
	lucy: 'Šv. Liucija, mergelė, kankinė',
	'john-of-the-cross': 'Šv. Kryžiaus Jonas, kunigas, Bažnyčios mokytojas',
	'peter-canisius': 'Šv. Petras Kanizijus, kunigas, Bažnyčios mokytojas',
	'john-of-kanty': 'Šv. Jonas Kentietis, kunigas',
	stephen: 'Šv. Steponas, pirmasis kankinys',
	'john-evangelist': 'Šv. Jonas, apaštalas, evangelistas',
	'holy-innocents': 'Šv. Nekaltieji Vaikeliai, kankiniai',
	'thomas-becket': 'Šv. Tomas Beketas, vyskupas, kankinys',
	'sylvester-i': 'Šv. Silvestras I, popiežius',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Mūsų Viešpaties Jėzaus Kristaus Gimimas (Kalėdos)',
	'holy-family': 'Šventoji Šeima: Jėzus, Marija ir Juozapas',
	'mary-mother-of-god': 'Švč. Mergelė Marija, Dievo Gimdytoja',
	'christmas-2-sunday': 'II sekmadienis po Kalėdų',
	epiphany: 'Kristaus Apsireiškimas',
	'baptism-of-the-lord': 'Kristaus Krikštas',
	'ash-wednesday': 'Pelenų trečiadienis',
	'palm-sunday': 'Kristaus kančios (Verbų) sekmadienis',
	'holy-thursday': 'Didysis ketvirtadienis',
	'good-friday': 'Didysis penktadienis',
	'holy-saturday': 'Didysis šeštadienis',
	'easter-sunday': 'Viešpaties Jėzaus Kristaus Prisikėlimas (Velykos)',
	'easter-2-sunday': 'II Velykų sekmadienis (Dievo Gailestingumo sekmadienis)',
	ascension: 'Viešpaties žengimas į dangų',
	pentecost: 'Šventosios Dvasios atsiuntimas',
	trinity: 'Švenčiausioji Trejybė',
	'corpus-christi': 'Švč. Kristaus Kūnas ir Kraujas',
	'sacred-heart': 'Švč. Jėzaus Širdis',
	'immaculate-heart': 'Nekaltoji Švč. Mergelės Marijos Širdis',
	'mary-mother-of-the-church': 'Švč. Mergelė Marija, Bažnyčios Motina',
	'christ-the-king': 'Kristus, Visatos Valdovas (Kristus Karalius)'
};

/**
 * The Proper of Time in Lithuanian, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const ltTemporal: TemporalNames = {
	days: {
		1: 'Pirmadienis',
		2: 'Antradienis',
		3: 'Trečiadienis',
		4: 'Ketvirtadienis',
		5: 'Penktadienis',
		6: 'Šeštadienis'
	},
	weeks: {
		1: 'I',
		2: 'II',
		3: 'III',
		4: 'IV',
		5: 'V',
		6: 'VI',
		7: 'VII',
		8: 'VIII',
		9: 'IX',
		10: 'X',
		11: 'XI',
		12: 'XII',
		13: 'XIII',
		14: 'XIV',
		15: 'XV',
		16: 'XVI',
		17: 'XVII',
		18: 'XVIII',
		19: 'XIX',
		20: 'XX',
		21: 'XXI',
		22: 'XXII',
		23: 'XXIII',
		24: 'XXIV',
		25: 'XXV',
		26: 'XXVI',
		27: 'XXVII',
		28: 'XXVIII',
		29: 'XXIX',
		30: 'XXX',
		31: 'XXXI',
		32: 'XXXII',
		33: 'XXXIII',
		34: 'XXXIV'
	},
	octave: { 5: 'penktoji', 6: 'šeštoji', 7: 'septintoji' },
	sunday: {
		advent: '{week} Advento sekmadienis',
		lent: '{week} Gavėnios sekmadienis',
		easter: '{week} Velykų sekmadienis',
		ordinary: '{week} eilinis sekmadienis'
	},
	weekday: {
		advent: '{week} Advento savaitė, {day}',
		lent: '{week} Gavėnios savaitė, {day}',
		easter: '{week} Velykų savaitė, {day}',
		ordinary: '{week} eilinė savaitė, {day}'
	},
	holyWeek: {
		form: 'Didysis {day}',
		days: { 1: 'pirmadienis', 2: 'antradienis', 3: 'trečiadienis' }
	},
	afterAshes: '{day} po Pelenės',
	afterEpiphany: '{day} po Kristaus Apsireiškimo',
	christmasWeekday: '{day} prieš Kristaus Apsireiškimo',
	easterOctave: 'I Velykų savaitė, {day}',
	christmasOctave: 'Kalėdų {nth} diena'
};
