/**
 * The General Roman Calendar in Maltese.
 *
 * Transcribed from GCatholic's Maltese edition of Malta's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 216 of the Calendar's 218. The 2 absent are the ones Malta keeps someone
 * else on the day of — `vincent-deacon` among them — so this edition never
 * prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 */
export const mt: Record<string, string> = {
	'basil-gregory': 'San Bażilju l-kbir u San Girgor Nazjanzenu, isqfijiet u dutturi tal-Knisja',
	'holy-name-of-jesus': 'L-Isem Imqaddes ta’ Ġesù',
	'raymond-of-penyafort': 'San Raymond ta’ Penyafort, presbiteru',
	hilary: 'San Ilarju, isqof u duttur tal-Knisja',
	'anthony-abbot': 'San Anton, abbati',
	fabian: 'San Fabjan, Papa u martri',
	sebastian: 'San Sebastjan, martri',
	agnes: 'Sant’Anjeże, verġni u martri',
	'francis-de-sales': 'San Franġisk ta’ Sales, isqof u duttur tal-Knisja',
	'conversion-of-paul': 'Il-Konverżjoni tal-Appostlu Missierna San Pawl',
	'timothy-titus': 'San Titu u San Timotju, isqfijiet',
	'angela-merici': 'Santa Anġela Merici, verġni',
	'thomas-aquinas': 'San Tumas ta’Aquino, presbiteru u duttur tal-Knisja',
	'john-bosco': 'San Ġwann Bosco, presbiteru',
	'presentation-of-the-lord': 'Il-Preżentazzjoni tal-Mulej',
	blaise: 'San Bjaġju, isqof u martri',
	ansgar: 'San Ansgarju, isqof',
	agatha: 'Sant’Agata, verġni u martri',
	'paul-miki': 'San Pawl Miki u sħabu, martri',
	'jerome-emiliani': 'San Ġilormu Emiliani, reliġjuż',
	'josephine-bakhita': 'Santa Ġużeppina Bakhita, verġni',
	'our-lady-of-lourdes': 'Il-Verġni Mqaddsa Marija ta’ Lourdes',
	'cyril-methodius': 'San Cirillu, raħeb, u San Metodju, isqof',
	'seven-founders': 'Is-Seba’ Qaddisin Fundaturi tal-Ordni tas-Serviti ta’ Marija',
	'peter-damian': 'San Pietru Damiani, isqof u duttur tal-Knisja',
	'chair-of-peter': 'Il-Kattedra ta’ San Pietru, appostlu',
	polycarp: 'San Polikarpu, isqof u martri',
	'gregory-of-narek': 'San Girgor Nażjanżenu, abbati u duttur tal-Knisja',
	casimir: 'San Każimiru',
	'perpetua-felicity': 'Santa Perpetwa u Santa Feliċita, martri',
	'john-of-god': 'San Ġwann ta’ Alla, reliġjuż',
	'frances-of-rome': 'Santa Franġiska Rumana, reliġjuża',
	patrick: 'San Patrizju, isqof',
	'cyril-of-jerusalem': 'San Ċirillu ta’ Ġerusalemm, isqof u duttur tal-Knisja',
	joseph: 'San Ġużepp, l-Għarus tal-Verġni Mqaddsa Marija',
	turibius: 'San Turibju ta’ Mongrovejo, isqof',
	annunciation: 'It-Tħabbira tal-Mulej',
	'francis-of-paola': 'San Franġisk ta’ Paola, eremita',
	isidore: 'San Sidor, isqof u duttur tal-Knisja',
	'vincent-ferrer': 'San Vinċenz Ferrer, presbiteru',
	'john-baptist-de-la-salle': 'San Ġwann Battista de la Salle, presbiteru',
	stanislaus: 'San Stanislaw, isqof u martri',
	'martin-i': 'San Martin I, Papa u martri',
	anselm: 'San Anselmu, isqof u duttur tal-Knisja',
	george: 'San Ġorġ, martri',
	adalbert: 'San Adalbertu, isqof u martri',
	fidelis: 'San Fidiel minn Sigmaringen, presbiteru u martri',
	mark: 'San Mark, evanġelista',
	'peter-chanel': 'San Pietru Chanel, presbiteru u martri',
	'louis-de-montfort': 'San Ludovik Marija Grignion de Montfort, presbiteru',
	'catherine-of-siena': 'Santa Katerina ta’ Siena, verġni, duttur tal-Knisja',
	'pius-v': 'San Piju V, Papa',
	'joseph-the-worker': 'San Ġużepp Ħaddiem',
	athanasius: 'San Atanasju, isqof u duttur tal-Knisja',
	'philip-james': 'San Filippu u San Ġakbu, appostli',
	'john-of-avila': 'San Ġwann ta’ Avila, presbiteru u duttur tal-Knisja',
	'nereus-achilleus': 'San Nerew u San Akille, martri',
	pancras: 'San Prankrazju, martri',
	'our-lady-of-fatima': 'L-Imqaddsa Verġni Marija ta’ Fatima',
	matthias: 'San Mattija, appostlu',
	'john-i': 'San Ġwann I, Papa u martri',
	'bernardine-of-siena': 'San Bernardinu ta’ Siena, presbiteru',
	'christopher-magallanes': 'San Kristofru Magallanes, presbiteru, u sħabu, martri',
	'rita-of-cascia': 'Santa Rita minn Cascia, reliġjuża',
	bede: 'San Beda l-Venerabbli, presbiteru u duttur tal-Knisja',
	'gregory-vii': 'San Girgor VII, Papa',
	'mary-magdalene-de-pazzi': 'Santa Marija Maddalen de’ Pazzi, verġni',
	'philip-neri': 'San Filippu Neri, presbiteru',
	'augustine-of-canterbury': 'Santu Wistin ta’ Canterbury, isqof',
	'paul-vi': 'San Pawlu VI, Papa',
	visitation: 'Iż-Żjara tal-Imqaddsa Verġni Marija',
	justin: 'San Ġustinu, martri',
	'marcellinus-peter': 'San Marċellinu u San Pietru, martri',
	'charles-lwanga': 'San Karlu Lwang u sħabu, martri',
	boniface: 'San Bonifaċju, isqof u martri',
	norbert: 'San Norbertu, isqof',
	ephrem: 'San Efrem, djaknu u duttur tal-Knisja',
	barnabas: 'San Barnaba, appostlu',
	'anthony-of-padua': 'Sant’Antnin ta’ Padova, presbiteru u duttur tal-Knisja',
	romuald: 'San Romwaldu, abbati',
	'aloysius-gonzaga': 'San Alwiġi Gonzaga, reliġjuż',
	'paulinus-of-nola': 'San Pawlinu ta’ Nola, isqof',
	'fisher-more': 'San Ġwann Fisher, isqof u San Tumas More, martri',
	'birth-of-john-the-baptist': 'It-Twelid ta’ San Ġwann Battista',
	'cyril-of-alexandria': 'San Ċirillu ta’ Lixandra, isqof u duttur tal-Knisja',
	irenaeus: 'San Irinew, isqof, martri u duttur tal-Knisja',
	'peter-and-paul': 'San Pietru u San Pawl, appostli',
	'first-martyrs-of-rome': 'L-Ewwel Martri tal-Knisja ta’ Ruma',
	'thomas-apostle': 'San Tumas, appostlu',
	'elizabeth-of-portugal': 'Santa Eliżabetta tal-Portugal',
	'anthony-zaccaria': 'San Anton Marija Zaccaria, presbiteru',
	'maria-goretti': 'Santa Marija Goretti, verġni u martri',
	'augustine-zhao-rong': 'Santu Wistin Zhao Rong, presbiteru, u sħabu, martri',
	benedict: 'San Benedittu, abbati',
	henry: 'San Enriku',
	camillus: 'San Kamillu de Lellis, presbiteru',
	bonaventure: 'San Bonaventura, isqof u duttur tal-Knisja',
	'our-lady-of-mount-carmel': 'L-Imqaddsa Verġni Marija tal-Għolja tal-Karmelu',
	apollinaris: 'San Apollinaris, isqof u martri',
	'lawrence-of-brindisi': 'San Lawrenz ta’ Brindisi, presbiteru u duttur tal-Knisja',
	'mary-magdalene': 'Santa Marija Maddalena',
	bridget: 'Santa Briġida, reliġjuża',
	sharbel: 'San Xarbel Makhlüf, presbiteru',
	james: 'San Ġakbu, appostlu',
	'joachim-anne': 'San Ġwakkin u Sant’Anna, ġenituri tal-Imqaddsa Verġni Marija',
	'martha-mary-lazarus': 'Santa Marta, Santa Marija u San Lazzru',
	'peter-chrysologus': 'San Pietru Krisologu, isqof u duttur tal-Knisja',
	'ignatius-of-loyola': 'San Injazju ta’ Loyola, presbiteru',
	'alphonsus-liguori': 'San Alfons Marija de’ Liguori, isqof u duttur tal-Knisja',
	'eusebius-of-vercelli': 'San Ewsebju ta’ Vercelli, isqof',
	'peter-julian-eymard': 'San Pietru Ġiljan Eymard, presbiteru',
	'john-vianney': 'San Ġwann Marija Vianney, presbiteru',
	'dedication-st-mary-major': 'Id-Dedikazzjoni tal-Bażilka ta’ Santa Marija Maggiore, f’Ruma',
	transfiguration: 'It-Trasfigurazzjoni tal-Mulej',
	'sixtus-ii': 'San Sistu II, Papa u sħabu, martri',
	cajetan: 'San Gejtanu, presbiteru',
	dominic: 'San Duminku, presbiteru',
	'teresa-benedicta': 'Santa Tereża Benedetta tas-Salib, verġni u martri',
	lawrence: 'San Lawrenz, djaknu u martri',
	clare: 'Santa Kjara, verġni',
	'jane-frances-de-chantal': 'Santa Ġovanna Franġiksa de Chantal, reliġjuża',
	'pontian-hippolytus': 'San Ponzjanu, Papa, u San Ippolitu, saċerdot, martri',
	'maximilian-kolbe': 'San Massimiljan Marija Kolbe, presbiteru u martri',
	assumption: 'L-Imqaddsa Verġni Marija Mtellgħa s-Sema',
	'stephen-of-hungary': 'San Stiefnu tal-Ungerija',
	'john-eudes': 'San Ġwann Eudes, presbiteru',
	bernard: 'San Bernard, abbati u duttur tal-Knisja',
	'pius-x': 'San Piju X, Papa',
	'queenship-of-mary': 'L-Imqaddsa Verġni Marija Reġina',
	'rose-of-lima': 'Santa Roża ta’ Lima, verġni',
	bartholomew: 'San Bartilmew, appostlu',
	louis: 'San Ludoviku IX',
	'joseph-calasanz': 'San Ġużepp Calasanz, presbiteru',
	monica: 'Santa Monika',
	augustine: 'Santu Wistin, isqof u duttur tal-Knisja',
	'passion-of-john-the-baptist': 'Il-Martirju ta’ Ġwanni l-Battista',
	'gregory-the-great': 'San Girgor il-Kbir, Papa u duttur tal-Knisja',
	'teresa-of-calcutta': 'Santa Tereża ta’ Calcutta, verġni',
	'nativity-of-mary': 'It-Twelid tal-Imqaddsa Verġni Marija',
	'peter-claver': 'San Pietru Claver, presbiteru',
	'holy-name-of-mary': 'L-Isem tal-Imqaddsa Verġni Marija',
	'john-chrysostom': 'San Ġwann Grisostmu, isqof u duttur tal-Knisja',
	'exaltation-of-the-cross': 'L-Eżaltazzjoni tas-Salib Imqaddes',
	'our-lady-of-sorrows': 'Il-Verġni Mqaddsa Marija tad-Duluri',
	'cornelius-cyprian': 'San Kornelju, Papa u San Ċiprijanu, isqof, martri',
	'robert-bellarmine': 'San Robertu Bellarmino, isqof u duttur tal-Knisja',
	hildegard: 'Sant’Ildegarda ta’ Bingen, verġni u duttur tal-Knisja',
	januarius: 'San Ġennaru, isqof u martri',
	'andrew-kim': 'San Andrija Kim Taegon, presbiteru, u San Pawl Chong Hasang, u sħabhom, martri',
	matthew: 'San Mattew, appostlu u evanġelista',
	'padre-pio': 'San Piju ta’ Pietrelcina, presbiteru',
	'cosmas-damian': 'San Kosma u San Damjan, martri',
	'vincent-de-paul': 'San Vinċenz de Paul, presbiteru',
	wenceslaus: 'San Vinċeslaw, Re tal-Boemja, martri',
	'lawrence-ruiz': 'San Lawrenz Ruiz u sħabu, martri',
	archangels: 'L-Arkanġli Mqaddsa, Mikiel, Gabrijel u Rafel',
	jerome: 'San Ġilormu, presbiteru u duttur tal-Knisja',
	'therese-of-lisieux': 'Santa Tereża tal-Bambin Ġesù, verġni u duttura tal-Knisja',
	'guardian-angels': 'L-Anġli Kustodji Mqaddsa',
	'francis-of-assisi': 'San Franġisk ta’ Assisi, djaknu',
	faustina: 'Santa Marija Fawstina Kowalska, verġni',
	bruno: 'San Bruno, presbiteru',
	'our-lady-of-the-rosary': 'L-Imqaddsa Verġni Marija tar-Rużarju',
	denis: 'San Djonisju, isqof, u sħabu, martri',
	'john-leonardi': 'San Ġwann Leonardi, presbiteru',
	'john-henry-newman': 'San John Henry Newman, presbiteru u duttur tal-Knisja',
	'john-xxiii': 'San Ġwanni XXIII, Papa',
	'callistus-i': 'San Kallistu, Papa u martri',
	'teresa-of-avila': 'Santa Tereża ta’ Ġesù, verġni u duttur tal-Knisja',
	hedwig: 'Santa Edwiġe, reliġjuża',
	'margaret-mary-alacoque': 'Santa Margerita Marija Alacoque, verġni',
	'ignatius-of-antioch': 'San Injazju ta’ Antjokja, isqof u martri',
	luke: 'San Luqa, evanġelista',
	'north-american-martyrs': 'San Ġwann de Brébeuf u San Iżakk Jogues, presbiteri u sħabhom, martri',
	'paul-of-the-cross': 'San Pawl tas-Salib, presbiteru',
	'john-paul-ii': 'San Ġwann Pawlu II, Papa',
	'john-of-capistrano': 'San Ġwann minn Capestrano, presbiteru',
	'anthony-mary-claret': 'San Anton Marija Claret, isqof',
	'simon-jude': 'San Xmun u San Ġuda, appostli',
	'all-saints': 'Il-Qaddisin Kollha',
	'martin-de-porres': 'San Martin de Porres, reliġjuż',
	'charles-borromeo': 'San Karlu Borromeo, isqof',
	'dedication-of-the-lateran': 'Id-Dedikazzjoni tal-Bażilka tal-Lateran',
	'leo-the-great': 'San Ljun il-Kbir, Papa u duttur tal-Knisja',
	'martin-of-tours': 'San Martin ta’ Tours, isqof',
	josaphat: 'San Ġosofat, isqof u martri',
	'albert-the-great': 'San Albertu l-Kbir, isqof u duttur tal-Knisja',
	'margaret-of-scotland': 'Santa Margerita tal-Iskozja',
	gertrude: 'Santa Ġertrude, verġni',
	'elizabeth-of-hungary': 'Santa Eliżabetta tal-Ungerija',
	'dedication-of-peter-and-paul': 'Id-Dedikazzjoni tal-Bażilki ta’ San Pietru u San Pawl, appostli',
	'presentation-of-mary': 'Il-Preżentazzjoni tal-Imqaddsa Verġni Marija',
	cecilia: 'Santa Ċeċilja, verġni u martri',
	'clement-i': 'San Klement I, Papa u martri',
	columban: 'San Kolumbanu, abbati',
	'andrew-dung-lac': 'Sant’Andrija Dung Lac, presbiteru, u sħabu, martri',
	'catherine-of-alexandria': 'Santa Katerina ta’ Lixandra, verġni u martri',
	andrew: 'Sant’Andrija, appostlu',
	'francis-xavier': 'San Franġisk Saverju, saċerdot',
	'john-damascene': 'San Ġwann Damaxxenu, presbiteru u duttur tal-Knisja',
	nicholas: 'San Nikola, isqof',
	ambrose: 'San Ambroġ, isqof u duttur tal-Knisja',
	'immaculate-conception': 'It-Tnissil bla Tebgħa tal-Imqaddsa Verġni Marija',
	'juan-diego': 'San Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Madonna ta’ Loreto',
	'damasus-i': 'San Damasu I, Papa',
	'our-lady-of-guadalupe': 'L-Imqaddsa Verġni Marija ta’ Gwadalupe',
	lucy: 'Santa Luċija, verġni u martri',
	'john-of-the-cross': 'San Ġwann tas-Salib, presbiteru u duttur tal-Knisja',
	'peter-canisius': 'San Pietru Kanisju, presbiteru u duttur tal-Knisja',
	'john-of-kanty': 'San Ġwann de Kety, presbiteru',
	stephen: 'San Stiefnu, protomartri',
	'john-evangelist': 'San Ġwann, appostlu u evanġelista',
	'holy-innocents': 'Il-Qaddisin Innoċenti Martri',
	'thomas-becket': 'San Tumas Becket, isqof u martri',
	'sylvester-i': 'San Silvestru, Papa'
};
