/**
 * The General Roman Calendar in Dutch.
 *
 * Transcribed from the 2 calendars GCatholic publishes in Dutch.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * All 218 of them, in the Calendar's own order.
 */
export const nl: Record<string, string> = {
	'basil-gregory': 'HH. Basilius de Grote en Gregorius van Nazianze, bisschoppen en kerkleraren',
	'holy-name-of-jesus': 'De heilige Naam Jezus',
	'raymond-of-penyafort': 'H. Raimundus van Penyafort, priester',
	hilary: 'H. Hilarius, bisschop en kerkleraar',
	'anthony-abbot': 'H. Antonius, abt',
	fabian: 'H. Fabianus, paus en martelaar',
	sebastian: 'H. Sebastianus, martelaar',
	agnes: 'H. Agnes, maagd en martelares',
	'vincent-deacon': 'H. Vincentius, diaken en martelaar',
	'francis-de-sales': 'H. Franciscus van Sales, bisschop en kerkleraar',
	'conversion-of-paul': 'Bekering van de heilige apostel Paulus',
	'timothy-titus': 'HH. Timoteüs en Titus, bisschoppen',
	'angela-merici': 'H. Angela Merici, stichteres kloosterorde',
	'thomas-aquinas': 'H. Thomas van Aquino, priester en kerkleraar',
	'john-bosco': 'H. Johannes Bosco, priester',
	'presentation-of-the-lord': 'Opdracht van de Heer in de Tempel',
	blaise: 'H. Blasius, bisschop en martelaar',
	ansgar: 'H. Ansgarius, bisschop',
	agatha: 'H. Agatha, maagd en martelares',
	'paul-miki': 'HH. Paulus Miki en gezellen, martelaren',
	'jerome-emiliani': 'H. Hiëronymus Emiliani',
	'josephine-bakhita': 'H. Josephina Bakhita, maagd',
	scholastica: 'H. Scholastica, maagd',
	'our-lady-of-lourdes': 'Heilige maagd Maria van Lourdes',
	'cyril-methodius': 'HH. Cyrillus, monnik, en Methodius, bisschop',
	'seven-founders': 'Zeven HH. Stichters van de Servieten van Maria',
	'peter-damian': 'H. Petrus Damiani, bisschop en kerkleraar',
	'chair-of-peter': 'Cathedra van de heilige apostel Petrus',
	polycarp: 'H. Polycarpus, bisschop en martelaar',
	'gregory-of-narek': 'H. Gregorius van Narek, abt en kerkleraar',
	casimir: 'H. Casimir, koning',
	'perpetua-felicity': 'HH. Perpetua en Felicitas, martelaressen',
	'john-of-god': 'H. Johannes de Deo, kloosterling',
	'frances-of-rome': 'H. Francisca Romana, kloosterlinge',
	patrick: 'H. Patricius, bisschop',
	'cyril-of-jerusalem': 'H. Cyrillus van Jeruzalem, bisschop en kerkleraar',
	joseph: 'H. Jozef, bruidegom van de heilige maagd Maria',
	turibius: 'H. Turibius de Mogrovejo, bisschop',
	annunciation: 'Aankondiging van de Heer',
	'francis-of-paola': 'H. Franciscus van Paola, kluizenaar',
	isidore: 'H. Isidorus van Sevilla, bisschop en kerkleraar',
	'vincent-ferrer': 'H. Vincent Ferrer, priester',
	'john-baptist-de-la-salle': 'H. Jean-Baptiste de la Salle, priester',
	stanislaus: 'H. Stanislas van Krakau, bisschop en martelaar',
	'martin-i': 'H. Martinus I, paus en martelaar',
	anselm: 'H. Anselmus, bisschop en kerkleraar',
	george: 'H. Joris, martelaar',
	adalbert: 'H. Adelbertus van Praag, bisschop en martelaar',
	fidelis: 'H. Fedelis van Sigmaringen, priester en martelaar',
	mark: 'H. Marcus, evangelist',
	'peter-chanel': 'H. Petrus Chanel, priester en martelaar',
	'louis-de-montfort': 'H. Louis-Marie Grignion de Montfort, priester',
	'catherine-of-siena': 'H. Catharina van Siena, maagd en kerklerares',
	'pius-v': 'H. Pius V, paus',
	'joseph-the-worker': 'H. Jozef, de Arbeider',
	athanasius: 'H. Athanasius, bisschop en kerkleraar',
	'philip-james': 'HH. Filippus en Jacobus, apostelen',
	'john-of-avila': 'H. Johannes van Ávila, priester en kerkleraar',
	'nereus-achilleus': 'HH. Nereus en Achilleus, martelaren',
	pancras: 'H. Pancratius, martelaar',
	'our-lady-of-fatima': 'Onze-Lieve-Vrouw van Fátima',
	matthias: 'H. Mattias, apostel',
	'john-i': 'H. Johannes I, paus en martelaar',
	'bernardine-of-siena': 'H. Bernardinus van Siena, priester',
	'christopher-magallanes': 'HH. Christophorus Magellaen, priester, en gezellen, martelaren',
	'rita-of-cascia': 'H. Rita van Cascia, kloosterlinge',
	bede: 'H. Beda de eerbiedwaardige, priester en kerkleraar',
	'gregory-vii': 'H. Gregorius VII, paus',
	'mary-magdalene-de-pazzi': 'H. Maria Magdalena de’ Pazzi, maagd',
	'philip-neri': 'H. Filippus Neri, priester',
	'augustine-of-canterbury': 'H. Augustinus van Canterbury, bisschop',
	'paul-vi': 'H. Paulus VI, paus',
	visitation: 'Maria Visitatie',
	justin: 'H. Justinus, martelaar',
	'marcellinus-peter': 'HH. Marcellinus en Petrus, martelaren',
	'charles-lwanga': 'HH. Carolus Lwanga en gezellen, martelaren',
	boniface: 'H. Bonifatius, bisschop en martelaar',
	norbert: 'H. Norbertus, bisschop',
	ephrem: 'H. Efrem de Syriër, diaken en kerkleraar',
	barnabas: 'H. Barnabas, apostel',
	'anthony-of-padua': 'H. Antonius van Padua, priester en kerkleraar',
	romuald: 'H. Romualdus, abt',
	'aloysius-gonzaga': 'H. Aloysius Gonzaga, kloosterling',
	'paulinus-of-nola': 'H. Paulinus van Nola, bisschop',
	'fisher-more': 'HH. John Fisher, bisschop, en Thomas More, martelaren',
	'birth-of-john-the-baptist': 'Geboorte van de H. Johannes de Doper',
	'cyril-of-alexandria': 'H. Cyrillus van Alexandrië, bisschop en kerkvader',
	irenaeus: 'H. Irenaeus van Lyon, bisschop, martelaar en kerkvader',
	'peter-and-paul': 'HH. Petrus en Paulus, apostelen',
	'first-martyrs-of-rome': 'Eerste martelaren van de Romeinse Kerk',
	'thomas-apostle': 'H. Thomas, apostel',
	'elizabeth-of-portugal': 'H. Elisabeth van Portugal',
	'anthony-zaccaria': 'H. Antonius Maria Zaccaria, priester',
	'maria-goretti': 'H. Maria Goretti, maagd en martelares',
	'augustine-zhao-rong': 'HH. Augustinus Zhao Rong, priester, en gezellen, martelaren',
	benedict: 'H. Benedictus, abt',
	henry: 'H. Henricus, keizer',
	camillus: 'H. Camillus de Lellis, priester',
	bonaventure: 'H. Bonaventura, bisschop en kerkleraar',
	'our-lady-of-mount-carmel': 'Onze-Lieve-Vrouw van de berg Karmel',
	apollinaris: 'H. Appollinaris, bisschop en martelaar',
	'lawrence-of-brindisi': 'H. Laurentius van Brindisi, priester en kerkleraar',
	'mary-magdalene': 'H. Maria Magdalena',
	bridget: 'H. Birgitta van Zweden, kloosterlinge',
	sharbel: 'H. Charbel Makhluf, priester',
	james: 'H. Jacobus, apostel',
	'joachim-anne': 'HH. Joachim en Anna, ouders van de maagd Maria',
	'martha-mary-lazarus': 'HH. Marta, Maria en Lazarus',
	'peter-chrysologus': 'H. Petrus Chrysologus, bisschop en kerkleraar',
	'ignatius-of-loyola': 'H. Ignatius van Loyola, priester',
	'alphonsus-liguori': 'H. Alfonsus Maria de Liguori, bisschop en kerkleraar',
	'eusebius-of-vercelli': 'H. Eusebius van Vercelli, bisschop',
	'peter-julian-eymard': 'H. Pierre-Julien Eymard, priester',
	'john-vianney': 'H. Johannes Maria Vianney, priester',
	'dedication-st-mary-major': 'Kerkwijding van de basiliek Santa Maria Maggiore',
	transfiguration: 'Gedaanteverandering van de Heer',
	'sixtus-ii': 'H. Sixtus II, paus, en gezellen, martelaren',
	cajetan: 'H. Gaetano van Thiene, priester',
	dominic: 'H. Dominicus Guzman, priester',
	'teresa-benedicta': 'H. Teresia Benedicta van het Kruis',
	lawrence: 'H. Laurentius, diaken en martelaar',
	clare: 'H. Clara van Assisi, maagd',
	'jane-frances-de-chantal': 'H. Johanna Francisca de Chantal, kloosterlinge',
	'pontian-hippolytus': 'HH. Pontianus, paus, en Hippolytus, priester, martelaren',
	'maximilian-kolbe': 'H. Maximiliaan Kolbe, priester',
	assumption: 'Maria Tenhemelopneming',
	'stephen-of-hungary': 'H. Stephanus van Hongarije, koning',
	'john-eudes': 'H. Johannes Eudes, priester',
	bernard: 'H. Bernardus van Clairvaux, abt en kerkleraar',
	'pius-x': 'H. Pius X, paus',
	'queenship-of-mary': 'Maria Koningin',
	'rose-of-lima': 'H. Rosa van Lima, maagd',
	bartholomew: 'H. Bartolomeus, apostel',
	louis: 'H. Lodewijk, koning',
	'joseph-calasanz': 'H. Jozef van Calasanza, priester',
	monica: 'H. Monica',
	augustine: 'H. Augustinus, bisschop en kerkvader',
	'passion-of-john-the-baptist': 'Onthoofding van de H. Johannes de Doper, martelaar',
	'gregory-the-great': 'H. Gregorius de Grote, paus en kerkleraar',
	'teresa-of-calcutta': 'H. Teresa van Calcutta, maagd',
	'nativity-of-mary': 'Maria Geboorte',
	'peter-claver': 'H. Petrus Claver, kloosterling',
	'holy-name-of-mary': 'Heilige Naam van Maria',
	'john-chrysostom': 'H. Johannes Chrysostomus, bisschop en kerkleraar',
	'exaltation-of-the-cross': 'Kruisverheffing',
	'our-lady-of-sorrows': 'Onze-Lieve-Vrouw van Smarten',
	'cornelius-cyprian': 'HH. Cornelius, paus, en Cyprianus, bisschop, martelaren',
	'robert-bellarmine': 'H. Robertus Bellarminus, bisschop en kerkleraar',
	hildegard: 'H. Hildegard van Bingen, maagd en kerklerares',
	januarius: 'H. Januarius, bisschop en martelaar',
	'andrew-kim': 'HH. Andreas Kim Taegon, priester, en Paulus Chong Hasang en gezellen, martelaren',
	matthew: 'H. Matteüs, apostel en evangelist',
	'padre-pio': 'H. Pius van Pietrelcina, priester',
	'cosmas-damian': 'HH. Cosmas en Damianus, martelaren',
	'vincent-de-paul': 'H. Vincentius a Paulo, priester',
	wenceslaus: 'H. Wenceslaus, martelaar',
	'lawrence-ruiz': 'HH. Laurentius Ruiz en gezellen, martelaren',
	archangels: 'HH. Michaël, Gabriël en Rafaël, aartsengelen',
	jerome: 'H. Hiëronymus, priester en kerkvader',
	'therese-of-lisieux': 'H. Theresia van het kind Jezus, maagd en kerklerares',
	'guardian-angels': 'HH. Engelbewaarders',
	'francis-of-assisi': 'H. Franciscus van Assisi',
	faustina: 'H. Maria Faustina Kowalska, kloosterlinge',
	bruno: 'H. Bruno van Keulen, priester',
	'our-lady-of-the-rosary': 'Onze-Lieve-Vrouw van de Rozenkrans',
	denis: 'HH. Dionysius, bisschop, en gezellen, martelaren',
	'john-leonardi': 'H. Johannes Leonardus, priester',
	'john-henry-newman': 'H. John Henry Newman, priester en kerkleraar',
	'john-xxiii': 'H. Johannes XXIII, paus',
	'callistus-i': 'H. Callistus I, paus en martelaar',
	'teresa-of-avila': 'H. Theresia van Ávila, maagd en kerklerares',
	hedwig: 'H. Hedwig, kloosterlinge',
	'margaret-mary-alacoque': 'H. Margaretha Maria Alacoque, maagd',
	'ignatius-of-antioch': 'H. Ignatius van Antiochië, bisschop en martelaar',
	luke: 'H. Lucas, evangelist',
	'north-american-martyrs':
		'HH. Jean de Brébeuf en Isaac Jogues, priesters, en gezellen, martelaren',
	'paul-of-the-cross': 'H. Paulus van het Kruis, priester',
	'john-paul-ii': 'H. Johannes Paulus II, paus',
	'john-of-capistrano': 'H. Johannes de Capistrano, priester',
	'anthony-mary-claret': 'H. Antonius Maria Claret, bisschop',
	'simon-jude': 'HH. Simon en Judas, apostelen',
	'all-saints': 'Allerheiligen',
	'martin-de-porres': 'H. Martinus van Porres, kloosterling',
	'charles-borromeo': 'H. Carolus Borromeus, bisschop',
	'dedication-of-the-lateran': 'Kerkwijding van de basiliek van Sint-Jan van Lateranen',
	'leo-the-great': 'H. Leo de Grote, paus en kerkleraar',
	'martin-of-tours': 'H. Martinus van Tours, bisschop',
	josaphat: 'H. Josafat Kuncewycz, bisschop en martelaar',
	'albert-the-great': 'H. Albertus de Grote, bisschop en kerkleraar',
	'margaret-of-scotland': 'H. Margaretha van Schotland, koningin',
	gertrude: 'H. Gertrudis van Helfta, maagd',
	'elizabeth-of-hungary': 'H. Elisabeth van Hongarije, moniale',
	'dedication-of-peter-and-paul': 'Kerkwijding van de Basilieken van de apostelen Petrus en Paulus',
	'presentation-of-mary': 'Opdracht van de heilige maagd Maria in de tempel',
	cecilia: 'H. Caecilia, maagd en martelares',
	'clement-i': 'H. Clemens I, paus en martelaar',
	columban: 'H. Columbanus, abt',
	'andrew-dung-lac': 'HH. Andreas Dung-Lac, priester, en gezellen, martelaren',
	'catherine-of-alexandria': 'H. Catharina van Alexandrië',
	andrew: 'H. Andreas, apostel',
	'francis-xavier': 'H. Franciscus Xaverius, priester',
	'john-damascene': 'H. Johannes van Damascus, priester en kerkleraar',
	nicholas: 'H. Nicolaas van Myra, bisschop',
	ambrose: 'H. Ambrosius, bisschop en kerkleraar',
	'immaculate-conception': 'Onbevlekte Ontvangenis van de heilige maagd Maria',
	'juan-diego': 'H. Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Onze-Lieve-Vrouw van Loreto',
	'damasus-i': 'H. Damasus I, paus',
	'our-lady-of-guadalupe': 'Onze-Lieve-Vrouw van Guadalupe',
	lucy: 'H. Lucia, maagd en martelares',
	'john-of-the-cross': 'H. Johannes van het Kruis, priester en kerkleraar',
	'peter-canisius': 'H. Petrus Canisius, priester en kerkleraar',
	'john-of-kanty': 'H. Johannes van Kenty, priester',
	stephen: 'H. Stefanus, diaken en eerste martelaar',
	'john-evangelist': 'H. Johannes, apostel en evangelist',
	'holy-innocents': 'HH. Onnozele Kinderen, martelaren',
	'thomas-becket': 'H. Thomas Becket, bisschop en martelaar',
	'sylvester-i': 'H. Silvester I, paus'
};
