/**
 * The General Roman Calendar in Norwegian.
 *
 * Transcribed from GCatholic's Norwegian edition of Norway's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 212 of the Calendar's 218. The 6 absent are the ones Norway keeps someone
 * else on the day of — `timothy-titus` among them — so this edition never
 * prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 */
export const no: Record<string, string> = {
	'basil-gregory':
		'Den hellige Basilios den store og den hellige Gregor fra Nazianz, biskoper og kirkelærere',
	'holy-name-of-jesus': 'Jesu hellige navn',
	'raymond-of-penyafort': 'Den hellige Raimund av Peñafort, prest',
	hilary: 'Den hellige Hilarius, biskop og kirkelærer',
	'anthony-abbot': 'Den hellige Antonius, abbed',
	fabian: 'Den hellige Fabian, pave og martyr',
	sebastian: 'Den hellige Sebastian, martyr',
	agnes: 'Den hellige Agnes, jomfru og martyr',
	'vincent-deacon': 'Den hellige Vincent, diakon og martyr',
	'francis-de-sales': 'Den hellige Frans av Sales, biskop og kirkelærer',
	'conversion-of-paul': 'Apostelen Paulus’ omvendelse',
	'angela-merici': 'Den hellige Angela Merici, jomfru',
	'thomas-aquinas': 'Den hellige Thomas Aquinas, prest og kirkelærer',
	'john-bosco': 'Den hellige Johannes Bosco, prest',
	'presentation-of-the-lord': 'Herrens fremstilling i templet',
	ansgar: 'Den hellige Ansgar, biskop',
	agatha: 'Den hellige Agathe, jomfru og martyr',
	'paul-miki': 'Den hellige Paul Miki og hans ledsagere, martyrer',
	'jerome-emiliani': 'Den hellige Hieronymus Emiliani',
	'josephine-bakhita': 'Den hellige Josefina Bakhita, jomfru',
	scholastica: 'Den hellige Scholastica, jomfru',
	'our-lady-of-lourdes': 'Vår Frue av Lourdes',
	'cyril-methodius': 'Den hellige Kyrillos, munk, og den hellige Methodios, biskop',
	'seven-founders': 'De syv stiftere av Servitterordenen',
	'peter-damian': 'Den hellige Peter Damian, biskop og kirkelærer',
	'chair-of-peter': 'Apostelen Peters stol',
	polycarp: 'Den hellige Polykarp, biskop og martyr',
	'gregory-of-narek': 'Den hellige Gregor av Narek, abbed og kirkelærer',
	casimir: 'Den hellige Kasimir',
	'perpetua-felicity': 'De hellige Perpetua og Felicitas, martyrer',
	'john-of-god': 'Den hellige Johannes av Gud, munk',
	'frances-of-rome': 'Den hellige Fransiska av Roma, nonne',
	patrick: 'Den hellige Patrick, biskop',
	'cyril-of-jerusalem': 'Den hellige Kyrillos av Jerusalem, biskop og kirkelærer',
	joseph: 'Den hellige Josef, jomfru Marias brudgom',
	turibius: 'Den hellige Turibio av Mogrovejo, biskop',
	annunciation: 'Herrens bebudelse',
	'francis-of-paola': 'Den hellige Frans fra Paola, eremitt',
	isidore: 'Den hellige Isidor av Sevilla, biskop og kirkelærer',
	'vincent-ferrer': 'Den hellige Vincent Ferrer, biskop og kirkelærer',
	'john-baptist-de-la-salle': 'Den hellige Jean Baptiste de la Salle, prest',
	stanislaus: 'Den hellige Stanislaus, biskop og martyr',
	'martin-i': 'Den hellige Martin I, pave og martyr',
	anselm: 'Den hellige Anselm av Canterbury, biskop og kirkelærer',
	george: 'Den hellige Georg, martyr',
	adalbert: 'Den hellige Adalbert av Praha, biskop og martyr',
	fidelis: 'Den hellige Fidelis av Sigmaringen, prest og martyr',
	mark: 'Den hellige Markus, evangelist',
	'peter-chanel': 'Den hellige Peter Chanel, prest og martyr',
	'louis-de-montfort': 'Den hellige Louis de Montfort, prest',
	'catherine-of-siena': 'Den hellige Katarina av Siena, jomfru og kirkelærer',
	'pius-v': 'Den hellige Pius V, pave',
	'joseph-the-worker': 'Den hellige Josef, håndverkeren',
	athanasius: 'Den hellige Athanasius, biskop og kirkelærer',
	'philip-james': 'Den hellige Filip og den hellige Jakob, apostler',
	'john-of-avila': 'Den hellige Johannes av Ávila, prest og kirkelærer',
	'nereus-achilleus': 'Den hellige Nereus og den hellige Achilleus, martyrer',
	pancras: 'Den hellige Pancratius, martyr',
	'our-lady-of-fatima': 'Den salige Jomfru Maria av Fatima',
	matthias: 'Den hellige Mattias, apostel',
	'bernardine-of-siena': 'Den hellige Bernardin av Siena, prest',
	'christopher-magallanes': 'Den hellige Kristoffer Magallanes og hans ledsagere',
	'rita-of-cascia': 'Den hellige Rita av Cascia',
	bede: 'Den hellige Beda den ærverdige, prest og kirkelærer',
	'gregory-vii': 'Den hellige Gregor VII, pave',
	'mary-magdalene-de-pazzi': 'Den hellige Maria Magdalena de’ Pazzi, jomfru',
	'philip-neri': 'Den hellige Filip Neri, prest',
	'augustine-of-canterbury': 'Den hellige Augustin av Canterbury, biskop',
	'paul-vi': 'Den hellige Paul VI, pave',
	visitation: 'Jomfru Marias gjesting hos Elisabeth',
	justin: 'Den hellige Justin, martyr',
	'marcellinus-peter': 'Den hellige Marcellinus og den hellige Peter, martyrer',
	'charles-lwanga': 'Den hellige Karl Lwanga og hans ledsagere, martyrer',
	boniface: 'Den hellige Bonifatius, biskop og martyr',
	norbert: 'Den hellige Norbert, biskop',
	ephrem: 'Den hellige Efrem Syrer, diakon og kirkelærer',
	barnabas: 'Den hellige Barnabas, apostel',
	'anthony-of-padua': 'Den hellige Antonius av Padua, prest og kirkelærer',
	romuald: 'Den hellige Romualdus, abbed',
	'aloysius-gonzaga': 'Den hellige Aloïsius Gonzaga, ordensbroder',
	'paulinus-of-nola': 'Den hellige Paulinus av Nola, biskop',
	'fisher-more': 'Den hellige John Fisher, biskop, og den hellige Thomas More, martyrer',
	'birth-of-john-the-baptist': 'Johannes Døperens fødsel',
	'cyril-of-alexandria': 'Den hellige Kyrillos av Alexandria, biskop og kirkelærer',
	irenaeus: 'Den hellige Ireneus, biskop, martyr og kirkelærer',
	'peter-and-paul': 'De hellige apostler Peter og Paulus',
	'first-martyrs-of-rome': 'Kirkens første martyrer i Roma',
	'thomas-apostle': 'Den hellige Thomas, apostel',
	'elizabeth-of-portugal': 'Den hellige Elisabeth av Portugal',
	'anthony-zaccaria': 'Den hellige Antonius Maria Zaccaria, prest',
	'maria-goretti': 'Den hellige Maria Goretti, jomfru og martyr',
	'augustine-zhao-rong': 'Den hellige Augustin Zhao Rong og hans ledsagere',
	benedict: 'Den hellige Benedikt, abbed',
	henry: 'Den hellige Henrik',
	camillus: 'Den hellige Camillus av Lellis, prest',
	bonaventure: 'Den hellige Bonaventura, biskop og kirkelærer',
	'our-lady-of-mount-carmel': 'Den salige jomfru Maria av Karmelberget',
	'lawrence-of-brindisi': 'Den hellige Laurentius av Brindisi, prest og kirkelærer',
	'mary-magdalene': 'Den hellige Maria Magdalena',
	bridget: 'Den hellige Birgitta, nonne',
	sharbel: 'Den hellige Charbel Makhlouf',
	james: 'Den hellige Jakob, apostel',
	'joachim-anne': 'Den hellige Joakim og den hellige Anna, jomfru Marias foreldre',
	'peter-chrysologus': 'Den hellige Peter Krysologos, biskop og kirkelærer',
	'ignatius-of-loyola': 'Den hellige Ignatius av Loyola, prest',
	'alphonsus-liguori': 'Den hellige Alfonso Maria de Liguori, biskop og kirkelærer',
	'eusebius-of-vercelli': 'Den hellige Eusebius av Vercelli, biskop',
	'peter-julian-eymard': 'Den hellige Peter Julian Eymard, prest',
	'john-vianney': 'Den hellige Johannes Maria Vianney, prest',
	'dedication-st-mary-major': 'Vigselsfesten for basilikaen Santa Maria Maggiore i Roma',
	transfiguration: 'Herrens forklarelse',
	'sixtus-ii': 'Den hellige Sixtus II, pave, og hans ledsagere, martyrer',
	cajetan: 'Den hellige Cajetan, prest',
	dominic: 'Den hellige Dominikus, prest',
	'teresa-benedicta': 'Den hellige Teresa Benedicta av Korset, nonne og martyr',
	lawrence: 'Den hellige Laurentius, diakon og martyr',
	clare: 'Den hellige Klara, jomfru',
	'jane-frances-de-chantal': 'Den hellige Johanna Fransiska av Chantal, nonne',
	'pontian-hippolytus': 'Den hellige Pontian, pave, og den hellige Hippolyt, prest',
	'maximilian-kolbe': 'Den hellige Maximilian Maria Kolbe, prest og martyr',
	assumption: 'Jomfru Marias opptagelse i himmelen',
	'stephen-of-hungary': 'Den hellige Stefan av Ungarn',
	'john-eudes': 'Den hellige Johannes Eudes, prest',
	bernard: 'Den hellige Bernhard av Clairvaux, abbed og kirkelærer',
	'pius-x': 'Den hellige Pius X, pave',
	'queenship-of-mary': 'Jomfru Marias dronningverdighet',
	'rose-of-lima': 'Den hellige Rosa av Lima, jomfru',
	bartholomew: 'Den hellige Bartolomeus, apostel',
	louis: 'Den hellige Ludvig av Frankrike',
	'joseph-calasanz': 'Den hellige Josef av Calasanz, prest',
	monica: 'Den hellige Monika, augustins mor',
	augustine: 'Den hellige Augustin, biskop og kirkelærer',
	'passion-of-john-the-baptist': 'Johannes Døperens martyrdød',
	'gregory-the-great': 'Den hellige Gregor den store, pave og kirkelærer',
	'teresa-of-calcutta': 'Den hellige Teresa av Calcutta, jomfru',
	'nativity-of-mary': 'Jomfru Marias fødsel',
	'peter-claver': 'Den hellige Peter Claverius, prest',
	'holy-name-of-mary': 'Jomfru Maria hellige Navn',
	'john-chrysostom': 'Den hellige Johannes Chrysostomos, biskop og kirkelærer',
	'exaltation-of-the-cross': 'Korsets opphøyelse',
	'our-lady-of-sorrows': 'Jomfru Marias smerter',
	'cornelius-cyprian': 'Den hellige Kornelius, pave, og den hellige Kyprian, biskop, martyrer',
	'robert-bellarmine': 'Den hellige Robert Bellarmin, biskop og kirkelærer',
	hildegard: 'Den hellige Hildegard av Bingen, jomfru og kirkelærer',
	januarius: 'Den hellige Januarius, biskop og martyr',
	'andrew-kim':
		'Den hellige Andreas Kim Taegon, prest, og den hellige Paulus Chong Hasang og deres ledsagere, martyrer',
	matthew: 'Den hellige Matteus, apostel og evangelist',
	'padre-pio': 'Den hellige Pius av Pietrelcina, prest',
	'cosmas-damian': 'Den hellige Kosmas og den hellige Damian, martyrer',
	'vincent-de-paul': 'Den hellige Vincent av Paul, prest',
	wenceslaus: 'Den hellige Venceslas, martyr',
	'lawrence-ruiz': 'Den hellige Lorenzo Ruiz og ledsagere, martyrer',
	archangels: 'De hellige erkeengler Mikael, Gabriel og Rafael',
	jerome: 'Den hellige Hieronymus, prest og kirkelærer',
	'therese-of-lisieux': 'Den hellige Terese av Jesusbarnet, jomfru og kirkelærer',
	'guardian-angels': 'De hellige verneengler',
	'francis-of-assisi': 'Den hellige Frans av Assisi',
	faustina: 'Den hellige Faustina Kowalska, jomfru',
	bruno: 'Den hellige Bruno, prest',
	'our-lady-of-the-rosary': 'Vår Frue av Rosenkransen',
	denis: 'Den hellige Dionysius, biskop, og hans ledsagere, martyrer',
	'john-leonardi': 'Den hellige Johannes Leonardi, prest',
	'john-henry-newman': 'Den hellige John Henry Newman, prest og kirkelærer',
	'john-xxiii': 'Den hellige Johannes XXIII, pave',
	'callistus-i': 'Den hellige Callistus I, pave og martyr',
	'teresa-of-avila': 'Den hellige Teresa av Avila, jomfru og kirkelærer',
	hedwig: 'Den hellige Hedvig, nonne',
	'margaret-mary-alacoque': 'Den hellige Margrete Marie Alacoque, jomfru',
	'ignatius-of-antioch': 'Den hellige Ignatius av Antiokia, biskop og martyr',
	luke: 'Den hellige Lukas, apostel og evangelist',
	'north-american-martyrs':
		'Den hellige Johannes av Brebeuf og den hellige Isaak Jogues, prester, og deres ledsagere, martyrer',
	'paul-of-the-cross': 'Den hellige Paul av korset, prest',
	'john-paul-ii': 'Den hellige Johannes Paul II, pave',
	'john-of-capistrano': 'Den hellige Johannes av Capestrano, prest',
	'anthony-mary-claret': 'Den hellige Antonius Maria Claret, biskop',
	'simon-jude': 'De hellige apostler Simon og Judas',
	'all-saints': 'Allehelgensdag',
	'martin-de-porres': 'Den hellige Martin av Porres, legbroder',
	'charles-borromeo': 'Den hellige Karl Borromeus, biskop',
	'dedication-of-the-lateran': 'Laterankirkens vigselsfest',
	'leo-the-great': 'Den hellige Leo den store, pave og kirkelærer',
	'martin-of-tours': 'Den hellige Martin av Tours, biskop',
	josaphat: 'Den hellige Josafat, biskop og martyr',
	'albert-the-great': 'Den hellige Albert den store, biskop og kirkelærer',
	'margaret-of-scotland': 'Den hellige Margrete av Skottland',
	gertrude: 'Den hellige Gjertrud, jomfru',
	'elizabeth-of-hungary': 'Den hellige Elisabeth av Ungarn',
	'dedication-of-peter-and-paul': 'Vigselsfesten for Peters og Paulus’ basilikaer i Roma',
	'presentation-of-mary': 'Jomfru Marias fremstilling i templet',
	cecilia: 'Den hellige Cecilia, jomfru og martyr',
	'clement-i': 'Den hellige Clemens I, pave og martyr',
	columban: 'Den hellige Kolumban, abbed',
	'andrew-dung-lac': 'Den hellige Andreas Dung-Lac, prest, og ledsagere, martyrer',
	andrew: 'Den hellige Andreas, apostel',
	'francis-xavier': 'Den hellige Frans Xavier, prest',
	'john-damascene': 'Den hellige Johannes av Damaskus, prest og kirkelærer',
	nicholas: 'Den hellige Nikolas av Myra, biskop',
	ambrose: 'Den hellige Ambrosius, biskop og kirkelærer',
	'immaculate-conception': 'Jomfru Marias uplettede unnfangelse',
	'juan-diego': 'Den hellige Juan Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Vår Frue av Loreto',
	'damasus-i': 'Den hellige Damasus I, pave',
	'our-lady-of-guadalupe': 'Vår Frue av Guadalupe',
	lucy: 'Den hellige Lucia, jomfru og martyr',
	'john-of-the-cross': 'Den hellige Johannes av Korset, prest og kirkelærer',
	'peter-canisius': 'Den hellige Peter Canisius, prest og kirkelærer',
	'john-of-kanty': 'Den hellige Johannes av Kanty, prest',
	stephen: 'Den hellige Stefan, Kirkens første martyr',
	'john-evangelist': 'Den hellige Johannes, apostel og evangelist',
	'holy-innocents': 'De uskyldige barn i Betlehem, martyrer',
	'thomas-becket': 'Den hellige Thomas Becket, biskop og martyr',
	'sylvester-i': 'Den hellige Sylvester I, pave'
};
