/**
 * The General Roman Calendar in Polish.
 *
 * Transcribed from GCatholic's Polish edition of Poland's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 205 of the Calendar's 218. The 13 absent are the ones Poland keeps someone
 * else on the day of — `stanislaus` among them — so this edition never
 * prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `plTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const pl: Record<string, string> = {
	'basil-gregory':
		'Świętych Bazylego Wielkiego i Grzegorza z Nazjanzu, biskupów i doktorów Kościoła',
	'holy-name-of-jesus': 'Najświętszego Imienia Jezus',
	'raymond-of-penyafort': 'Św. Rajmunda z Penyafort, prezbitera',
	hilary: 'Św. Hilarego, biskupa i doktora Kościoła',
	'anthony-abbot': 'Św. Antoniego, opata',
	fabian: 'Św. Fabiana, papieża i męczennika',
	sebastian: 'Św. Sebastiana, męczennika',
	agnes: 'Św. Agnieszki, dziewicy i męczennicy',
	'vincent-deacon': 'Św. Wincentego, diakona i męczennika',
	'francis-de-sales': 'Św. Franciszka Salezego, biskupa i doktora Kościoła',
	'conversion-of-paul': 'Nawrócenie św. Pawła, Apostoła',
	'timothy-titus': 'Świętych biskupów Tymoteusza i Tytusa',
	'angela-merici': 'Św. Anieli Merici, dziewicy',
	'thomas-aquinas': 'Św. Tomasza z Akwinu, prezbitera i doktora Kościoła',
	'john-bosco': 'Św. Jana Bosko, prezbitera',
	'presentation-of-the-lord': 'Ofiarowanie Pańskie',
	blaise: 'Św. Błażeja, biskupa i męczennika',
	ansgar: 'Św. Oskara, biskupa',
	agatha: 'Św. Agaty, dziewicy i męczennicy',
	'paul-miki': 'Świętych męczenników Pawła Miki i Towarzyszy',
	'jerome-emiliani': 'Św. Hieronima Emilianiego',
	'josephine-bakhita': 'Św. Józefiny Bakhity, dziewicy',
	scholastica: 'Św. Scholastyki, dziewicy',
	'our-lady-of-lourdes': 'Najświętszej Maryi Panny z Lourdes',
	'cyril-methodius': 'Świętych Cyryla, mnicha i Metodego, biskupa',
	'seven-founders': 'Świętych Siedmiu Założycieli Zakonu Serwitów Najświętszej Maryi Panny',
	'peter-damian': 'Św. Piotra Damianiego, biskupa i doktora Kościoła',
	'chair-of-peter': 'Katedry św. Piotra, Apostoła',
	polycarp: 'Św. Polikarpa, biskupa i męczennika',
	'gregory-of-narek': 'Św. Grzegorza z Nareku, opata i doktora Kościoła',
	casimir: 'Św. Kazimierza',
	'perpetua-felicity': 'Świętych męczennic Perpetuy i Felicyty',
	'john-of-god': 'Św. Jana Bożego, zakonnika',
	'frances-of-rome': 'Św. Franciszki Rzymianki, zakonnicy',
	patrick: 'Św. Patryka, biskupa',
	'cyril-of-jerusalem': 'Św. Cyryla Jerozolimskiego, biskupa i doktora Kościoła',
	joseph: 'Św. Józefa, Oblubieńca Najświętszej Maryi Panny',
	turibius: 'Św. Turybiusza z Mongrovejo, biskupa',
	annunciation: 'Zwiastowanie Pańskie',
	'francis-of-paola': 'Św. Franciszka z Paoli, pustelnika',
	isidore: 'Św. Izydora, biskupa i doktora Kościoła',
	'vincent-ferrer': 'Św. Wincentego Ferreriusza, prezbitera',
	'john-baptist-de-la-salle': 'Św. Jana Chrzciciela de la Salle, prezbitera',
	'martin-i': 'Św. Marcina I, papieża i męczennika',
	anselm: 'Św. Anzelma, biskupa i doktora Kościoła',
	adalbert: 'Św. Wojciecha, biskupa i męczennika',
	fidelis: 'Św. Fidelisa z Sigmaringen, prezbitera i męczennika',
	mark: 'Św. Marka, Ewangelisty',
	'peter-chanel': 'Św. Piotra Chanela, prezbitera i męczennika',
	'louis-de-montfort': 'Św. Ludwika Marii Grignion de Montfort, prezbitera',
	'catherine-of-siena': 'Św. Katarzyny Sieneńskiej, dziewicy i doktora Kościoła',
	'pius-v': 'Św. Piusa V, papieża',
	'joseph-the-worker': 'Św. Józefa, rzemieślnika',
	athanasius: 'Św. Atanazego, biskupa i doktora Kościoła',
	'john-of-avila': 'Św. Jan z Ávili, prezbitera i doktora Kościoła',
	'nereus-achilleus': 'Świętych męczenników Nereusza i Achillesa',
	pancras: 'Św. Pankracego, męczennika',
	'our-lady-of-fatima': 'Najświętszej Maryi Panny Fatimskiej',
	matthias: 'Św. Macieja, Apostoła',
	'john-i': 'Św. Jana I, papieża i męczennika',
	'bernardine-of-siena': 'Św. Bernardyna ze Sieny, prezbitera',
	'christopher-magallanes': 'Świętych męczenników Krzysztofa Magallanesa, prezbitera, i Towarzyszy',
	'rita-of-cascia': 'Św. Rity z Cascii, zakonnicy',
	bede: 'Św. Bedy Czcigodnego, prezbitera i doktora Kościoła',
	'gregory-vii': 'Św. Grzegorza VII, papieża',
	'mary-magdalene-de-pazzi': 'Św. Marii Magdaleny de Pazzi, dziewicy',
	'philip-neri': 'Św. Filipa Nereusza, prezbitera',
	'augustine-of-canterbury': 'Św. Augustyna z Canterbury, biskupa',
	visitation: 'Nawiedzenie Najświętszej Maryi Panny',
	justin: 'Św. Justyna, męczennika',
	'marcellinus-peter': 'Świętych męczenników Marcelina i Piotra',
	'charles-lwanga': 'Świętych męczenników Karola Lwangi i Towarzyszy',
	boniface: 'Św. Bonifacego, biskupa i męczennika',
	norbert: 'Św. Norberta, biskupa',
	ephrem: 'Św. Efrema, diakona i doktora Kościoła',
	barnabas: 'Św. Barnaby, Apostoła',
	'anthony-of-padua': 'Św. Antoniego z Padwy, prezbitera i doktora Kościoła',
	romuald: 'Św. Romualda, opata',
	'aloysius-gonzaga': 'Św. Alojzego Gonzagi, zakonnika',
	'paulinus-of-nola': 'Św. Paulina z Noli, biskupa',
	'fisher-more': 'Świętych męczenników Jana Fishera, biskupa i Tomasza More’a',
	'birth-of-john-the-baptist': 'Narodzenie św. Jana Chrzciciela',
	'cyril-of-alexandria': 'Św. Cyryla Aleksandryjskiego, biskupa i doktora Kościoła',
	irenaeus: 'Św. Ireneusza, biskupa, męczennika i doktora Kościoła',
	'peter-and-paul': 'Świętych Apostołów Piotra i Pawła',
	'first-martyrs-of-rome': 'Świętych pierwszych męczenników świętego Kościoła Rzymskiego',
	'thomas-apostle': 'Św. Tomasza, Apostoła',
	'elizabeth-of-portugal': 'Św. Elżbiety Portugalskiej',
	'anthony-zaccaria': 'Św. Antoniego Marii Zaccarii, prezbitera',
	'augustine-zhao-rong': 'Świętych męczenników Augustyna Zhao Rong, prezbitera, i Towarzyszy',
	benedict: 'Św. Benedykta, opata',
	camillus: 'Św. Kamila de Lellis, prezbitera',
	bonaventure: 'Św. Bonawentury, biskupa i doktora Kościoła',
	'our-lady-of-mount-carmel': 'Najświętszej Maryi Panny z Góry Karmel',
	'lawrence-of-brindisi': 'Św. Wawrzyńca z Brindisi, prezbitera i doktora Kościoła',
	'mary-magdalene': 'Św. Marii Magdaleny',
	bridget: 'Św. Brygidy, zakonnicy',
	james: 'Św. Jakuba, Apostoła',
	'joachim-anne': 'Świętych Joachima i Anny, rodziców Najświętszej Maryi Panny',
	'martha-mary-lazarus': 'Świętych Marty, Marii i Łazarza',
	'peter-chrysologus': 'Św. Piotra Chryzologa, biskupa i doktora Kościoła',
	'ignatius-of-loyola': 'Św. Ignacego z Loyoli, prezbitera',
	'alphonsus-liguori': 'Św. Alfonsa Marii Liguoriego, biskupa i doktora Kościoła',
	'eusebius-of-vercelli': 'Św. Euzebiusza z Vercelli, biskupa',
	'peter-julian-eymard': 'Św. Piotra Juliani Eymarda, prezbitera',
	'john-vianney': 'Św. Jana Marii Vianneya, prezbitera',
	'dedication-st-mary-major': 'Rocznica poświęcenia rzymskiej Bazyliki Najświętszej Maryi Panny',
	transfiguration: 'Przemienienie Pańskie',
	'sixtus-ii': 'Świętych męczenników Sykstusa II, papieża, i Towarzyszy',
	cajetan: 'Św. Kajetana, prezbitera',
	dominic: 'Św. Dominika, prezbitera',
	'teresa-benedicta': 'Św. Teresy Benedykty od Krzyża, dziewicy i męczennicy',
	lawrence: 'Św. Wawrzyńca, diakona i męczennika',
	clare: 'Św. Klary, dziewicy',
	'jane-frances-de-chantal': 'Św. Joanny Franciszki de Chantal, zakonnicy',
	'pontian-hippolytus': 'Świętych męczenników Poncjana, papieża, i Hipolita, prezbitera',
	'maximilian-kolbe': 'Św. Maksymiliana Marii Kolbego, prezbitera i męczennika',
	assumption: 'Wniebowzięcie Najświętszej Maryi Panny',
	'stephen-of-hungary': 'Św. Stefana Węgierskiego',
	'john-eudes': 'Św. Jana Eudesa, prezbitera',
	bernard: 'Św. Bernarda, opata i doktora Kościoła',
	'pius-x': 'Św. Piusa X, papieża',
	'queenship-of-mary': 'Najświętszej Maryi Panny, Królowej',
	'rose-of-lima': 'Św. Róży z Limy, dziewicy',
	bartholomew: 'Św. Bartłomieja, Apostoła',
	louis: 'Św. Ludwika',
	'joseph-calasanz': 'Św. Józefa Kalasantego, prezbitera',
	monica: 'Św. Moniki',
	augustine: 'Św. Augustyna, biskupa i doktora Kościoła',
	'passion-of-john-the-baptist': 'Męczeństwo św. Jana Chrzciciela',
	'gregory-the-great': 'Św. Grzegorza Wielkiego, papieża i doktora Kościoła',
	'teresa-of-calcutta': 'Św. Teresa z Kalkuty, męczennicy',
	'nativity-of-mary': 'Narodzenie Najświętszej Maryi Panny',
	'peter-claver': 'Św. Piotra Klawera, prezbitera',
	'holy-name-of-mary': 'Najświętszego Imienia Maryi',
	'john-chrysostom': 'Św. Jana Chryzostoma, biskupa i doktora Kościoła',
	'exaltation-of-the-cross': 'Podwyższenie Krzyża Świętego',
	'our-lady-of-sorrows': 'Najświętszej Maryi Panny Bolesnej',
	'cornelius-cyprian': 'Świętych męczenników Korneliusza, papieża, i Cypriana, biskupa',
	'robert-bellarmine': 'Św. Roberta Bellarmina, biskupa i doktora Kościoła',
	hildegard: 'Św. Hildegardy z Bingen, dziewicy i doktora Kościoła',
	januarius: 'Św. Januarego, biskupa i męczennika',
	'andrew-kim':
		'Świętych męczenników Andrzeja Kim Taegon, prezbitera, Pawła Chong Hasang i Towarzyszy',
	matthew: 'Św. Mateusza, Apostoła i Ewangelisty',
	'padre-pio': 'Św. Pio z Pietrelciny, prezbitera',
	'cosmas-damian': 'Świętych męczenników Kosmy i Damiana',
	'vincent-de-paul': 'Św. Wincentego à Paulo, prezbitera',
	wenceslaus: 'Św. Wacława, męczennika',
	archangels: 'Świętych Archaniołów Michała, Gabriela i Rafała',
	jerome: 'Św. Hieronima, prezbitera i doktora Kościoła',
	'therese-of-lisieux': 'Św. Teresy od Dzieciątka Jezus, dziewicy i doktora Kościoła',
	'guardian-angels': 'Świętych Aniołów Stróżów',
	'francis-of-assisi': 'Św. Franciszka z Asyżu, zakonnika',
	faustina: 'Św. Faustyny Kowalskiej, dziewicy',
	bruno: 'Św. Brunona, prezbitera',
	'our-lady-of-the-rosary': 'Najświętszej Maryi Panny Różańcowej',
	denis: 'Świętych męczenników Dionizego, biskupa, i Towarzyszy',
	'john-leonardi': 'Św. Jana Leonardiego, prezbitera',
	'john-henry-newman': 'Św. Jan Henryk Newman, prezbitera I doktora Kościoła',
	'john-xxiii': 'Św. Jana XXIII, papieża',
	'callistus-i': 'Św. Kaliksta I, papieża i męczennika',
	'teresa-of-avila': 'Św. Teresy od Jezusa, dziewicy i doktora Kościoła',
	'ignatius-of-antioch': 'Św. Ignacego Antiocheńskiego, biskupa i męczennika',
	luke: 'Św. Łukasza, Ewangelisty',
	'north-american-martyrs':
		'Świętych męczenników Jana de Brebeuf, Izaaka Jogues’a, prezbiterów, i Towarzyszy',
	'paul-of-the-cross': 'Św. Pawła od Krzyża, prezbitera',
	'john-paul-ii': 'Św. Jana Pawła II, papieża',
	'john-of-capistrano': 'Św. Jana Kapistrana, prezbitera',
	'anthony-mary-claret': 'Św. Antoniego Marii Clareta, biskupa',
	'simon-jude': 'Świętych Apostołów Szymona i Judy Tadeusza',
	'all-saints': 'Wszystkich Świętych',
	'martin-de-porres': 'Św. Marcina de Porres, zakonnika',
	'charles-borromeo': 'Św. Karola Boremeusza, biskupa',
	'dedication-of-the-lateran': 'Rocznica poświęcenia Bazyliki Laterańskiej',
	'leo-the-great': 'Św. Leona Wielkiego, papieża i doktora Kościoła',
	'martin-of-tours': 'Św. Marcina z Tours, biskupa',
	josaphat: 'Św. Jozafata, biskupa i męczennika',
	'albert-the-great': 'Św. Alberta Wielkiego, biskupa i doktora Kościoła',
	'margaret-of-scotland': 'Św. Małgorzaty Szkockiej',
	gertrude: 'Św. Gertrudy, dziewicy',
	'elizabeth-of-hungary': 'Św. Elżbiety Węgierskiej, zakonnicy',
	'presentation-of-mary': 'Ofiarowanie Najświętszej Maryi Panny',
	cecilia: 'Św. Cecylii, dziewicy i męczennicy',
	'clement-i': 'Św. Klemensa I, papieża i męczennika',
	columban: 'Św. Kolumbana, opata',
	'andrew-dung-lac': 'Świętych męczenników Andrzeja Dung-Lac, prezbitera, i Towarzyszy',
	'catherine-of-alexandria': 'Św. Katarzyny Aleksandryjskiej, dziewicy i męczennicy',
	andrew: 'Św. Andrzeja, Apostoła',
	'francis-xavier': 'Św. Franciszka Ksawerego, prezbitera',
	'john-damascene': 'Św. Jana Damasceńskiego, prezbitera i doktora Kościoła',
	nicholas: 'Św. Mikołaja, biskupa',
	ambrose: 'Św. Ambrożego, biskupa i doktora Kościoła',
	'immaculate-conception': 'Niepokalane poczęcie Najświętszej Maryi Panny',
	'juan-diego': 'Św. Jana Diego Cuauhtlatoatzin',
	'our-lady-of-loreto': 'Najświętszej Maryi Panny Loretańskiej',
	'damasus-i': 'Św. Damazego I, papieża',
	'our-lady-of-guadalupe': 'Najświętszej Maryi Panny z Guadalupe',
	lucy: 'Św. Łucji, dziewicy i męczennicy',
	'john-of-the-cross': 'Św. Jana od Krzyża, prezbitera i doktora Kościoła',
	'peter-canisius': 'Św. Piotra Kanizjusza, prezbitera i doktora Kościoła',
	stephen: 'Św. Szczepana, pierwszego męczennika',
	'john-evangelist': 'Św. Jana, Apostoła i Ewangelisty',
	'holy-innocents': 'Świętych Młodziaków, męczenników',
	'thomas-becket': 'Św. Tomasza Becketa, biskupa i męczennika',
	'sylvester-i': 'Św. Sylwestra I, papieża',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Narodzenie Pańskie',
	'holy-family': 'Świętej Rodziny Jezusa, Maryi i Józefa',
	'mary-mother-of-god': 'Świętej Bożej Rodzicielki Maryi',
	'christmas-2-sunday': 'II Niedziela po Bożym Narodzeniu',
	epiphany: 'Objawienie Pańskie',
	'baptism-of-the-lord': 'Chrzest Pański',
	'ash-wednesday': 'Środa Popielcowa',
	'palm-sunday': 'Niedziela Palmowa Męki Pańskiej',
	'holy-thursday': 'Wielki Czwartek: Wieczerzy Pańskiej',
	'good-friday': 'Wielki Piątek: Męki Pańskiej',
	'holy-saturday': 'Wielka Sobota',
	'easter-sunday': 'Niedziela Zmartwychwstania Pańskiego',
	'easter-2-sunday': 'II Niedziela Wielkanocna czyli Miłosierdzia Bożego',
	ascension: 'Wniebowstąpienie Pańskie',
	pentecost: 'Niedziela Zesłania Ducha Świętego',
	trinity: 'Najświętszej Trójcy',
	'corpus-christi': 'Najświętszego Ciała i Krwi Chrystusa',
	'sacred-heart': 'Najświętszego Serca Pana Jezusa',
	'immaculate-heart': 'Niepokalanego Serca Najświętszej Maryi Panny',
	'mary-mother-of-the-church': 'Najświętszej Maryi Panny, Matki Kościoła',
	'christ-the-king': 'Jezusa Chrystusa, Króla Wszechświata'
};

/**
 * The Proper of Time in Polish, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const plTemporal: TemporalNames = {
	days: { 1: 'Poniedziałek', 2: 'Wtorek', 3: 'Środa', 4: 'Czwartek', 5: 'Piątek', 6: 'Sobota' },
	weeks: {
		1: 'I',
		2: 'II',
		3: 'III',
		4: 'IV',
		5: 'V',
		6: 'VI',
		7: 'VII',
		8: 'VIII',
		9: 'IX',
		10: 'X',
		11: 'XI',
		12: 'XII',
		13: 'XIII',
		14: 'XIV',
		15: 'XV',
		16: 'XVI',
		17: 'XVII',
		18: 'XVIII',
		19: 'XIX',
		20: 'XX',
		21: 'XXI',
		22: 'XXII',
		23: 'XXIII',
		24: 'XXIV',
		25: 'XXV',
		26: 'XXVI',
		27: 'XXVII',
		28: 'XXVIII',
		29: 'XXIX',
		30: 'XXX',
		31: 'XXXI',
		32: 'XXXII',
		33: 'XXXIII',
		34: 'XXXIV'
	},
	octave: { 5: 'V', 6: 'VI', 7: 'VII' },
	sunday: {
		advent: '{week} Niedziela Adwentu',
		lent: '{week} Niedziela Wielkiego Postu',
		easter: '{week} Niedziela Wielkanocna',
		ordinary: '{week} Niedziela Zwykła'
	},
	weekday: {
		advent: '{day} {week} tygodnia Adwentu',
		lent: '{day} {week} tygodnia Wielkiego Postu',
		easter: '{day} {week} Tygodnia Wielkanocnego',
		ordinary: '{day} {week} tygodnia zwykłego'
	},
	holyWeek: {
		form: '{day}',
		days: { 1: 'Wielki Poniedziałek', 2: 'Wielki Wtorek', 3: 'Wielka Środa' }
	},
	afterAshes: '{day} po Popielcu',
	afterEpiphany: '{day} po Objawieniu Pańskim',
	christmasWeekday: '{day} przed Objawieniem Pańskim',
	easterOctave: '{day} w Oktawie Wielkanocy',
	christmasOctave: '{nth} dzień w oktawie Narodzenia Pańskiego'
};
