/**
 * The General Roman Calendar in Slovak.
 *
 * Transcribed from GCatholic's Slovak edition of Slovakia's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 213 of the Calendar's 218. The 5 absent are the ones Slovakia keeps
 * someone else on the day of — `cyril-methodius` among them — so this
 * edition never prints them and they go on falling back to English, which is
 * what `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `skTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const sk: Record<string, string> = {
	'basil-gregory': 'Svätých Bazila Veľkého a Gregora Nazianzského, biskupov a učiteľov Cirkvi',
	'holy-name-of-jesus': 'Najsvätejšieho mena Ježiš',
	'raymond-of-penyafort': 'Svätého Rajmunda z Peňafortu, kňaza',
	hilary: 'Svätého Hilára, biskupa, učiteľa Cirkvi',
	'anthony-abbot': 'Svätého Antona, opáta',
	fabian: 'Svätého Fabiána, pápeža a mučeníka',
	sebastian: 'Svätého Šebastiána, mučeníka',
	agnes: 'Svätej Agnesy, panny a mučenice',
	'vincent-deacon': 'Svätého Vincenta, diakona a mučeníka',
	'francis-de-sales': 'Svätého Františka Saleského, biskupa a učiteľa Cirkvi',
	'conversion-of-paul': 'Obrátenie svätého Pavla, apoštola',
	'timothy-titus': 'Svätých Timoteja a Títa, biskupov',
	'angela-merici': 'Svätej Angely Merici, panny',
	'thomas-aquinas': 'Svätého Tomáša Akvinského, kňaza a učiteľa Cirkvi',
	'john-bosco': 'Svätého Jána Boska, kňaza',
	'presentation-of-the-lord': 'Obetovanie Pána',
	blaise: 'Svätého Blažeja, biskupa a mučeníka',
	ansgar: 'Svätého Oskára, biskupa',
	agatha: 'Svätej Agáty, panny a mučenice',
	'paul-miki': 'Svätého Pavla Mikiho a spoločníkov, mučeníkov',
	'jerome-emiliani': 'Svätého Hieronyma Emilianiho',
	'josephine-bakhita': 'Svätej Jozefíny Bakhity, panny',
	scholastica: 'Svätej Školastiky, panny',
	'our-lady-of-lourdes': 'Preblahoslavenej Panny Márie Lurdskej',
	'seven-founders': 'Siedmich svätých zakladateľov rehole Služobníkov Panny Márie',
	'peter-damian': 'Svätého Petra Damianiho, biskupa a učiteľa Cirkvi',
	'chair-of-peter': 'Katedra svätého Petra, apoštola',
	polycarp: 'Svätého Polykarpa, biskupa a mučeníka',
	'gregory-of-narek': 'Svätého Gregora Narekatsi, opáta a učiteľa Cirkvi',
	casimir: 'Svätého Kazimíra',
	'perpetua-felicity': 'Svätých Perpetuy a Felicity, mučeníc',
	'john-of-god': 'Svätého Jána z Boha, rehoľníka',
	'frances-of-rome': 'Svätej Františky Rímskej, rehoľníčky',
	patrick: 'Svätého Patrika, biskupa',
	'cyril-of-jerusalem': 'Svätého Cyrila Jeruzalemského, biskupa a učiteľa Cirkvi',
	joseph: 'Svätého Jozefa, ženícha Panny Márie',
	turibius: 'Svätého Turibia de Mongrovejo, biskupa',
	annunciation: 'Zvestovanie Pána',
	'francis-of-paola': 'Svätého Františka z Paoly, pustovníka',
	isidore: 'Svätého Izidora, biskupa a učiteľa Cirkvi',
	'vincent-ferrer': 'Svätého Vincenta Ferrera, kňaza',
	'john-baptist-de-la-salle': 'Svätého Jána Krstiteľa de la Salle, kňaza',
	stanislaus: 'Svätého Stanislava, biskupa a mučeníka',
	'martin-i': 'Svätého Martina I., pápeža a mučeníka',
	anselm: 'Svätého Anzelma, biskupa a učiteľa Cirkvi',
	adalbert: 'Svätého Vojtecha, biskupa a mučeníka',
	fidelis: 'Svätého Fidéla zo Sigmaringenu, kňaza a mučeníka',
	mark: 'Svätého Marka, evanjelistu',
	'peter-chanel': 'Svätého Petra Chanela, kňaza a mučeníka',
	'louis-de-montfort': 'Svätého Ľudovíta Máriu Grigniona z Montfortu, kňaza',
	'catherine-of-siena': 'Svätej Kataríny Sienskej, panny a učiteľky Cirkvi',
	'pius-v': 'Svätého Pia V., pápeža',
	'joseph-the-worker': 'Svätého Jozefa, robotníka',
	athanasius: 'Svätého Atanáza, biskupa a učiteľa Cirkvi',
	'philip-james': 'Svätých Filipa a Jakuba, apoštolov',
	'john-of-avila': 'Svätého Jána z Ávily, kňaza a učiteľa Cirkvi',
	'nereus-achilleus': 'Svätých Nerea a Achila, mučeníkov',
	pancras: 'Svätého Pankráca, mučeníka',
	'our-lady-of-fatima': 'Blahoslavenej Panny Márie Fatimskej',
	matthias: 'Svätého Mateja, apoštola',
	'john-i': 'Svätého Jána I., pápeža a mučeníka',
	'bernardine-of-siena': 'Svätého Bernardína Sienského, kňaza',
	'christopher-magallanes': 'Svätého Krištofa Magallanesa, kňaza, a spoločníkov, mučeníkov',
	'rita-of-cascia': 'Svätej Rity z Cascie, rehoľníčky',
	bede: 'Svätého Bédu Ctihodného, kňaza a učiteľa Cirkvi',
	'gregory-vii': 'Svätého Gregora VII., pápeža',
	'mary-magdalene-de-pazzi': 'Svätej Márie Magdalény de’ Pazzi, panny',
	'philip-neri': 'Svätého Filipa Neriho, kňaza',
	'augustine-of-canterbury': 'Svätého Augustína z Canterbury, biskupa',
	'paul-vi': 'Svätého Pavla VI., pápeža',
	justin: 'Svätého Justína, mučeníka',
	'marcellinus-peter': 'Svätých Marcelína a Petra, mučeníkov',
	'charles-lwanga': 'Svätých Karola Lwangu a spoločníkov, mučeníkov',
	boniface: 'Svätého Bonifáca, biskupa a mučeníka',
	norbert: 'Svätého Norberta, biskupa',
	ephrem: 'Svätého Efréma, diakona a učiteľa Cirkvi',
	barnabas: 'Svätého Barnabáša, apoštola',
	'anthony-of-padua': 'Svätého Antona Paduánskeho, kňaza a učiteľa Cirkvi',
	romuald: 'Svätého Romualda, opáta',
	'aloysius-gonzaga': 'Svätého Alojza Gonzágu, rehoľníka',
	'paulinus-of-nola': 'Svätého Pavlína z Noly, biskupa',
	'fisher-more': 'Svätých Jána Fišera, biskupa, a Tomáša Mórusa, mučeníkov',
	'birth-of-john-the-baptist': 'Narodenie svätého Jána Krstiteľa',
	'cyril-of-alexandria': 'Svätého Cyrila Alexandrijského, biskupa a učiteľa Cirkvi',
	irenaeus: 'Svätého Ireneja, biskupa, mučeníka a učiteľa Cirkvi',
	'peter-and-paul': 'Svätých Petra a Pavla, apoštolov',
	'first-martyrs-of-rome': 'Prvých svätých mučeníkov Cirkvi v Ríme',
	'thomas-apostle': 'Svätého Tomáša, apoštola',
	'elizabeth-of-portugal': 'Svätej Alžbety Portugalskej',
	'maria-goretti': 'Svätej Márie Goretti, panny a mučenice',
	'augustine-zhao-rong': 'Svätých Augustína Zhao Ronga, kňaza, a spoločníkov, mučeníkov',
	benedict: 'Svätého Benedikta, opáta',
	henry: 'Svätého Henricha',
	camillus: 'Svätého Kamila de Lellis, kňaza',
	bonaventure: 'Svätého Bonaventúru, biskupa a učiteľa Cirkvi',
	'our-lady-of-mount-carmel': 'Preblahoslavenej Panny Márie Karmelskej',
	apollinaris: 'Svätého Apolinára, biskupa a mučeníka',
	'lawrence-of-brindisi': 'Svätého Vavrinca z Brindisi, kňaza a učiteľa Cirkvi',
	'mary-magdalene': 'Svätej Márie Magdalény',
	bridget: 'Svätej Brigity, rehoľníčky',
	sharbel: 'Svätého Šarbela Machlúfa, kňaza',
	james: 'Svätého Jakuba, apoštola',
	'joachim-anne': 'Svätých Joachima a Anny, rodičov Panny Márie',
	'martha-mary-lazarus': 'Svätých Marty, Márie a Lazára',
	'peter-chrysologus': 'Svätého Petra Chryzológa, biskupa a učiteľa Cirkvi',
	'ignatius-of-loyola': 'Svätého Ignáca z Loyoly, kňaza',
	'alphonsus-liguori': 'Svätého Alfonza Máriu de’ Liguori, biskupa a učiteľa Cirkvi',
	'eusebius-of-vercelli': 'Svätého Euzébia Vercellského, biskupa',
	'peter-julian-eymard': 'Svätého Petra Juliána Eymarda, kňaza',
	'john-vianney': 'Svätého Jána Máriu Vianneya, kňaza',
	'dedication-st-mary-major': 'Výročie posviacky Hlavnej mariánskej baziliky v Ríme',
	transfiguration: 'Premenenie Pána',
	'sixtus-ii': 'Svätých Sixta II., pápeža, a jeho spoločníkov, mučeníkov',
	cajetan: 'Svätého Kajetána, kňaza',
	dominic: 'Svätého Dominika, kňaza',
	'teresa-benedicta': 'Svätej Terézie Benedikty od Kríža, panny a mučenice',
	lawrence: 'Svätého Vavrinca, diakona a mučeníka',
	clare: 'Svätej Kláry, panny',
	'jane-frances-de-chantal': 'Svätej Jany Františky de Chantal, rehoľníčky',
	'pontian-hippolytus': 'Svätých Ponciána, pápeža, a Hipolyta, kňaza, mučeníkov',
	'maximilian-kolbe': 'Svätého Maximiliána Máriu Kolbeho, kňaza a mučeníka',
	assumption: 'Nanebovzatie Panny Márie',
	'stephen-of-hungary': 'Svätého Štefana Uhorského',
	'john-eudes': 'Svätého Jána Eudesa, kňaza',
	bernard: 'Svätého Bernarda, opáta a učiteľa Cirkvi',
	'pius-x': 'Svätého Pia X., pápeža',
	'queenship-of-mary': 'Panny Márie Kráľovnej',
	'rose-of-lima': 'Svätej Ruženy Limskej, panny',
	bartholomew: 'Svätého Bartolomeja, apoštola',
	louis: 'Svätého Ľudovíta',
	'joseph-calasanz': 'Svätého Jozefa Kalazanského, kňaza',
	monica: 'Svätej Moniky',
	augustine: 'Svätého Augustína, biskupa a učiteľa Cirkvi',
	'passion-of-john-the-baptist': 'Mučenícka smrť svätého Jána Krstiteľa',
	'gregory-the-great': 'Svätého Gregora Veľkého, pápeža a učiteľa Cirkvi',
	'teresa-of-calcutta': 'Svätej Tereza z Kalkaty, panny',
	'nativity-of-mary': 'Narodenie Panny Márie',
	'peter-claver': 'Svätého Petra Clavera, kňaza',
	'holy-name-of-mary': 'Najsvätejšieho mena Panny Márie',
	'john-chrysostom': 'Svätého Jána Zlatoústeho, biskupa a učiteľa Cirkvi',
	'exaltation-of-the-cross': 'Povýšenie Svätého kríža',
	'cornelius-cyprian': 'Svätých Kornélia, pápeža, a Cypriána, biskupa, mučeníkov',
	'robert-bellarmine': 'Svätého Róberta Bellarmína, biskupa a učiteľa Cirkvi',
	hildegard: 'Svätej Hildegarda z Bingenu, panny a učiteľky Cirkvi',
	januarius: 'Svätého Januára, biskupa a mučeníka',
	'andrew-kim': 'Svätých Ondreja Kima Taegona, kňaza, Pavla Chonga Hasanga a spoločníkov, mučeníko',
	matthew: 'Svätého Matúša, apoštola a evanjelistu',
	'padre-pio': 'Svätého Pia z Pietrelčiny, kňaza',
	'cosmas-damian': 'Svätých Kozmu a Damiána, mučeníkov',
	'vincent-de-paul': 'Svätého Vincenta de Paul, kňaza',
	wenceslaus: 'Svätého Václava, mučeníka',
	'lawrence-ruiz': 'Svätého Vavrinca Ruiza a spoločníkov, mučeníkov',
	archangels: 'Svätých Michala, Gabriela a Rafaela, archanjelov',
	jerome: 'Svätého Hieronyma, kňaza a učiteľa Cirkvi',
	'therese-of-lisieux': 'Svätej Terézie od Dieťaťa Ježiša, panny a učiteľky Cirkvi',
	'guardian-angels': 'Svätých anjelov strážcov',
	'francis-of-assisi': 'Svätého Františka Assiského, rehoľníka',
	faustina: 'Svätej Faustíny Kowalskej, panny',
	bruno: 'Svätého Bruna, kňaza',
	'our-lady-of-the-rosary': 'Ružencovej Panny Márie',
	denis: 'Svätého Dionýza, biskupa, a spoločníkov, mučeníkov',
	'john-leonardi': 'Svätého Jána Leonardiho, kňaza',
	'john-henry-newman': 'Svätého John Henry Newman, kňaza a učiteľa Cirkvi',
	'john-xxiii': 'Svätého Jána XXIII., pápeža',
	'callistus-i': 'Svätého Kalixta I., pápeža a mučeníka',
	'teresa-of-avila': 'Svätej Terézie od Ježiša, panny a učiteľky Cirkvi',
	hedwig: 'Svätej Hedvigy, rehoľníčky',
	'margaret-mary-alacoque': 'Svätej Margity Márie Alacoque, panny',
	'ignatius-of-antioch': 'Svätého Ignáca Antiochijského, biskupa a mučeníka',
	luke: 'Svätého Lukáša, evanjelistu',
	'north-american-martyrs':
		'Svätých Jána de Brébeuf a Izáka Jogues, kňazov, a ich spoločníkov, mučeníkov',
	'paul-of-the-cross': 'Svätého Pavla z Kríža, kňaza',
	'john-paul-ii': 'Svätého Jána Pavla II., pápeža',
	'john-of-capistrano': 'Svätého Jána Kapistránskeho, kňaza',
	'anthony-mary-claret': 'Svätého Antona Máriu Clareta, biskupa',
	'simon-jude': 'Svätých Šimona a Júdu, apoštolov',
	'all-saints': 'Všetkých svätých',
	'martin-de-porres': 'Svätého Martina de Porres, rehoľníka',
	'charles-borromeo': 'Svätého Karola Borromejského, biskupa',
	'dedication-of-the-lateran': 'Výročie posviacky Lateránskej baziliky',
	'leo-the-great': 'Svätého Leva Veľkého, pápeža a učiteľa Cirkvi',
	'martin-of-tours': 'Svätého Martina z Tours, biskupa',
	josaphat: 'Svätého Jozafáta, biskupa a mučeníka',
	'albert-the-great': 'Svätého Alberta Veľkého, biskupa a učiteľa Cirkvi',
	'margaret-of-scotland': 'Svätej Margity Škótskej',
	gertrude: 'Svätej Gertrúdy, panny',
	'elizabeth-of-hungary': 'Svätej Alžbety Uhorskej, rehoľníčky',
	'dedication-of-peter-and-paul': 'Výročie posviacky bazilík svätých Petra a Pavla, apoštolov',
	'presentation-of-mary': 'Obetovanie Panny Márie',
	cecilia: 'Svätej Cecílie, panny a mučenice',
	'clement-i': 'Svätého Klementa I., pápeža a mučeníka',
	columban: 'Svätého Kolumbána, opáta',
	'andrew-dung-lac': 'Svätého Ondreja Dung-Laka, kňaza, a spoločníkov, mučeníkov',
	'catherine-of-alexandria': 'Svätej Kataríny Alexandrijskej, panny a mučenice',
	andrew: 'Svätého Ondreja, apoštola',
	'francis-xavier': 'Svätého Františka Xaverského, kňaza',
	'john-damascene': 'Svätého Jána Damascénskeho, kňaza a učiteľa Cirkvi',
	nicholas: 'Svätého Mikuláša, biskupa',
	ambrose: 'Svätého Ambróza, biskupa a učiteľa Cirkvi',
	'immaculate-conception': 'Nepoškvrnené počatie Panny Márie',
	'juan-diego': 'Svätého Jána Didaka Cuauhtlatoatzina',
	'our-lady-of-loreto': 'Preblahoslavenej Panny Márie Loretánskej',
	'damasus-i': 'Svätého Damaza I., pápeža',
	'our-lady-of-guadalupe': 'Preblahoslavenej Panny Márie Guadalupskej',
	lucy: 'Svätej Lucie, panny a mučenice',
	'john-of-the-cross': 'Svätého Jána z Kríža, kňaza a učiteľa Cirkvi',
	'peter-canisius': 'Svätého Petra Kanízia, kňaza a učiteľa Cirkvi',
	'john-of-kanty': 'Svätého Jána Kentského, kňaza',
	stephen: 'Svätého Štefana, prvého mučeníka',
	'john-evangelist': 'Svätého Jána, apoštola a evanjelistu',
	'holy-innocents': 'Svätých Neviniatok, mučeníkov',
	'thomas-becket': 'Svätého Tomáša Becketa, biskupa a mučeníka',
	'sylvester-i': 'Svätého Silvestra I., pápeža',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Narodenie Pána',
	'holy-family': 'Svätej rodiny Ježiša, Márie a Jozefa',
	'mary-mother-of-god': 'Panny Márie Bohorodičky',
	'christmas-2-sunday': '2. nedeľa po narodení Pána',
	epiphany: 'Zjavenie Pána',
	'baptism-of-the-lord': 'Krst Krista Pána',
	'ash-wednesday': 'Popolcová streda',
	'palm-sunday': 'Nedeľa utrpenia Pána',
	'holy-thursday': 'Štvrtok Veľkého týždňa',
	'good-friday': 'Veľký piatok – Slávenie utrpenia a smrti Pána',
	'holy-saturday': 'Biela sobota',
	'easter-sunday': 'Veľkonočná nedeľa Pánovho zmŕtvychvstania',
	'easter-2-sunday': '2. Veľkonočná nedeľa (Nedeľa Božieho milosrdenstva)',
	ascension: 'Nanebovstúpenie Pána',
	pentecost: 'Zoslanie Ducha Svätého',
	trinity: 'Najsvätejšej Trojice',
	'corpus-christi': 'Najsvätejšieho Kristovho Tela a Krvi',
	'sacred-heart': 'Najsvätejšieho Srdca Ježišovho',
	'immaculate-heart': 'Nepoškvrneného Srdca Panny Márie',
	'mary-mother-of-the-church': 'Preblahoslavenej Panny Márie, Matky Cirkvi',
	'christ-the-king': 'Krista Kráľa'
};

/**
 * The Proper of Time in Slovak, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const skTemporal: TemporalNames = {
	days: { 1: 'Pondelok', 2: 'Utorok', 3: 'Streda', 4: 'Štvrtok', 5: 'Piatok', 6: 'Sobota' },
	weeks: {
		1: '1',
		2: '2',
		3: '3',
		4: '4',
		5: '5',
		6: '6',
		7: '7',
		8: '8',
		9: '9',
		10: '10',
		11: '11',
		12: '12',
		13: '13',
		14: '14',
		15: '15',
		16: '16',
		17: '17',
		18: '18',
		19: '19',
		20: '20',
		21: '21',
		22: '22',
		23: '23',
		24: '24',
		25: '25',
		26: '26',
		27: '27',
		28: '28',
		29: '29',
		30: '30',
		31: '31',
		32: '32',
		33: '33',
		34: '34'
	},
	octave: { 5: 'Piaty', 6: 'Šiesty', 7: 'Siedmy' },
	sunday: {
		advent: '{week}. adventná nedeľa',
		lent: '{week}. pôstna nedeľa',
		easter: '{week}. veľkonočná nedeľa',
		ordinary: '{week}. nedeľa v Cezročnom období'
	},
	weekday: {
		advent: '{day} po {week}. adventnej nedeli',
		lent: '{day} po {week}. pôstnej nedeli',
		easter: '{day} po {week}. veľkonočnej nedeli',
		ordinary: '{day} {week}. týždňa v Cezročnom období'
	},
	holyWeek: '{day} Veľkého týždňa',
	afterAshes: '{day} po popolcovej strede',
	afterEpiphany: '{day} po Zjavení Pána',
	christmasWeekday: '{day} vo Vianočnom období',
	easterOctave: '{day} vo Veľkonočnej oktáve',
	christmasOctave: '{nth} deň oktávy narodenia Pána'
};
