/**
 * The General Roman Calendar in Swedish.
 *
 * Transcribed from GCatholic's Swedish edition of Sweden's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 212 of the Calendar's 218. The 6 absent are the ones Sweden keeps someone
 * else on the day of — `blaise` among them — so this edition never prints
 * them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `svTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const sv: Record<string, string> = {
	'basil-gregory': 'S:t Basilios den store och S:t Gregorios av Nazianzos',
	'holy-name-of-jesus': 'Jesu heliga namn',
	'raymond-of-penyafort': 'S:t Raimond av Peñafort, präst',
	hilary: 'S:t Hilarius av Poitiers, biskop och kyrkolärare',
	'anthony-abbot': 'S:t Antonius, abbot',
	fabian: 'S:t Fabianus, påve och martyr',
	sebastian: 'S:t Sebastian, martyr',
	agnes: 'S:ta Agnes, jungfru och martyr',
	'vincent-deacon': 'S:t Vincentius av Saragossa, diakon och martyr',
	'francis-de-sales': 'S:t François de Sales, biskop och kyrkolärare',
	'conversion-of-paul': 'Den helige Aposteln Paulus Omvändelse',
	'timothy-titus': 'S:t Timotheos och S:t Titus, biskopar',
	'angela-merici': 'S:ta Angela Merici, jungfru',
	'thomas-aquinas': 'S:t Thomas av Aquino, präst och kyrkolärare',
	'john-bosco': 'S:t Giovanni Bosco, präst',
	'presentation-of-the-lord': 'Kyndelsmässodagen, Herrens Frambärande i Templet',
	ansgar: 'S:t Ansgar, biskop',
	agatha: 'S:ta Agatha, jungfru och martyr',
	'paul-miki': 'S:t Paul Miki och hans följeslagare, martyrer',
	'jerome-emiliani': 'S:t Hieronymus Emiliani',
	'josephine-bakhita': 'S:ta Josefina Bakhita, jungfru',
	scholastica: 'S:ta Scholastica, jungfru',
	'our-lady-of-lourdes': 'Den saliga jungfrun Maria av Lourdes',
	'cyril-methodius': 'S:t Kyrillos, munk, och S:t Methodios, biskop',
	'seven-founders': 'De sju grundarna av servitorden',
	'peter-damian': 'S:t Petrus Damiani, biskop och kyrkolärare',
	'chair-of-peter': 'Den helige Aposteln Petrus Biskopsstol',
	polycarp: 'S:t Polykarpos, martyr',
	'gregory-of-narek': 'S:t Gregorios av Narek, abbot och kyrkolärare',
	casimir: 'S:t Kasimir',
	'perpetua-felicity': 'S:ta Perpetua och S:ta Felicitas, martyrer',
	'john-of-god': 'S:t Johannes av Gud, ordensman',
	'frances-of-rome': 'S:ta Francesca Romana, ordenskvinna',
	patrick: 'S:t Patrick, biskop',
	'cyril-of-jerusalem': 'S:t Kyrillos av Jerusalem, biskop och kyrkolärare',
	joseph: 'S:t Josef, Jungfru Marias Brudgum',
	turibius: 'S:t Toribio av Mongrovejo, biskop',
	annunciation: 'Herrens Bebådelse – Jungfru Marie Bebådelsedag',
	'francis-of-paola': 'S:t Francesco di Paola, eremit',
	isidore: 'S:t Isidor av Sevilla, biskop och kyrkolärare',
	'vincent-ferrer': 'S:t Vincentius Ferrer, präst',
	'john-baptist-de-la-salle': 'S:t Jean Baptiste de la Salle, präst',
	stanislaus: 'S:t Stanislaus, biskop och martyr',
	'martin-i': 'S:t Martin I, påve och martyr',
	anselm: 'S:t Anselm av Canterbury, biskop och kyrkolärare',
	george: 'S:t Georg, martyr',
	adalbert: 'S:t Adalbert, biskop och martyr',
	fidelis: 'S:t Fidelis av Sigmaringen, präst och martyr',
	mark: 'S:t Markus, evangelist',
	'peter-chanel': 'S:t Pierre Chanel, präst och martyr',
	'louis-de-montfort': 'S:t Louis Marie Grignion de Montfort, präst',
	'catherine-of-siena': 'S:ta Katarina av Siena, jungfru och kyrkolärare',
	'pius-v': 'S:t Pius V, påve',
	'joseph-the-worker': 'S:t Josef arbetaren',
	athanasius: 'S:t Athanasios, biskop och kyrkolärare',
	'philip-james': 'S:t Filippos och S:t Jakob, apostlar',
	'john-of-avila': 'S:t Johannes av Ávila, präst och kyrkolärare',
	'nereus-achilleus': 'S:t Nereus och S:t Achilleus, martyrer',
	pancras: 'S:t Pankratios, martyr',
	'our-lady-of-fatima': 'Den saliga jungfru Maria av Fatima',
	matthias: 'S:t Mattias, apostel',
	'bernardine-of-siena': 'S:t Bernardino av Siena, präst',
	'christopher-magallanes': 'S:t Kristoffer Magallanes, präst och hans följeslagare',
	'rita-of-cascia': 'S:ta Rita av Cascia, ordenskvinna',
	bede: 'S:t Beda Venerabilis, präst och kyrkolärare',
	'gregory-vii': 'S:t Gregorius VII, påve',
	'mary-magdalene-de-pazzi': 'S:ta Maria Magdalena de’ Pazzi, jungfru',
	'philip-neri': 'S:t Filippo Neri, präst',
	'augustine-of-canterbury': 'S:t Augustinus av Canterbury, biskop',
	'paul-vi': 'S:t Paulus VI, påve',
	visitation: 'Den saliga Jungfrun Marias Besök',
	justin: 'S:t Justinus, martyr',
	'marcellinus-peter': 'S:t Marcellinus och S:t Petrus, martyrer',
	'charles-lwanga': 'S:t Charles Lwanga och hans följeslagare, martyrer',
	boniface: 'S:t Bonifatius, biskop och martyr',
	norbert: 'S:t Norbert av Xanten, biskop',
	ephrem: 'S:t Efraim Syriern, diakon och kyrkolärare',
	barnabas: 'S:t Barnabas, apostel',
	'anthony-of-padua': 'S:t Antonius av Padua, präst och kyrkolärare',
	romuald: 'S:t Romuald, abbot',
	'aloysius-gonzaga': 'S:t Aloisius Gonzaga, ordensman',
	'paulinus-of-nola': 'S:t Paulinus av Nola, biskop',
	'fisher-more': 'S:t John Fisher, biskop, och S:t Thomas More, martyrer',
	'birth-of-john-the-baptist': 'S:t Johannes Döparens Födelse',
	'cyril-of-alexandria': 'S:t Kyrillos av Alexandria, biskop och kyrkolärare',
	irenaeus: 'S:t Irenaeus av Lyon, biskop, martyr och kyrkolärare',
	'peter-and-paul': 'S:t Petrus och S:t Paulus, apostlar',
	'first-martyrs-of-rome': 'Den romerska kyrkans första martyrer',
	'thomas-apostle': 'S:t Tomas, apostel',
	'elizabeth-of-portugal': 'S:ta Elisabeth av Portugal',
	'anthony-zaccaria': 'S:t Antonio Maria Zaccaria, präst',
	'maria-goretti': 'S:ta Maria Goretti, jungfru och martyr',
	'augustine-zhao-rong': 'S:t Augustinus Zhao Rong, präst, och hans följeslagare, martyrer',
	benedict: 'S:t Benedictus av Nursia, abbot',
	henry: 'S:t Henrik II',
	camillus: 'S:t Camillo de Lellis, präst',
	bonaventure: 'S:t Bonaventura, biskop och kyrkolärare',
	'our-lady-of-mount-carmel': 'Den saliga jungfrun Maria av berget Karmel',
	'lawrence-of-brindisi': 'S:t Lorenzo da Brindisi, präst och kyrkolärare',
	'mary-magdalene': 'S:ta Maria Från Magdala',
	sharbel: 'S:t Charbel Makhlûf, präst',
	james: 'S:t Jakob, apostel',
	'joachim-anne': 'S:t Joakim och S:ta Anna, jungfru Marias föräldrar',
	'peter-chrysologus': 'S:t Petrus Chrysologus, biskop och kyrkolärare',
	'ignatius-of-loyola': 'S:t Ignatius av Loyola, präst',
	'alphonsus-liguori': 'S:t Alfonso Maria de’ Liguori, biskop och kyrkolärare',
	'eusebius-of-vercelli': 'S:t Pierre Julien Eymard, präst',
	'peter-julian-eymard': 'S:t Eusebius av Vercelli, biskop',
	'john-vianney': 'S:t Jean Marie Vianney, präst',
	'dedication-st-mary-major': 'Invigningen av basilikan Santa Maria Maggiore',
	transfiguration: 'Kristi Förklaring',
	'sixtus-ii': 'S:t Sixtus II, påve, och hans följeslagare, martyrer',
	cajetan: 'S:t Cajetanus, präst',
	dominic: 'S:t Dominicus, präst',
	'teresa-benedicta': 'S:ta Teresia Benedicta av Korset, jungfru och martyr',
	lawrence: 'S:t Laurentius, diakon och martyr',
	clare: 'S:ta Clara, jungfru',
	'jane-frances-de-chantal': 'S:ta Jeanne–Françoise de Chantal, ordenskvinna',
	'pontian-hippolytus': 'S:t Pontianus, påve, och S:t Hippolytos, präst, martyrer',
	'maximilian-kolbe': 'S:t Maximilian Maria Kolbe, präst och martyr',
	assumption: 'Jungfru Marias Upptagning till Himlen',
	'stephen-of-hungary': 'S:t Stefan av Ungern',
	'john-eudes': 'S:t Jean Eudes, präst',
	bernard: 'S:t Bernhard, abbot och kyrkolärare',
	'pius-x': 'S:t Pius X, påve',
	'queenship-of-mary': 'Den saliga jungfru Maria drottningen',
	'rose-of-lima': 'S:ta Rosa av Lima, jungfru',
	bartholomew: 'S:t Bartolomaios, apostel',
	louis: 'S:t Ludvig av Frankrike',
	'joseph-calasanz': 'S:t Josef av Calasanz, präst',
	monica: 'S:ta Monica',
	augustine: 'S:t Augustinus, biskop och kyrkolärare',
	'passion-of-john-the-baptist': 'S:t Johannes döparens martyrium',
	'gregory-the-great': 'S:t Gregorius den store, påve och kyrkolärare',
	'teresa-of-calcutta': 'S:ta Teresa av Calcutta, jungfru',
	'nativity-of-mary': 'Den saliga Jungfru Marias Födelse',
	'peter-claver': 'S:t Petrus Claver, präst',
	'holy-name-of-mary': 'Den saliga jungfru Marias namn',
	'john-chrysostom': 'S:t Johannes Chrysostomos, biskop och kyrkolärare',
	'exaltation-of-the-cross': 'Det heliga korsets upphöjelse',
	'our-lady-of-sorrows': 'Den saliga jungfru Marias smärtor',
	'cornelius-cyprian': 'S:t Cornelius, påve, och S:t Cyprianus, biskop',
	'robert-bellarmine': 'S:t Roberto Bellarmino, biskop och kyrkolärare',
	hildegard: 'S:ta Hildegard av Bingen, jungfru och kyrkolärare',
	januarius: 'S:t Januarius, biskop och martyr',
	'andrew-kim':
		'S:t Andreas Kim Tae-gŏn, präst, S:t Paulus Chŏng Ha-sang och deras följeslagare, martyrer',
	matthew: 'S:t Matteus, apostel och evangelist',
	'padre-pio': 'S:t Pio av Pietrelcina, präst',
	'cosmas-damian': 'S:t Kosmas och S:t Damianus, martyrer',
	'vincent-de-paul': 'S:t Vincent de Paul, präst',
	wenceslaus: 'S:t Venceslaus, martyr',
	'lawrence-ruiz': 'S:t Lorenzo Ruiz och hans följeslagare, martyrer',
	archangels: 'S:t Mikael, S:t Gabriel och S:t Rafael, ärkeänglar',
	jerome: 'S:t Hieronymus, präst och kyrkolärare',
	'therese-of-lisieux': 'S:ta Teresa av Jesusbarnet, jungfru och kyrkolärare',
	'guardian-angels': 'De heliga skyddsänglarna',
	'francis-of-assisi': 'S:t Franciskus av Assisi',
	faustina: 'S:ta Faustina Kowalska, jungfru',
	bruno: 'S:t Bruno, präst',
	denis: 'S:t Dionysios, biskop, och hans följeslagare, martyrer',
	'john-leonardi': 'S:t Giovanni Leonardi, präst',
	'john-henry-newman': 'S:t John Henry Newman, präst och kyrkolärare',
	'john-xxiii': 'S:t Johannes XXIII, påve',
	'callistus-i': 'S:t Calixtus I, påve och martyr',
	'teresa-of-avila': 'S:ta Teresa av Jesus, jungfru och kyrkolärare',
	hedwig: 'S:ta Hedvig, ordenskvinna',
	'margaret-mary-alacoque': 'S:ta Margareta Maria Alacoque, jungfru',
	'ignatius-of-antioch': 'S:t Ignatios av Antiochia, biskop och martyr',
	luke: 'S:t Lukas, evangelist',
	'north-american-martyrs':
		'S:t Jean de Brébeuf och S:t Isaac Jogues, präster, och deras följeslagare, martyrer',
	'paul-of-the-cross': 'S:t Paulus av Korset, präst',
	'john-paul-ii': 'S:t Johannes Paulus II, påve',
	'john-of-capistrano': 'S:t Giovanni da Capistrano, präst',
	'anthony-mary-claret': 'S:t Antonius Maria Claret, biskop',
	'simon-jude': 'S:t Simon och S:t Judas, apostlar',
	'all-saints': 'Alla Helgons Dag',
	'martin-de-porres': 'S:t Martin de Porres, ordensman',
	'charles-borromeo': 'S:t Carlo Borromeo, biskop',
	'dedication-of-the-lateran': 'Lateranbasilikans Invigningsdag',
	'leo-the-great': 'S:t Leo den store, påve och kyrkolärare',
	'martin-of-tours': 'S:t Martin av Tours, biskop',
	josaphat: 'S:t Josafat, biskop och martyr',
	'albert-the-great': 'S:t Albertus Magnus, biskop och kyrkolärare',
	'margaret-of-scotland': 'S:ta Margareta av Skottland',
	gertrude: 'S:ta Gertrud av Helfta, jungfru',
	'elizabeth-of-hungary': 'S:ta Elisabeth av Ungern, ordenskvinna',
	'dedication-of-peter-and-paul': 'Petrus– och Paulus– basilikornas invigningsdag',
	'presentation-of-mary': 'Den saliga jungfru Marias tempelgång',
	cecilia: 'S:ta Cecilia, jungfru och martyr',
	'clement-i': 'S:t Clemens I, påve och martyr',
	columban: 'S:t Columbanus, abbot',
	'andrew-dung-lac': 'S:t Andreas Dûng Lac, präst, och hans följeslagare, martyrer',
	'catherine-of-alexandria': 'S:ta Katarina av Alexandria, jungfru och martyr',
	andrew: 'S:t Andreas, apostel',
	'francis-xavier': 'S:t Francisco Xavier, präst',
	'john-damascene': 'S:t Johannes av Damaskus, präst och kyrkolärare',
	nicholas: 'S:t Nicolaus, biskop',
	ambrose: 'S:t Ambrosius, biskop och kyrkolärare',
	'immaculate-conception': 'Jungfru Marias Utkorelse och Fullkomliga Renhet',
	'juan-diego': 'S:t Juan Diego Cuahtlatoatzin',
	'our-lady-of-loreto': 'Den saliga jungfru Maria av Loreto',
	'damasus-i': 'S:t Damasus I, påve',
	'our-lady-of-guadalupe': 'Den saliga jungfru Maria av Guadalupe',
	lucy: 'S:ta Lucia',
	'john-of-the-cross': 'S:t Johannes av Korset, präst och kyrkolärare',
	'peter-canisius': 'S:t Petrus Canisius, präst och kyrkolärare',
	'john-of-kanty': 'S:t Johannes av Kêty, präst',
	stephen: 'S:t Stefanos, den förste martyren',
	'john-evangelist': 'S:t Johannes, apostel och evangelist',
	'holy-innocents': 'De heliga Oskyldiga Barnen i Betlehem, martyrer',
	'thomas-becket': 'S:t Thomas Becket, biskop och martyr',
	'sylvester-i': 'S:t Silvester I, påve',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Juldagen',
	'holy-family': 'Den Heliga Familjen',
	'mary-mother-of-god': 'Guds Heliga Moder Marias Högtid',
	'christmas-2-sunday': 'Andra Söndagen efter Jul',
	epiphany: 'Epifania– Herrens Uppenbarelse',
	'baptism-of-the-lord': 'Herrens Dop',
	'ash-wednesday': 'Askonsdagen',
	'palm-sunday': 'Palmsöndagen – Passionssöndagen',
	'holy-thursday': 'Skärtorsdagen',
	'good-friday': 'Långfredagen – Herrens Lidande och Död',
	'holy-saturday': 'Påskafton',
	'easter-sunday': 'Påskdagen – Kristi Uppståndelse',
	'easter-2-sunday': '2:a Påsksöndagen – Den Gudomliga Barmhärtighetens',
	ascension: 'Kristi Himmelsfärds Dag',
	pentecost: 'Pingstdagen',
	trinity: 'Heliga Trefaldighets Dag',
	'corpus-christi': 'Kristi Kropps och Blods Högtid',
	'sacred-heart': 'Jesu Hjärtas Dag',
	'immaculate-heart': 'Jungfru Marias Obefläckade Hjärta',
	'mary-mother-of-the-church': 'Den saliga Jungfrun Maria, kyrkans moder',
	'christ-the-king': 'Kristus Konungens Dag'
};

/**
 * The Proper of Time in Swedish, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 *
 * It does not number its Sundays the way it numbers its weekdays, so three
 * Sunday numerals were settled separately (2026-09-06). Advent week 3 and
 * Lent week 4 are Gaudete and Laetare, which the solve skipped over the
 * colour the feeds give them and which the feeds do state — `Tredje Söndagen
 * i Advent`, `Fjärde Söndagen i Fastan`, in all three years. Ordinary Time
 * week 9 has no Sunday in 2025, 2026 or 2027 in any calendar, and this column
 * writes every week as its digits.
 */
export const svTemporal: TemporalNames = {
	days: { 1: 'Måndag', 2: 'Tisdag', 3: 'Onsdag', 4: 'Torsdag', 5: 'Fredag', 6: 'Lördag' },
	weeks: {
		1: '1:a',
		2: '2:a',
		3: '3:e',
		4: '4:e',
		5: '5:e',
		6: '6:e',
		7: '7:e',
		8: '8:e',
		9: '9:e',
		10: '10:e',
		11: '11:e',
		12: '12:e',
		13: '13:e',
		14: '14:e',
		15: '15:e',
		16: '16:e',
		17: '17:e',
		18: '18:e',
		19: '19:e',
		20: '20:e',
		21: '21:a',
		22: '22:a',
		23: '23:e',
		24: '24:e',
		25: '25:e',
		26: '26:e',
		27: '27:e',
		28: '28:e',
		29: '29:e',
		30: '30:e',
		31: '31:a',
		32: '32:a',
		33: '33:e',
		34: '34:e'
	},
	octave: { 5: 'Femte', 6: 'Sjätte', 7: 'Sjunde' },
	sunday: {
		advent: {
			form: '{week} Söndagen i Advent',
			weeks: { 1: 'Första', 2: 'Andra', 3: 'Tredje', 4: 'Fjärde' }
		},
		lent: {
			form: '{week} Söndagen i Fastan',
			weeks: { 1: 'Första', 2: 'Andra', 3: 'Tredje', 4: 'Fjärde', 5: 'Femte' }
		},
		easter: { form: '{week}:e Påsksöndagen', weeks: { 3: '3', 4: '4', 5: '5', 6: '6', 7: '7' } },
		ordinary: {
			form: '{week} Söndagen »under året«',
			weeks: {
				2: '2',
				3: '3',
				4: '4',
				5: '5',
				6: '6',
				7: '7',
				8: '8',
				9: '9',
				10: '10',
				11: '11',
				12: '12',
				13: '13',
				14: '14',
				15: '15',
				16: '16',
				17: '17',
				18: '18',
				19: '19',
				20: '20',
				21: '21',
				22: '22',
				23: '23',
				24: '24',
				25: '25',
				26: '26',
				27: '27',
				28: '28',
				29: '29',
				30: '30',
				31: '31',
				32: '32',
				33: '33'
			}
		}
	},
	weekday: {
		advent: '{day} i {week} adventsveckan',
		lent: '{day} i {week} fasteveckan',
		easter: '{day} i {week} påskveckan',
		ordinary: '{day} i {week} veckan »under året«'
	},
	holyWeek: '{day} i Stilla Veckan',
	afterAshes: '{day} efter Askonsdag',
	afterEpiphany: '{day} efter epifania',
	christmasWeekday: '{day} efter nyårsdagen',
	easterOctave: '{day} i 1:a påskveckan',
	christmasOctave: '{nth} dagen i juloktaven'
};
