/**
 * The General Roman Calendar in Vietnamese.
 *
 * Transcribed from GCatholic's Vietnamese edition of Vietnam's calendar.
 * `../names.svelte.ts` has what these are, where they came from, and the two
 * things they are not.
 *
 * 216 of the Calendar's 218. The 2 absent are the ones Vietnam keeps someone
 * else on the day of — `our-lady-of-the-rosary` among them — so this edition
 * never prints them and they go on falling back to English, which is what
 * `celebrationName` is for.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `viTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const vi: Record<string, string> = {
	'basil-gregory': 'Thánh Ba-xi-li-ô Cả và thánh Ghê-gô-ri-ô Na-di-en, giám mục, tiến sĩ Hội Thánh',
	'holy-name-of-jesus': 'Kính Danh rất thánh Chúa Giê-su',
	'raymond-of-penyafort': 'Thánh Rây-mun-đô Pê-nha-pho, linh mục',
	hilary: 'Thánh Hi-la-ri-ô, giám mục, tiến sĩ Hội Thánh',
	'anthony-abbot': 'Thánh An-tôn, viện phụ',
	fabian: 'Thánh Pha-bi-a-nô, giáo hoàng, tử đạo',
	sebastian: 'Thánh Xê-bát-ti-a-nô, tử đạo',
	agnes: 'Thánh A-nê, trinh nữ, tử đạo',
	'vincent-deacon': 'Thánh Vinh-sơn, phó tế, tử đạo',
	'francis-de-sales': 'Thánh Phan-xi-cô đơ Xan, giám mục, tiến sĩ Hội Thánh',
	'conversion-of-paul': 'Thánh Phao-lô, tông đồ trở lại',
	'timothy-titus': 'Thánh Ti-mô-thê và thánh Ti-tô, giám mục',
	'angela-merici': 'Thánh An-giê-la Mê-ri-si, trinh nữ',
	'thomas-aquinas': 'Thánh Tô-ma A-qui-nô, linh mục, tiến sĩ Hội Thánh',
	'john-bosco': 'Thánh Gio-an Bốt-cô, linh mục',
	'presentation-of-the-lord': 'Dâng Chúa Giê-su Trong Đền Thánh',
	blaise: 'Thánh Bơ-la-xi-ô, giám mục, tử đạo',
	ansgar: 'Thánh An-ga-ri-ô, giám mục',
	agatha: 'Thánh A-ga-ta, trinh nữ, tử đạo',
	'paul-miki': 'Thánh Phao-lô Mi-ki và các bạn, tử đạo',
	'jerome-emiliani': 'Thánh Giê-rô-ni-mô Ê-mi-li-a-ni',
	'josephine-bakhita': 'Thánh Gio-sep-phi-na Ba-khi-ta, trinh nữ',
	scholastica: 'Thánh Cô-lát-ti-ca, trinh nữ',
	'our-lady-of-lourdes': 'Đức Mẹ Lộ-đức',
	'cyril-methodius': 'Thánh Sy-ri-lô, đan sĩ và thánh Mê-tô-đi-ô, giám mục',
	'seven-founders': 'Bảy thánh lập dòng Tôi Tớ Đức Mẹ',
	'peter-damian': 'Thánh Phê-rô Đa-mi-a-nô, giám mục, tiến sĩ Hội Thánh',
	'chair-of-peter': 'Lập tông tòa thánh Phê-rô',
	polycarp: 'Thánh Pô-li-cáp, giám mục, tử đạo',
	'gregory-of-narek': 'Thánh Ghê-gô-ri-ô thành Narek, viện phụ, tiến sĩ Hội Thánh',
	casimir: 'Thánh Ca-xi-mia',
	'perpetua-felicity': 'Thánh nữ Pe-pê-tu-a và thánh nữ Phê-li-xi-ta, tử đạo',
	'john-of-god': 'Thánh Gio-an Thiên Chúa, Tu sĩ',
	'frances-of-rome': 'Thánh Phan-xi-ca Rô-ma, nữ tu',
	patrick: 'Thánh Pát-tric, giám mục',
	'cyril-of-jerusalem': 'Thánh Sy-ri-lô, giám mục Giê-ru-sa-lem, tiến sĩ Hội Thánh',
	joseph: 'Thánh Giu-se, Bạn trăm năm Đức Trinh nữ Maria',
	turibius: 'Thánh Tu-ri-bi-ô Môn-rô-vê-khô, giám mục',
	annunciation: 'Lễ Truyền Tin',
	'francis-of-paola': 'Thánh Phan-xi-cô Pao-la, ẩn tu',
	isidore: 'Thánh I-xi-đô-rô, giám mục, tiến sĩ Hội Thánh',
	'vincent-ferrer': 'Thánh Vinh-sơn Phê-ri-ô, linh mục',
	'john-baptist-de-la-salle': 'Thánh Gio-an Bao-ti-xi-ta La San, linh mục',
	stanislaus: 'Thánh Ta-nit-lao, giám mục, tử đạo',
	'martin-i': 'Thánh Mác-ti-nô I, giáo hoàng, tử đạo',
	anselm: 'Thánh An-xen-mô, giám mục, tiến sĩ Hội Thánh',
	george: 'Thánh Gio-gi-ô, tử đạo',
	adalbert: 'Thánh A-đan-bét-tô, giám mục, tử đạo',
	fidelis: 'Thánh Phi-đên Dich-ma-rinh-gan, linh mục, tử đạo',
	mark: 'Thánh Mác-cô, tác giả sách Tin Mừng',
	'peter-chanel': 'Thánh Phê-rô Sa-nen, linh mục, tử đạo',
	'louis-de-montfort': 'Thánh Lu-i đơ Mông-pho, linh mục',
	'catherine-of-siena': 'Thánh Ca-ta-ri-na Si-ê-na, trinh nữ, tiến sĩ Hội Thánh',
	'pius-v': 'Thánh Pi-ô V, giáo hoàng',
	'joseph-the-worker': 'Thánh Giu-se thợ',
	athanasius: 'Thánh A-tha-na-xi-ô, giám mục, tiến sĩ Hội Thánh',
	'philip-james': 'Thánh Phi-lip-phê và thánh Gia-cô-bê, tông đồ',
	'john-of-avila': 'Thánh Gio-an thành Ávila, linh mục, tiến sĩ Hội Thánh',
	'nereus-achilleus': 'Thánh Nê-rê-ô và thánh A-ki-lê-ô, tử đạo',
	pancras: 'Thánh Păng-ra-xi-ô, tử đạo',
	'our-lady-of-fatima': 'Đức Mẹ Fa-ti-ma',
	matthias: 'Thánh Mat-thi-a, tông đồ',
	'john-i': 'Thánh Gio-an I, giáo hoàng, tử đạo',
	'bernardine-of-siena': 'Thánh Bê-na-đi-nô Xi-ê-na, linh mục',
	'christopher-magallanes': 'Thánh Christôphê de Magallanes, linh mục, và các bạn, tử đạo',
	'rita-of-cascia': 'Thánh Ri-ta thành Ca-xi-a, Nữ tu',
	bede: 'Thánh Bê-đa khả kính, linh mục, tiến sĩ Hội Thánh',
	'gregory-vii': 'Thánh Ghê-gôri-ô VII, giáo hoàng',
	'mary-magdalene-de-pazzi': 'Thánh Ma-ri-a Ma-đa-lê-na Pat-di, trinh nữ',
	'philip-neri': 'Thánh Phi-lip-phê Nê-ri, linh mục',
	'augustine-of-canterbury': 'Thánh Au-tinh thành Can-tơ-bơ-ri, giám mục',
	'paul-vi': 'Thánh Phao-lô VI, giáo hoàng',
	visitation: 'Đức Ma-ri-a thăm viếng bà Ê-li-sa-bét',
	justin: 'Thánh Giút-ti-nô, tử đạo',
	'marcellinus-peter': 'Thánh Mác-sê-li-nô và thánh Phê-rô, tử đạo',
	'charles-lwanga': 'Thánh Ca-rô-lô Loan-ga và các bạn, tử đạo',
	boniface: 'Thánh Bô-ni-phát, giám mục, tử đạo',
	norbert: 'Thánh Nô-bec-tô, giám mục',
	ephrem: 'Thánh Ép-rem, phó tế, tiến sĩ Hội Thánh',
	barnabas: 'Thánh Ba-na-ba, tông đồ',
	'anthony-of-padua': 'Thánh An-tôn thành Pa-đô-va, linh mục, tiến sĩ Hội Thánh',
	romuald: 'Thánh Rô-moan-đô, viện phụ',
	'aloysius-gonzaga': 'Thánh Lu-y Gon-da-ga, tu sĩ',
	'paulinus-of-nola': 'Thánh Pao-li-nô, giám mục Nô-la',
	'fisher-more': 'Thánh Gio-an Phít-sơ, giám mục, và thánh Tô-ma Mo, tử đạo',
	'birth-of-john-the-baptist': 'Sinh nhật thánh Gio-an Tẩy Giả',
	'cyril-of-alexandria': 'Thánh Sy-ri-lô, giám mục A-lê-xan-ri, tiến sĩ Hội Thánh',
	irenaeus: 'Thánh I-rê-nê, giám mục, tử đạo, tiến sĩ Hội Thánh',
	'peter-and-paul': 'Thánh Phê-rô và thánh Phao-lô, tông đồ',
	'first-martyrs-of-rome': 'Các thánh tử đạo tiên khởi của giáo đoàn Rô-ma',
	'thomas-apostle': 'Thánh Tô-ma, tông đồ',
	'elizabeth-of-portugal': 'Thánh nữ Ê-li-sa-bét Bồ-đào-nha',
	'anthony-zaccaria': 'Thánh An-tôn Ma-ri-a Da-ca-ri-a, linh mục',
	'maria-goretti': 'Thánh Ma-ri-a Go-rét-ti, trinh nữ, tử đạo',
	'augustine-zhao-rong': 'Thánh Augustinô Triệu Vinh, linh mục và các bạn, tử đạo',
	benedict: 'Thánh Biển-đức, viện phụ',
	henry: 'Thánh Hen-ri-cô',
	camillus: 'Thánh Ca-mi-lô Len-li, linh mục',
	bonaventure: 'Thánh Bô-na-ven-tu-ra, giám mục, tiến sĩ Hội Thánh',
	'our-lady-of-mount-carmel': 'Đức Mẹ núi Cat-minh',
	apollinaris: 'Thánh A-pô-li-na-rê, giám mục, tử đạo',
	'lawrence-of-brindisi': 'Thánh Lô-ren-xô Bơ-rin-đi-xi, linh mục, tiến sĩ Hội Thánh',
	'mary-magdalene': 'Thánh Ma-ri-a Ma-đa-lê-na',
	bridget: 'Thánh Bi-ghit-ta, nữ tu',
	sharbel: 'Thánh Sa-ben Mac-lup, linh mục',
	james: 'Thánh Gia-cô-bê, tông đồ',
	'joachim-anne': 'Thánh Gio-a-kim và thánh An-na, song thân Đức Ma-ri-a',
	'martha-mary-lazarus': 'Thánh nữ Mác-ta, thánh nữ Ma-ri-a và thánh La-xa-rơ',
	'peter-chrysologus': 'Thánh Phê-rô Kim Ngôn, giám mục, tiến sĩ Hội Thánh',
	'ignatius-of-loyola': 'Thánh I-nha-xi-ô Lôi-ô-la, linh mục',
	'alphonsus-liguori': 'Thánh An-phong Ma-ri-a Li-gô-ri, giám mục, tiến sĩ Hội Thánh',
	'eusebius-of-vercelli': 'Thánh Êu-xê-bi-ô Véc-se-li, giám mục',
	'peter-julian-eymard': 'Thánh Phê-rô Giu-li-a-nô Ê-ma, linh mục',
	'john-vianney': 'Thánh Gio-an Ma-ri-a Vi-a-nê, linh mục',
	'dedication-st-mary-major': 'Cung hiến thánh đường Đức Ma-ri-a',
	transfiguration: 'Chúa Hiển Dung',
	'sixtus-ii': 'Thánh Xit-tô II, giáo hoàng và các bạn, tử đạo',
	cajetan: 'Thánh Ga-ê-ta-nô, linh mục',
	dominic: 'Thánh Đa-minh, linh mục',
	'teresa-benedicta': 'Thánh Têrêxa Bê-nê-đíc-ta Thánh Giá, trinh nữ, tử đạo',
	lawrence: 'Thánh Lô-ren-xô, phó tế, tử đạo',
	clare: 'Thánh Cờ-la-ra, trinh nữ',
	'jane-frances-de-chantal': 'Thánh Gio-an-na Phan-xi-ca Săng-tan, nữ tu',
	'pontian-hippolytus': 'Thánh Pôn-xi-a-nô, giáo hoàng, và thánh Hip-pô-li-tô, linh mục, tử đạo',
	'maximilian-kolbe': 'Thánh Mác-xi-mi-li-a-nô Kôn-bê, linh mục, tử đạo',
	assumption: 'Đức Ma-ri-a Lên Trời',
	'stephen-of-hungary': 'Thánh Stê-pha-nô Hungary',
	'john-eudes': 'Thánh Gio-an Ơ-đơ, linh mục',
	bernard: 'Thánh Bê-na-đô, viện phụ, tiến sĩ Hội Thánh',
	'pius-x': 'Thánh Piô X, giáo hoàng',
	'queenship-of-mary': 'Đức Ma-ri-a Nữ vương',
	'rose-of-lima': 'Thánh Rô-sa Li-ma, trinh nữ',
	bartholomew: 'Thánh Ba-tô-lô-mê-ô, tông đồ',
	louis: 'Thánh Lu-y',
	'joseph-calasanz': 'Thánh Giu-se Ca-la-xan, linh mục',
	monica: 'Thánh nữ Mô-ni-ca',
	augustine: 'Thánh Âu-tinh, giám mục, tiến sĩ Hội Thánh',
	'passion-of-john-the-baptist': 'Thánh Gio-an Tẩy Giả bị trảm quyết',
	'gregory-the-great': 'Thánh Grê-gô-ri-ô Cả, giáo hoàng, tiến sĩ Hội Thánh',
	'teresa-of-calcutta': 'Thánh Tê-rê-xa Cal-cut-ta, trinh nữ',
	'nativity-of-mary': 'Sinh nhật Đức trinh nữ Maria',
	'peter-claver': 'Thánh Phê-rô Cơ-la-ve, linh mục',
	'holy-name-of-mary': 'Danh Rất Thánh trinh nữ Ma-ri-a',
	'john-chrysostom': 'Thánh Gio-an Kim Khẩu, giám mục, tiến sĩ Hội Thánh',
	'exaltation-of-the-cross': 'Suy tôn Thánh giá',
	'our-lady-of-sorrows': 'Đức Mẹ sầu bi',
	'cornelius-cyprian': 'Thánh Co-nê-li-ô, giáo hoàng và thánh Sip-ri-a-nô, giám mục, tử đạo',
	'robert-bellarmine': 'Thánh Rô-be-tô Be-la-mi-nô, giám mục, tiến sĩ Hội Thánh',
	hildegard: 'Thánh nữ Hildegard thành Bingen, trinh nữ, tiến sĩ Hội Thánh',
	januarius: 'Thánh Gia-nu-a-ri-ô, giám mục, tử đạo',
	'andrew-kim': 'Thánh An-rê Kim Tê-gon, Phao-lô Chứng Ha-san và các bạn, tử đạo',
	matthew: 'Thánh Mat-thêu, tông đồ, tác giả sách Tin Mừng',
	'padre-pio': 'Thánh Pi-ô thành Pi-e-tren-ci-na, linh mục',
	'cosmas-damian': 'Thánh Cót-ma và thánh Đa-mi-a-nô, tử đạo',
	'vincent-de-paul': 'Thánh Vinh-sơn Phao-lô, linh mục',
	wenceslaus: 'Thánh Ven-xét-lao, tử đạo',
	'lawrence-ruiz': 'Thánh Lô-ren-xô Ru-y và các bạn, tử đạo',
	archangels: 'Các Tổng lãnh thiên thần Mi-ca-en, Gáp-ri-en và Ra-pha-en',
	jerome: 'Thánh Giê-rô-ni-mô, linh mục, tiến sĩ Hội Thánh',
	'therese-of-lisieux': 'Thánh Tê-rê-xa Hài Đồng Giê-su, trinh nữ, tiến sĩ Hội Thánh',
	'guardian-angels': 'Các thiên thần hộ thủ',
	'francis-of-assisi': 'Thánh Phan-xi-cô thành Át-xi-di',
	faustina: 'Thánh Faustina Kowalska, trinh nữ',
	bruno: 'Thánh Bơ-ru-nô, linh mục',
	denis: 'Thánh Đi-ô-ni-xi-ô, giám mục và các bạn, tử đạo',
	'john-leonardi': 'Thánh Gio-an Lê-ô-nác-đi, linh mục',
	'john-henry-newman': 'Thánh Gioan Henricô Newman, linh mục, tiến sĩ Hội Thánh',
	'john-xxiii': 'Thánh Gio-an XXIII, giáo hoàng',
	'callistus-i': 'Thánh Ca-lít-tô I, giáo hoàng, tử đạo',
	'teresa-of-avila': 'Thánh Tê-rê-xa Giê-su, trinh nữ, tiến sĩ Hội Thánh',
	hedwig: 'Thánh Hét-vích, nữ tu',
	'margaret-mary-alacoque': 'Thánh Ma-ga-ri-ta Ma-ri-a A-la-cốc, trinh nữ',
	'ignatius-of-antioch': 'Thánh I-nha-xi-ô thành An-ti-ô-khi-a, giám mục, tử đạo',
	luke: 'Thánh Lu-ca, tác giả sách Tin Mừng',
	'north-american-martyrs':
		'Thánh Gio-an Bơ-rê-bớp, và thánh I-xa-ác Gio-gơ, linh mục và các bạn, tử đạo',
	'paul-of-the-cross': 'Thánh Phao-lô Thánh Giá, linh mục',
	'john-paul-ii': 'Thánh Gio-an Phao-lô II, giáo hoàng',
	'john-of-capistrano': 'Thánh Gio-an thành Ca-pét-ra-nô, linh mục',
	'anthony-mary-claret': 'Thánh An-tôn Ma-ri-a Cơ-la-rét, giám mục',
	'simon-jude': 'Thánh Si-mon và thánh Giu-đa, tông đồ',
	'all-saints': 'Các Thánh Nam Nữ',
	'martin-de-porres': 'Thánh Mác-ti-nô Po-rét, tu sĩ',
	'charles-borromeo': 'Thánh Ca-rô-lô Bô-rô-mê-ô, giám mục',
	'dedication-of-the-lateran': 'Cung hiến thánh đường La-tê-ra-nô',
	'leo-the-great': 'Thánh Lê-ô Cả, giáo hoàng, tiến sĩ Hội Thánh',
	'martin-of-tours': 'Thánh Mác-ti-nô thành Tua, giám mục',
	josaphat: 'Thánh Giô-sa-phát, giám mục, tử đạo',
	'albert-the-great': 'Thánh An-béc-tô Cả, giám mục, tiến sĩ Hội Thánh',
	'margaret-of-scotland': 'Thánh nữ Ma-ga-ri-ta Tô-cách-lan',
	gertrude: 'Thánh Ghê-tơ-rút, trinh nữ',
	'elizabeth-of-hungary': 'Thánh nữ Ê-li-sa-bet nước Hung-ga-ri',
	'dedication-of-peter-and-paul': 'Cung hiến thánh đường thánh Phê-rô và thánh đường thánh Phao-lô',
	'presentation-of-mary': 'Đức Mẹ dâng mình trong đền thờ',
	cecilia: 'Thánh Xê-xi-li-a, trinh nữ, tử đạo',
	'clement-i': 'Thánh Cơ-lê-men-tê I, giáo hoàng, tử đạo',
	columban: 'Thánh Cô-lum-ban, viện phụ',
	'catherine-of-alexandria': 'Thánh Ca-ta-ri-na A-lê-xan-ri-a, trinh nữ, tử đạo',
	andrew: 'Thánh An-rê, tông đồ',
	'francis-xavier': 'Thánh Phan-xi-cô Xa-vi-e, linh mục',
	'john-damascene': 'Thánh Gioan Đa-mát, linh mục, tiến sĩ Hội Thánh',
	nicholas: 'Thánh Ni-cô-la, giám mục',
	ambrose: 'Thánh Am-rô-xi-ô, giám mục, tiến sĩ Hội Thánh',
	'immaculate-conception': 'Đức Maria vô nhiễm nguyên tội',
	'juan-diego': 'Thánh Gio-an Đi-ê-gô',
	'our-lady-of-loreto': 'Đức trinh nữ Ma-ri-a Lô-rê-tô',
	'damasus-i': 'Thánh Đa-ma-xô I, giáo hoàng',
	'our-lady-of-guadalupe': 'Đức trinh nữ Ma-ri-a Goa-đa-lu-pê',
	lucy: 'Thánh Lu-xi-a, trinh nữ, tử đạo',
	'john-of-the-cross': 'Thánh Gio-an Thánh Giá, linh mục, tiến sĩ Hội Thánh',
	'peter-canisius': 'Thánh Phe-rô Ca-na-xi-ô, linh mục, tiến sĩ Hội Thánh',
	'john-of-kanty': 'Thánh Gio-an thành Kê-ty, linh mục',
	stephen: 'Thánh Tê-pha-nô, tử đạo tiên khởi',
	'john-evangelist': 'Thánh Gio-an, tông đồ, tác giả sách Tin Mừng',
	'holy-innocents': 'Các Thánh Anh Hài, tử đạo',
	'thomas-becket': 'Thánh Tô-ma Béc-két, giám mục, tử đạo',
	'sylvester-i': 'Thánh Xin-vet-tê I, giáo hoàng',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: 'Chúa Giáng Sinh',
	'holy-family': 'Thánh Gia Thất: Chúa Giê-su, Đức Maria và thánh Giu-se',
	'mary-mother-of-god': 'Thánh Ma-ri-a, Ðức Mẹ Chúa Trời',
	epiphany: 'Chúa Hiển Linh',
	'baptism-of-the-lord': 'Chúa Giê-su Chịu Phép Rửa',
	'ash-wednesday': 'Thứ Tư Lễ Tro',
	'palm-sunday': 'Chúa Nhật Lễ Lá',
	'holy-thursday': 'Thứ Năm Tuần Thánh',
	'good-friday': 'Thứ Sáu Tuần Thánh',
	'holy-saturday': 'Thứ Bảy Tuần Thánh',
	'easter-sunday': 'Chúa Nhật Lễ Phục Sinh',
	'easter-2-sunday': 'Chúa Nhật thứ Hai Mùa Phục Sinh (Kính Lòng Thương Xót Chúa)',
	ascension: 'Lễ Thăng Thiên',
	pentecost: 'Lễ Chúa Thánh Thần Hiện Xuống',
	trinity: 'Lễ Chúa Ba Ngôi',
	'corpus-christi': 'Lễ Mình Máu Thánh Chúa',
	'sacred-heart': 'Lễ Trái Tim Cực Thánh Chúa Giê-su',
	'immaculate-heart': 'Lễ Trái Tim Vô Nhiễm Đức Mẹ Ma-ri-a',
	'mary-mother-of-the-church': 'Đức Ma-ri-a, Mẹ Hội Thánh',
	'christ-the-king': 'Lễ Chúa Kitô Vua'
};

/**
 * The Proper of Time in Vietnamese, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const viTemporal: TemporalNames = {
	days: { 1: 'Hai', 2: 'Ba', 3: 'Tư', 4: 'Năm', 5: 'Sáu', 6: 'Bảy' },
	weeks: {
		1: 'Nhất',
		2: 'Hai',
		3: 'Ba',
		4: 'Tư',
		5: 'Năm',
		6: 'Sáu',
		7: 'Bảy',
		8: 'Tám',
		9: 'Chín',
		10: 'Mười',
		11: 'Mười Một',
		12: 'Mười Hai',
		13: 'Mười Ba',
		14: 'Mười Bốn',
		15: 'Mười Lăm',
		16: 'Mười Sáu',
		17: 'Mười Bảy',
		18: 'Mười Tám',
		19: 'Mười Chín',
		20: 'Hai Mươi',
		21: 'Hai Mươi-Nhất',
		22: 'Hai Mươi-Hai',
		23: 'Hai Mươi-Ba',
		24: 'Hai Mươi-Tư',
		25: 'Hai Mươi-Năm',
		26: 'Hai Mươi-Sáu',
		27: 'Hai Mươi-Bảy',
		28: 'Hai Mươi-Tám',
		29: 'Hai Mươi-Chín',
		30: 'Ba Mươi',
		31: 'Ba Mươi-Nhất',
		32: 'Ba Mươi-Hai',
		33: 'Ba Mươi-Ba',
		34: 'Ba Mươi-Tư'
	},
	octave: { 5: 'năm', 6: 'sáu', 7: 'bẩy' },
	sunday: {
		advent: 'Chúa Nhật thứ {week} Mùa Vọng',
		lent: 'Chúa Nhật thứ {week} Mùa Chay',
		easter: 'Chúa Nhật thứ {week} Mùa Phục Sinh',
		ordinary: 'Chúa Nhật thứ {week} Mùa Quanh Năm'
	},
	weekday: {
		advent: 'Thứ {day} trong tuần thứ {week} Mùa Vọng',
		lent: 'Thứ {day} trong tuần thứ {week} Mùa Chay',
		easter: 'Thứ {day} trong tuần thứ {week} Mùa Phục Sinh',
		ordinary: 'Thứ {day} trong tuần thứ {week} Mùa Quanh Năm'
	},
	holyWeek: 'Thứ {day} Tuần Thánh',
	afterAshes: 'Thứ {day} sau Thứ Tư Lễ Tro',
	afterEpiphany: 'Thứ {day} sau Lễ Hiển Linh',
	christmasWeekday: 'Thứ {day} trước Lễ Hiển Linh',
	easterOctave: 'Thứ {day} trong tuần Bát Nhật Lễ Phục Sinh',
	christmasOctave: 'Ngày thứ {nth} trong tuần Bát Nhật Lễ Giáng Sinh'
};
