/**
 * The General Roman Calendar in Traditional Chinese.
 *
 * Transcribed from the 3 calendars GCatholic publishes in Traditional
 * Chinese. `../names.svelte.ts` has what these are, where they came from,
 * and the two things they are not.
 *
 * 217 of the Calendar's 218. The one absent is `augustine-zhao-rong`, which
 * every calendar in this language keeps someone else on the day of, so this
 * edition never prints it and it goes on falling back to English — which is
 * what `celebrationName` is for.
 *
 * Hong Kong and Macau against Taiwan on 197 of the 217, in the
 * transliterations and in the punctuation both — `聖亞加大（貞女、殉道）` against
 * `聖佳德貞女殉道`. What is here is Hong Kong's and Macau's, being two calendars
 * against one and the older of the two traditions. IT IS A CHOICE AND NOT A
 * FINDING: `zht` is one tag over two usages, and it means a reader in Taipei
 * meets Hong Kong's spelling of Agatha.
 *
 * THE DIVISION IS THE SANCTORALE'S ALONE. Hong Kong, Macau and Taiwan print
 * the Proper of Time below identically — the same week numerals, the same
 * weekday characters, the same patterns — so nothing in `zhtTemporal` was
 * chosen between.
 *
 * AND THERE IS NO SIMPLIFIED EDITION TO WEIGH AGAINST EITHER. GCatholic
 * publishes Chinese under one code, `zt`, in three territories, all of them
 * Traditional; `zh` is an interface language here with no calendar of its own
 * anywhere in the feeds, and converting these by script would produce a text
 * nobody published. That reader gets English, which is what a language with no
 * source gets.
 *
 * The Proper of Time is here too: the days the Missal names outright at the
 * end of the record below, and the pieces the other 285 days of the year are
 * composed from in `zhtTemporal` under it.
 */
import type { TemporalNames } from '../types';

export const zht: Record<string, string> = {
	'basil-gregory': '聖巴西略及聖額我略．納齊安（主教、聖師）',
	'holy-name-of-jesus': '耶穌聖名',
	'raymond-of-penyafort': '聖雷孟（司鐸）',
	hilary: '聖依拉略（主教、聖師）',
	'anthony-abbot': '聖安當（院長）',
	fabian: '聖法俾盎（教宗、殉道）',
	sebastian: '聖巴斯弟盎（殉道）',
	agnes: '聖依搦斯（貞女、殉道）',
	'vincent-deacon': '聖味增爵（執事、殉道）',
	'francis-de-sales': '聖方濟各沙雷氏（主教、聖師）',
	'conversion-of-paul': '聖保祿宗徒歸化（宗徒）',
	'timothy-titus': '聖弟茂德及聖弟鐸（主教）',
	'angela-merici': '聖安琪拉．美利西（貞女）',
	'thomas-aquinas': '聖多瑪斯．亞奎納（司鐸、聖師）',
	'john-bosco': '聖若望鮑思高（司鐸）',
	'presentation-of-the-lord': '獻主',
	blaise: '聖巴拉斯（主教、殉道）',
	ansgar: '聖安斯卡（主教）',
	agatha: '聖亞加大（貞女、殉道）',
	'paul-miki': '聖保祿三木及同伴（殉道）',
	'jerome-emiliani': '聖熱羅尼莫．艾明廉',
	'josephine-bakhita': '聖若瑟芬．柏姬達（貞女）',
	scholastica: '聖思嘉（貞女）',
	'our-lady-of-lourdes': '露德聖母',
	'cyril-methodius': '聖濟利祿（隱修士）及聖默多狄（主教）',
	'seven-founders': '聖母忠僕會七位會祖（會士）',
	'peter-damian': '聖伯多祿．達彌盎（主教、聖師）',
	'chair-of-peter': '建立聖伯多祿宗座',
	polycarp: '聖玻里加（主教、殉道）',
	'gregory-of-narek': '聖額我略．納雷科（院長、聖師）',
	casimir: '聖加西彌祿',
	'perpetua-felicity': '聖伯爾都亞及聖斐尼絲（殉道）',
	'john-of-god': '聖若望由天主者（會士）',
	'frances-of-rome': '聖方濟加．露雯（修女）',
	patrick: '聖博德（主教）',
	'cyril-of-jerusalem': '聖濟利祿．耶路撒冷（主教、聖師）',
	joseph: '聖若瑟（聖母淨配）',
	turibius: '聖多利玻（主教）',
	annunciation: '預報救主降生',
	'francis-of-paola': '聖方濟各保拉（隱修士）',
	isidore: '聖依西多祿（主教、聖師）',
	'vincent-ferrer': '聖味增爵斐洛（司鐸）',
	'john-baptist-de-la-salle': '聖若翰．喇沙（司鐸）',
	stanislaus: '聖達尼老（主教、殉道）',
	'martin-i': '聖瑪爾定一世（教宗、殉道）',
	anselm: '聖安瑟莫（主教、聖師）',
	george: '聖喬治（殉道）',
	adalbert: '聖道博（主教、殉道）',
	fidelis: '聖斐德理（司鐸、殉道）',
	mark: '聖馬爾谷（聖史）',
	'peter-chanel': '聖伯多祿．查納（司鐸、殉道）',
	'louis-de-montfort': '聖類斯．葛利寧．蒙福（司鐸）',
	'catherine-of-siena': '聖加大利納（貞女、聖師）',
	'pius-v': '聖比約五世（教宗）',
	'joseph-the-worker': '聖若瑟勞工',
	athanasius: '聖亞大納修（主教、聖師）',
	'philip-james': '聖斐理伯及聖雅各伯（宗徒）',
	'john-of-avila': '聖若望．亞維拉（司鐸、聖師）',
	'nereus-achilleus': '聖聶勒及聖亞基略（殉道）',
	pancras: '聖龐加爵（殉道）',
	'our-lady-of-fatima': '花地瑪聖母',
	matthias: '聖瑪弟亞（宗徒）',
	'john-i': '聖若望一世（教宗、殉道）',
	'bernardine-of-siena': '聖伯爾納定（司鐸）',
	'christopher-magallanes': '聖多福．麥哲倫（司鐸）及同伴（殉道）',
	'rita-of-cascia': '聖李達．加西亞（修女）',
	bede: '聖伯達（司鐸、聖師）',
	'gregory-vii': '聖額我略七世（教宗）',
	'mary-magdalene-de-pazzi': '聖瑪達肋納巴斯（貞女）',
	'philip-neri': '聖斐理伯．內利（司鐸）',
	'augustine-of-canterbury': '聖奧思定．坎特伯雷（主教）',
	'paul-vi': '聖保祿六世（教宗）',
	visitation: '聖母訪親',
	justin: '聖猶思定（殉道）',
	'marcellinus-peter': '聖瑪策林及聖伯多祿（殉道）',
	'charles-lwanga': '聖嘉祿．盧安加及同伴（殉道）',
	boniface: '聖玻尼法（主教、殉道）',
	norbert: '聖諾伯多（主教）',
	ephrem: '聖義範（執事、聖師）',
	barnabas: '聖巴爾納伯（宗徒）',
	'anthony-of-padua': '聖安多尼．巴都亞（司鐸、聖師）',
	romuald: '聖羅慕德（院長）',
	'aloysius-gonzaga': '聖類思．公撒格（會士）',
	'paulinus-of-nola': '聖保林（主教）',
	'fisher-more': '聖若望．費舍（主教）及聖多默．莫爾（殉道）',
	'birth-of-john-the-baptist': '聖若翰洗者誕辰',
	'cyril-of-alexandria': '聖濟利祿．亞力山卓（主教、聖師）',
	irenaeus: '聖依勒內（主教、殉道、聖師）',
	'peter-and-paul': '聖伯多祿及聖保祿（宗徒）',
	'first-martyrs-of-rome': '羅馬教會初期殉道烈士',
	'thomas-apostle': '聖多默（宗徒）',
	'elizabeth-of-portugal': '聖依撒伯爾．葡萄牙',
	'anthony-zaccaria': '聖安多尼．匝加利（司鐸）',
	'maria-goretti': '聖瑪利亞．葛萊蒂（貞女、殉道）',
	benedict: '聖本篤（院長）',
	henry: '聖皇亨利',
	camillus: '聖加彌祿．彌理（司鐸）',
	bonaventure: '聖文德（主教、聖師）',
	'our-lady-of-mount-carmel': '加爾默羅聖母',
	apollinaris: '聖亞博那（主教、殉道）',
	'lawrence-of-brindisi': '聖老楞佐．布林希（司鐸、聖師）',
	'mary-magdalene': '聖瑪利亞．瑪達肋納',
	bridget: '聖彼濟大（修女）',
	sharbel: '聖撒柏．麥祿福（司鐸）',
	james: '聖雅各伯（宗徒）',
	'joachim-anne': '聖若亞敬及聖亞納（聖母雙親）',
	'martha-mary-lazarus': '聖瑪爾大、聖瑪利亞、聖拉匝祿',
	'peter-chrysologus': '聖伯多祿．金言（主教、聖師）',
	'ignatius-of-loyola': '聖依納爵．羅耀拉（司鐸）',
	'alphonsus-liguori': '聖亞豐索（主教、聖師）',
	'eusebius-of-vercelli': '聖歐瑟伯（主教）',
	'peter-julian-eymard': '聖艾伯鐸（司鐸）',
	'john-vianney': '聖若翰．維雅納（司鐸）',
	'dedication-st-mary-major': '聖母大殿奉獻日',
	transfiguration: '耶穌顯聖容',
	'sixtus-ii': '聖西斯篤二世（教宗）及同伴（殉道）',
	cajetan: '聖嘉耶當（司鐸）',
	dominic: '聖道明（司鐸）',
	'teresa-benedicta': '聖十字德蘭．本篤（貞女、殉道）',
	lawrence: '聖老楞佐（執事、殉道）',
	clare: '聖嘉勒（貞女）',
	'jane-frances-de-chantal': '聖方濟加．尚達爾（修女）',
	'pontian-hippolytus': '聖彭謙（教宗）及聖希玻里（司鐸）（殉道）',
	'maximilian-kolbe': '聖高比（司鐸、殉道）',
	assumption: '聖母蒙召升天',
	'stephen-of-hungary': '匈牙利的聖斯德望國王',
	'john-eudes': '聖若望．歐德（司鐸）',
	bernard: '聖伯爾納鐸（院長、聖師）',
	'pius-x': '聖比約十世（教宗）',
	'queenship-of-mary': '聖母元后',
	'rose-of-lima': '聖羅撒（貞女）',
	bartholomew: '聖巴爾多祿茂（宗徒）',
	louis: '聖路易國王',
	'joseph-calasanz': '聖若瑟．加拉桑（司鐸）',
	monica: '聖莫尼加',
	augustine: '聖奧思定（主教、聖師）',
	'passion-of-john-the-baptist': '聖若翰洗者殉道',
	'gregory-the-great': '聖額我略一世（教宗、聖師）',
	'teresa-of-calcutta': '聖德蘭．加爾各答（貞女）',
	'nativity-of-mary': '聖母誕辰',
	'peter-claver': '聖高華（司鐸）',
	'holy-name-of-mary': '聖母瑪利亞聖名',
	'john-chrysostom': '金口聖若望（主教、聖師）',
	'exaltation-of-the-cross': '光榮十字聖架',
	'our-lady-of-sorrows': '痛苦聖母',
	'cornelius-cyprian': '聖高爾乃略（教宗）及聖西彼廉（主教）（殉道）',
	'robert-bellarmine': '聖伯拉民（主教、聖師）',
	hildegard: '聖賀德佳．碧根（貞女、聖師）',
	januarius: '聖雅納略（主教、殉道）',
	'andrew-kim': '聖金大建（司鐸）、聖丁聖夏及同伴（殉道）',
	matthew: '聖瑪竇（宗徒、聖史）',
	'padre-pio': '聖碧岳．庇特來（司鐸）',
	'cosmas-damian': '聖葛斯默及聖達彌盎（殉道）',
	'vincent-de-paul': '聖雲先（司鐸）',
	wenceslaus: '聖文策老（殉道）',
	'lawrence-ruiz': '聖老楞佐．盧斯及同伴（殉道）',
	archangels: '聖彌額爾、聖加俾額爾及聖辣法耳總領天使',
	jerome: '聖熱羅尼莫（司鐸、聖師）',
	'therese-of-lisieux': '聖德蘭．里修（小德肋撒）（貞女、聖師）',
	'guardian-angels': '護守天使',
	'francis-of-assisi': '聖方濟．亞西西（會士）',
	faustina: '聖傅天娜．克瓦爾斯卡（貞女）',
	bruno: '聖博諾（司鐸）',
	'our-lady-of-the-rosary': '玫瑰聖母',
	denis: '聖雕尼削（主教）及同伴（殉道）',
	'john-leonardi': '聖若望．良納第（司鐸）',
	'john-henry-newman': '若望．亨利．紐曼（司鐸、聖師）',
	'john-xxiii': '聖若望二十三世（教宗）',
	'callistus-i': '聖加理斯多一世（教宗、殉道）',
	'teresa-of-avila': '聖德蘭．亞維拉（大德肋撒）（貞女、聖師）',
	hedwig: '聖赫德維（修女）',
	'margaret-mary-alacoque': '聖瑪加利大．亞拉高（貞女）',
	'ignatius-of-antioch': '聖依納爵．安提約基亞（主教、殉道）',
	luke: '聖路加（聖史）',
	'north-american-martyrs': '聖若望．貝巴、聖依撒格．饒覺（司鐸）及同伴（殉道）',
	'paul-of-the-cross': '聖十字保祿（司鐸）',
	'john-paul-ii': '聖若望保祿二世（教宗）',
	'john-of-capistrano': '聖若望．嘉庇當（司鐸）',
	'anthony-mary-claret': '聖安多尼．加烈（主教）',
	'simon-jude': '聖西滿及聖猶達（宗徒）',
	'all-saints': '諸聖',
	'martin-de-porres': '聖瑪爾定．包瑞斯（會士）',
	'charles-borromeo': '聖嘉祿．鮑榮茂（主教）',
	'dedication-of-the-lateran': '祝聖拉特朗大殿',
	'leo-the-great': '聖良一世（教宗、聖師）',
	'martin-of-tours': '聖瑪爾定．都爾（主教）',
	josaphat: '聖若撒法（主教、殉道）',
	'albert-the-great': '聖亞爾伯（主教、聖師）',
	'margaret-of-scotland': '聖瑪加利大．蘇格蘭',
	gertrude: '聖日多達（貞女）',
	'elizabeth-of-hungary': '聖依撒伯爾．匈牙利（修女）',
	'dedication-of-peter-and-paul': '聖伯多祿大殿及聖保祿大殿奉獻日',
	'presentation-of-mary': '獻聖母於聖殿',
	cecilia: '聖則濟利亞（貞女、殉道）',
	'clement-i': '聖克萊孟一世（教宗、殉道）',
	columban: '聖高隆邦（院長）',
	'andrew-dung-lac': '聖陳安勇樂（司鐸）及同伴（殉道）',
	'catherine-of-alexandria': '聖加大利納．亞力大卓（貞女、殉道）',
	andrew: '聖安德肋（宗徒）',
	'francis-xavier': '聖方濟．沙勿略（司鐸）',
	'john-damascene': '聖若望．達瑪森（司鐸、聖師）',
	nicholas: '聖尼各老（主教）',
	ambrose: '聖安博（主教、聖師）',
	'immaculate-conception': '聖母無玷始胎',
	'juan-diego': '聖若望．迪達谷',
	'our-lady-of-loreto': '洛雷托聖母',
	'damasus-i': '聖達瑪穌一世（教宗）',
	'our-lady-of-guadalupe': '瓜達盧佩聖母',
	lucy: '聖路濟亞（貞女、殉道）',
	'john-of-the-cross': '聖十字若望（司鐸、聖師）',
	'peter-canisius': '聖加尼修（司鐸、聖師）',
	'john-of-kanty': '聖若望．甘迪（司鐸）',
	stephen: '聖斯德望（首位殉道）',
	'john-evangelist': '聖若望（宗徒、聖史）',
	'holy-innocents': '諸聖嬰孩（殉道）',
	'thomas-becket': '聖多瑪斯．百克（主教、殉道）',
	'sylvester-i': '聖西物斯德一世（教宗）',

	/* The Proper of Time, for the days the Missal names outright. */
	christmas: '耶穌聖誕',
	'holy-family': '聖家',
	'mary-mother-of-god': '天主之母聖瑪利亞',
	epiphany: '主顯',
	'baptism-of-the-lord': '主受洗',
	'ash-wednesday': '聖灰禮儀星期三',
	'palm-sunday': '基督苦難主日（聖枝主日）',
	'holy-thursday': '聖週四：主的晚餐',
	'good-friday': '聖週五：救主受難紀念',
	'holy-saturday': '聖週六',
	'easter-sunday': '耶穌復活主日',
	'easter-2-sunday': '復活期第二主日（救主慈悲主日）',
	ascension: '耶穌升天',
	pentecost: '五旬節主日',
	trinity: '天主聖三',
	'corpus-christi': '基督聖體聖血',
	'sacred-heart': '耶穌聖心',
	'immaculate-heart': '聖母無玷之心',
	'mary-mother-of-the-church': '教會之母',
	'christ-the-king': '我們的主、耶穌基督、普世君王'
};

/**
 * The Proper of Time in Traditional Chinese, in pieces.
 *
 * Not a table of names: the twenty-odd words this language builds a ferial
 * day out of, and the fifteen patterns that arrange them.
 * `../names.svelte.ts` has where they came from and how they were solved
 * for; `../types.ts` has what a `NameForm` is.
 */
export const zhtTemporal: TemporalNames = {
	days: { 1: '一', 2: '二', 3: '三', 4: '四', 5: '五', 6: '六' },
	weeks: {
		1: '一',
		2: '二',
		3: '三',
		4: '四',
		5: '五',
		6: '六',
		7: '七',
		8: '八',
		9: '九',
		10: '十',
		11: '十一',
		12: '十二',
		13: '十三',
		14: '十四',
		15: '十五',
		16: '十六',
		17: '十七',
		18: '十八',
		19: '十九',
		20: '二十',
		21: '二十一',
		22: '二十二',
		23: '二十三',
		24: '二十四',
		25: '二十五',
		26: '二十六',
		27: '二十七',
		28: '二十八',
		29: '二十九',
		30: '三十',
		31: '三十一',
		32: '三十二',
		33: '三十三',
		34: '三十四'
	},
	octave: { 5: '五', 6: '六', 7: '七' },
	sunday: {
		advent: '將臨期第{week}主日',
		lent: '四旬期第{week}主日',
		easter: '復活期第{week}主日',
		ordinary: '常年期第{week}主日'
	},
	weekday: {
		advent: '將臨期第{week}週星期{day}',
		lent: '四旬期第{week}週星期{day}',
		easter: '復活期第{week}週星期{day}',
		ordinary: '常年期第{week}週星期{day}'
	},
	holyWeek: '聖週{day}',
	afterAshes: '聖灰禮儀後星期{day}',
	afterEpiphany: '主顯節後星期{day}',
	christmasWeekday: '聖誕期平日星期{day}',
	easterOctave: '復活節八日慶祝期星期{day}',
	christmasOctave: '聖誕慶期第{nth}日'
};
