/**
 * Propers that several national calendars carry identically.
 *
 * GENERATED by `pipeline/derive_national_calendars.py` -- do not edit. Each
 * constant below is the intersection of its members' derived propers, at
 * whole-date granularity: a date is here only where EVERY member of the group
 * holds an identical list of celebrations on it, same ids, ranks, colours and
 * names. A member that stops agreeing simply keeps the date in its own file
 * on the next run.
 *
 * ## These are measurements, not claims about authority
 *
 * The names describe who shares the rows, and nothing more. AMECEA is the
 * plausible explanation of the eastern African set and the *Regionalkalender
 * fur das deutsche Sprachgebiet* of the German-language one, and this project
 * has verified neither -- what it has verified, on every run, is that the
 * rows are the same. Do not read a group as saying that some body approved
 * it, and do not add a member by hand on the grounds that it ought to belong.
 *
 * ## What this changes about checking, which is nothing
 *
 * `oracle.test.ts` compares the calendar this project COMPUTES against the
 * calendar GCatholic computes, day by day, per country. It never reads a
 * layer file, so a shared set is invisible to it and every member goes on
 * being checked whole. That is what makes this a deduplication of the data
 * rather than an assertion about it -- and it is why it was safe to do at
 * all. See `withGroup` in `./common.ts`.
 */

import { proper } from './common';
import type { Celebration } from '../types';

/** Carried identically by Kenya, Sudan, Uganda, South Africa. */
export const EASTERN_AFRICA: Record<string, Celebration[]> = {
	'01-09': [proper('adrian-of-canterbury', { en: 'Saint Adrian of Canterbury, abbot' }, 'o')],
	'01-20': [proper('cyprian-michael-tansi', { en: 'Blessed Cyprian Michael Tansi, priest' }, 'o')],
	'02-26': [
		proper('alexander-of-alexandria', { en: 'Saint Alexander of Alexandria, bishop' }, 'o')
	],
	'04-04': [
		proper('benedict-the-moor', { en: 'Saint Benedict the Moor, religious' }, 'o', {
			colour: 'violet'
		})
	],
	'04-12': [proper('zeno-of-verona', { en: 'Saint Zeno of Verona, bishop' }, 'o')],
	'04-20': [proper('marcellinus-of-embrun', { en: 'Saint Marcellinus of Embrun, bishop' }, 'o')],
	'04-30': [proper('mother-of-africa', { en: 'Our Lady Mother of Africa' }, 'f')],
	'05-24': [proper('help-of-christians', { en: 'Our Lady Help of Christians' }, 'm')],
	'06-12': [proper('onuphrius', { en: 'Saint Onuphrius, abbot' }, 'o')],
	'07-28': [proper('victor-i', { en: 'Saint Victor I, pope and martyr' }, 'o', { colour: 'red' })],
	'07-30': [proper('justin-de-jacobis', { en: 'Saint Justin de Jacobis, bishop' }, 'o')],
	'08-12': [
		proper('isidore-bakanja', { en: 'Blessed Isidore Bakanja, martyr' }, 'o', { colour: 'red' })
	],
	'08-18': [proper('victoria-rasoamanarivo', { en: 'Blessed Victoria Rasoamanarivo' }, 'o')],
	'09-22': [
		proper(
			'maurice-of-agaune-and-companions',
			{ en: 'Saint Maurice of Agaune and companions, martyrs' },
			'o',
			{ colour: 'red' }
		)
	],
	'10-20': [
		proper(
			'daudi-okelo-and-blessed-jildo-irwa',
			{ en: 'Blessed Daudi Okelo and Blessed Jildo Irwa, martyrs' },
			'o',
			{ colour: 'red' }
		)
	],
	'11-06': [proper('all-saints-of-africa', { en: 'All Saints of Africa' }, 'm')],
	'12-01': [
		proper(
			'marie-clementine-anuarite-nengapeta',
			{ en: 'Blessed Marie-Clémentine Anuarite Nengapeta, virgin and martyr' },
			'o',
			{ colour: 'red' }
		)
	]
};

/** Carried identically by Austria, Liechtenstein. */
export const GERMAN_LANGUAGE_AREA: Record<string, Celebration[]> = {
	'01-07': [
		proper(
			'valentine-of-raetia',
			{ de: 'Hl. Valentin von Rätien, Bischof', en: 'Saint Valentine of Raetia, bishop' },
			'o'
		)
	],
	'01-08': [
		proper(
			'severin-of-noricum',
			{ de: 'Hl. Severin, Mönch', en: 'Saint Severin of Noricum, religious' },
			'o'
		)
	],
	'01-21': [
		proper(
			'meinrad-of-einsiedeln',
			{
				de: 'Hl. Meinrad, Einsiedler, Märtyrer',
				en: 'Saint Meinrad of Einsiedeln, hermit and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'01-23': [
		proper(
			'henry-suso',
			{ de: 'Sel. Heinrich Seuse, Ordenspriester', en: 'Blessed Henry Suso, priest' },
			'o'
		)
	],
	'02-25': [
		proper('walburga', { de: 'Hl. Walburga, Äbtissin', en: 'Saint Walburga, abbess' }, 'o')
	],
	'03-06': [
		proper(
			'fridolin-of-sackingen',
			{ de: 'Hl. Fridolin von Säckingen, Mönch', en: 'Saint Fridolin of Säckingen, monk' },
			'o',
			{ colour: 'violet' }
		)
	],
	'03-09': [
		proper(
			'bruno-of-querfurt',
			{
				de: 'Hl. Bruno von Querfurt, Bischof, Märtyrer',
				en: 'Saint Bruno of Querfurt, bishop and martyr'
			},
			'o',
			{ colour: 'violet' }
		)
	],
	'03-14': [
		proper('mathilda', { de: 'Hl. Mathilde', en: 'Saint Mathilda' }, 'o', { colour: 'violet' })
	],
	'03-15': [
		proper(
			'clement-mary-hofbauer',
			{
				de: 'Hl. Klemens Maria Hofbauer, Ordenspriester',
				en: 'Saint Clement Mary Hofbauer, priest'
			},
			'o',
			{ colour: 'violet' }
		)
	],
	'03-17': [
		proper('gertrude', { de: 'Hl. Gertrud, Äbtissin', en: 'Saint Gertrude, abbess' }, 'o', {
			colour: 'violet'
		})
	],
	'04-19': [proper('leo-ix', { de: 'Hl. Leo IX., Papst', en: 'Saint Leo IX, pope' }, 'o')],
	'04-21': [
		proper(
			'conrad-of-parzham',
			{ de: 'Hl. Konrad von Parzham, Ordensmann', en: 'Saint Conrad of Parzham, religious' },
			'o'
		)
	],
	'05-04': [
		proper(
			'florian-and-companions',
			{
				de: 'Hl. Florian und heilige Märtyrer von Lorch',
				en: 'Saint Florian and companions, martyrs'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'05-05': [
		proper(
			'gotthard-of-hildesheim',
			{ de: 'Hl. Godehard von Hildesheim, Bischof', en: 'Saint Gotthard of Hildesheim, bishop' },
			'o'
		)
	],
	'05-16': [
		proper(
			'john-of-nepomuk',
			{
				de: 'Hl. Johannes Nepomuk, Priester, Märtyrer',
				en: 'Saint John of Nepomuk, priest and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'06-15': [
		proper('vitus', { de: 'Hl. Vitus, Märtyrer', en: 'Saint Vitus, martyr' }, 'o', {
			colour: 'red'
		})
	],
	'06-16': [proper('benno', { de: 'Hl. Benno, Bischof', en: 'Saint Benno, bishop' }, 'o')],
	'06-26': [
		proper(
			'josemaria-escriva-de-balaguer',
			{
				de: 'Hl. Josefmaria Escrivá de Balaguer, Priester',
				en: 'Saint Josemaría Escrivá de Balaguer, priest'
			},
			'o'
		)
	],
	'06-30': [
		proper(
			'otto-of-bamberg',
			{ de: 'Hl. Otto von Bamberg, Bischof', en: 'Saint Otto of Bamberg, bishop' },
			'o'
		)
	],
	'07-04': [
		proper(
			'ulrich-of-augsburg',
			{ de: 'Hl. Ulrich von Augsburg, Bischof', en: 'Saint Ulrich of Augsburg, bishop' },
			'o'
		)
	],
	'07-07': [
		proper('willibald', { de: 'Hl. Willibald, Bischof', en: 'Saint Willibald, bishop' }, 'o')
	],
	'07-08': [
		proper(
			'kilian',
			{
				de: 'Hl. Kilian, Bischof, und Gefährten, Märtyrer',
				en: 'Saint Kilian, bishop, and companions, martyrs'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'07-10': [
		proper(
			'canute-iv',
			{
				de: 'Hl. Knud IV., hl. Erich IX., Märtyrer, und hl. Olaf II.',
				en: 'Saint Canute IV, Saint Eric IX, martyrs, and Saint Olaf II'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'07-20': [
		proper(
			'margaret-of-antioch',
			{
				de: 'Hl. Margareta von Antiochien, Jungfrau, Märtyrin',
				en: 'Saint Margaret of Antioch, virgin and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'07-24': [
		proper(
			'christopher',
			{ de: 'Hl. Christophorus, Märtyrer', en: 'Saint Christopher, martyr' },
			'o',
			{ colour: 'red' }
		)
	],
	'08-31': [
		proper(
			'paulinus-of-trier',
			{
				de: 'Hl. Paulinus von Trier, Bischof, Märtyrer',
				en: 'Saint Paulinus of Trier, bishop and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'09-18': [
		proper(
			'lambert-of-maastricht',
			{
				de: 'Hl. Lambert von Maastricht, Bischof, Märtyrer',
				en: 'Saint Lambert of Maastricht, bishop and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'09-22': [
		proper(
			'maurice-of-agaune-and-companions',
			{
				de: 'Hl. Mauritius und Gefährten, Märtyrer',
				en: 'Saint Maurice of Agaune and companions, martyrs'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'09-24': [
		proper(
			'rupert-and-saint-vergilius',
			{
				de: 'Hl. Rupert und hl. Virgil, Bischöfe',
				en: 'Saint Rupert and Saint Vergilius, bishops'
			},
			'o'
		)
	],
	'09-28': [proper('leoba', { de: 'Hl. Lioba, Äbtissin', en: 'Saint Leoba, abbess' }, 'o')],
	'10-20': [
		proper(
			'wendelin-of-trier',
			{ de: 'Hl. Wendelin, Einsiedler', en: 'Saint Wendelin of Trier, hermit' },
			'o'
		)
	],
	'11-03': [
		proper(
			'hubertus-of-liege',
			{ de: 'Hl. Hubert von Lüttich, Bischof', en: 'Saint Hubertus of Liège, bishop' },
			'o'
		),
		proper('pirmin', { de: 'Hl. Pirmin, Abtbischof', en: 'Saint Pirmin, abbot and bishop' }, 'o')
	],
	'11-06': [
		proper(
			'leonard-of-noblac',
			{ de: 'Hl. Leonhard, Einsiedler', en: 'Saint Leonard of Noblac, abbot' },
			'o'
		)
	],
	'11-07': [
		proper('willibrord', { de: 'Hl. Willibrord, Bischof', en: 'Saint Willibrord, bishop' }, 'o')
	],
	'11-15': [
		proper(
			'leopold',
			{ de: 'Hl. Leopold, Markgraf von Österreich', en: 'Saint Leopold, Margrave of Austria' },
			'o'
		)
	],
	'11-26': [
		proper(
			'conrad-and-saint-gebhard',
			{ de: 'Hl. Konrad und hl. Gebhard, Bischöfe', en: 'Saint Conrad and Saint Gebhard, bishops' },
			'o'
		)
	],
	'12-04': [
		proper(
			'barbara',
			{ de: 'Hl. Barbara, Märtyrin', en: 'Saint Barbara, virgin and martyr' },
			'o',
			{ colour: 'red' }
		)
	],
	'12-05': [
		proper(
			'anno-of-cologne',
			{ de: 'Hl. Anno von Köln, Bischof', en: 'Saint Anno of Cologne, bishop' },
			'o'
		)
	],
	'12-13': [
		proper(
			'odilia-of-alsace',
			{ de: 'Hl. Odilia, Äbtissin', en: 'Saint Odilia of Alsace, abbess' },
			'o'
		)
	]
};

/** Carried identically by Algeria, Tunisia. */
export const NORTH_AFRICA: Record<string, Celebration[]> = {
	'01-03': [
		proper(
			'fulgentius-of-ruspe',
			{ fr: 'Saint Fulgence de Ruspe, évêque', en: 'Saint Fulgentius of Ruspe, bishop' },
			'm'
		)
	],
	'01-08': [
		proper(
			'quodvultdeus-and-saint-deogratias',
			{
				fr: 'Saint Quodvultdeus et Saint Deogratias, évêques',
				en: 'Saint Quodvultdeus and Saint Deogratias, bishops'
			},
			'o'
		)
	],
	'04-30': [
		proper('mother-of-africa', { fr: 'Notre-Dame d’Afrique', en: 'Our Lady Mother of Africa' }, 's')
	],
	'06-04': [
		proper(
			'optatus-of-milevis',
			{ fr: 'Saint Optat de Milev, évêque', en: 'Saint Optatus of Milevis, bishop' },
			'm'
		)
	],
	'06-26': [
		proper(
			'josemaria-escriva-de-balaguer',
			{
				fr: 'Saint Josemaria Escrivá de Balaguer, prêtre',
				en: 'Saint Josemaría Escrivá de Balaguer, priest'
			},
			'o'
		)
	],
	'07-10': [
		proper(
			'marciana-of-mauretania',
			{
				fr: 'Sainte Marcienne de Dellys, vierge et martyre',
				en: 'Saint Marciana of Mauretania, virgin and martyr'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'07-17': [
		proper(
			'speratus-and-companions',
			{
				fr: 'Saint Spérat et ses compagnons, martyrs Scillitains',
				en: 'Saint Speratus and companions, martyrs of Scillium'
			},
			'm',
			{ colour: 'red' }
		)
	],
	'09-10': [
		proper(
			'nemesian',
			{
				fr: 'Saint Némésianus, évêque, et ses compagnons, martyrs',
				en: 'Saint Nemesian, bishop, and companions, martyrs'
			},
			'o',
			{ colour: 'red' }
		)
	],
	'09-12': [
		proper(
			'marcellinus-of-carthage',
			{ fr: 'Saint Marcellin de Carthage, martyr', en: 'Saint Marcellinus of Carthage, martyr' },
			'o',
			{ colour: 'red' }
		)
	],
	'10-30': [
		proper(
			'marcellus-of-tangier-and-saint-maximilian-of-numidia',
			{
				fr: 'Saint Marcel et Saint Maximilien, martyrs',
				en: 'Saint Marcellus of Tangier and Saint Maximilian of Numidia, martyrs'
			},
			'm',
			{ colour: 'red' }
		)
	],
	'12-01': [
		proper(
			'charles-de-foucauld',
			{ fr: 'Saint Charles de Foucauld, prêtre', en: 'Saint Charles de Foucauld, priest' },
			'o'
		)
	],
	'12-05': [
		proper('crispina', { fr: 'Sainte Crispine, martyre', en: 'Saint Crispina, martyr' }, 'm', {
			colour: 'red'
		})
	]
};
