import { describe, expect, it } from 'vitest';
import { withGroup } from './common';
import { EASTERN_AFRICA, GERMAN_LANGUAGE_AREA, NORTH_AFRICA } from './groups';
import { KENYA } from './ke';
import { SUDAN } from './sd';
import { UGANDA } from './ug';
import { SOUTH_AFRICA } from './za';
import { ALGERIA } from './dz';
import { TUNISIA } from './tn';
import { AUSTRIA } from './at';
import { LIECHTENSTEIN } from './li';
import type { NationalCalendar } from '../types';

/**
 * The shared proper sets, and the one property that makes them safe.
 *
 * `groups.ts` and its members are all generated by
 * `pipeline/derive_national_calendars.py`, so nothing here is checking a
 * person's typing. What it checks is that the GENERATOR's invariant survives
 * in the files it wrote — which matters because the invariant is the entire
 * argument for factoring the rows out at all: **a group may never change what
 * a country celebrates.**
 *
 * WHY THIS RUNS IN THE HERMETIC SUITE AND NOT BESIDE THE ORACLE. `withGroup`
 * throws on a collision at module load, which would be caught by anything
 * that imports a member — and until this file existed, nothing in `npm test`
 * did: `year.test.ts` imports Brazil, which is hand-written and in no group,
 * and `oracle.test.ts` (which imports every layer) moved out of the default
 * run when the oracle moved to the corpus. So the throw was unreachable
 * without a corpus checkout, and the corpus is the one thing this suite is
 * guaranteed not to have.
 */

const GROUPS: readonly {
	name: string;
	group: Record<string, unknown[]>;
	members: readonly NationalCalendar[];
}[] = [
	{
		name: 'EASTERN_AFRICA',
		group: EASTERN_AFRICA,
		members: [KENYA, SUDAN, UGANDA, SOUTH_AFRICA]
	},
	{ name: 'NORTH_AFRICA', group: NORTH_AFRICA, members: [ALGERIA, TUNISIA] },
	{
		name: 'GERMAN_LANGUAGE_AREA',
		group: GERMAN_LANGUAGE_AREA,
		members: [AUSTRIA, LIECHTENSTEIN]
	}
];

describe('shared propers', () => {
	it('reached every member of every group', () => {
		// A generation bug that wrote `groups.ts` and forgot to point a member
		// at it costs that country its shared celebrations, and nothing else
		// in this repository would notice without the corpus: the layer is
		// still valid, still type-checks, and simply keeps fewer feasts.
		for (const { name, group, members } of GROUPS) {
			expect(Object.keys(group).length, `${name} is empty`).toBeGreaterThan(0);
			for (const member of members) {
				for (const mmdd of Object.keys(group)) {
					expect(member.propers[mmdd], `${member.id} is missing ${name} ${mmdd}`).toEqual(
						group[mmdd]
					);
				}
			}
		}
	});

	it('refuses a member that carries its own proper on a group’s date', () => {
		// THE SAFETY PROPERTY, stated as the failure it prevents. A spread
		// would resolve a collision silently and the winner would depend on
		// argument order — so a country could lose a celebration its
		// conference approved because a group it belongs to also uses that
		// date, with nothing to report it.
		expect(() => withGroup({ '01-09': [] }, { '01-09': [] })).toThrow(/01-09/);
		expect(() => withGroup({ '01-09': [] }, { '01-10': [] })).not.toThrow();
	});
});
